[ADD] web_widget_date_interval
OCA/web pull request #1001
Opened 2018-07-23 16:49 UTC by hbrunn

This is a widget for date intervals, currently only implemented for search views (the form part will be a migration of https://github.com/OCA/web/pull/575).

For testing, open the users list on runbot and play with the two extra dropdowns allowing you to filter for some intervals on the fields `create_date` and `last_login`

2019-01-03 21:06 UTC, ovnicraft commented
@hbrunn any updates ?

2019-01-07 07:53 UTC, hbrunn commented
not at the moment, but the addon is not dead. If you prefer, I can close this until I start working on it again. It's already useful for me, so I figured it might be for others as well, that's why I kept the PR here

2019-01-08 15:54 UTC, ovnicraft commented
@hbrunn so its usable? 
We can review and merge it, so in next pr you can improve it.

2019-01-08 16:04 UTC, hbrunn commented
well, usable is a big word. For now, you can add something like
![screenshot_2019-01-08_17-01-45](https://user-images.githubusercontent.com/2563186/50842523-2da72a00-1367-11e9-8e3b-3890bbec7781.png)
to a search view, which allows you to cycle through calendar (iso) weeks of whatever date{,time} field you configured quickly. But it's not feature complete, so I think it will be quite a bummer for people to see this merged but not be able to do a lot of stuff, like having a form widget for date intervals

2019-01-08 19:30 UTC, ovnicraft commented
Ok, so wait until you have time to end it 👍

2019-01-09 04:44 UTC, nikul-serpentcs requested changes
Minor change

2019-01-09 04:44 UTC, nikul-serpentcs commented on web_widget_date_interval/__manifest__.py
> +    "author": "Therp BV,Odoo Community Association (OCA)",
add `website` [like](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L11)

2022-12-11 12:33 UTC, closed without merging