[FIX] web_widget_char_switchcase: keep caret position
OCA/web pull request #1085
Opened 2018-10-18 08:42 UTC by SimoRubi

Keep caret position after changing the value

2018-10-18 09:16 UTC, eLBati approved these changes
tested

2018-10-18 09:32 UTC, astirpe reviewed
In Travis I read this:

```
ERROR openerp_test odoo.tests.common: phantomjs: error
```

2018-10-18 10:00 UTC, SimoRubi commented
Thanks @astirpe I still had to check Travis, now it should be good

2018-10-18 14:21 UTC, astirpe requested changes

2018-10-18 14:21 UTC, astirpe commented on web_widget_char_switchcase/static/src/js/web_widget_char_switchcase.js
> +            // save caret position
Please check travis warnings:
```
web_widget_char_switchcase/static/src/js/web_widget_char_switchcase.js:24: [W7903(javascript-lint), ] Comments should not begin with a lowercase character [Error/capitalized-comments]
```

2018-10-18 14:21 UTC, astirpe commented on web_widget_char_switchcase/static/src/js/web_widget_char_switchcase.js
> +
```
web_widget_char_switchcase/static/src/js/web_widget_char_switchcase.js:28: [W7903(javascript-lint), ] Trailing spaces not allowed. [Error/no-trailing-spaces]
```

2018-10-18 14:23 UTC, SimoRubi commented
@astirpe now travis is :heavy_check_mark:

2018-10-18 14:25 UTC, astirpe commented
I mean here: https://travis-ci.org/OCA/web/jobs/443104196

2018-10-18 15:28 UTC, SimoRubi commented
@astirpe I have fixed most JSLint warnings, Travis now is :heavy_check_mark: (as it was before, since JSLint doesn't make the build fail)

2018-10-18 16:04 UTC, astirpe approved these changes
Thank you!

2018-10-19 07:35 UTC, SimoRubi commented
Fixed up

2018-10-22 14:01 UTC, SimoRubi commented
@simahawk sorry to bother you again, but you already know this module so well!
Could you please review? I also solved most of the JSLint warnings!
Thanks

2018-10-23 06:29 UTC, simahawk approved these changes

2018-10-23 06:29 UTC, merged

2018-10-23 06:30 UTC, simahawk commented
thanks for keeping commits clear ;)