[11.0][FIX] add_events calling and add jsdocs
OCA/web pull request #1087
Opened 2018-10-19 08:57 UTC by tarteo

Issue: https://github.com/OCA/web/issues/1077

2018-10-19 09:43 UTC, simahawk commented
@tarteo any chance to have separated commits? Makes really hard to understand where the fix is... :wink:

2018-10-19 10:06 UTC, tarteo commented
@simahawk Sorry :smile:, Now it should be clear.

2018-10-19 11:02 UTC, simahawk requested changes
wouldn't be better to delegate events binding to https://github.com/OCA/web/blob/a9130d5cc555af14e469e7d2256b844ef7648cc8/web_timeline/static/src/js/timeline_renderer.js#L18 ?

2018-10-19 11:34 UTC, tarteo commented
@simahawk This PR just fixes #1077 and makes travis green, I'm not trying to refactor it.

2018-10-19 11:43 UTC, astirpe approved these changes

2018-10-19 11:44 UTC, simahawk commented
@tarteo I'm not proposing a refactoring: I'm proposing to fix this in a better way :wink: 
Then you can tell me "is not going to work in this case" and I surrender :smile:

2018-10-19 12:41 UTC, tarteo commented
@simahawk Oh I see, I understand now. Thanks I didn't notice but of course I'll fix it the Odoo way! :+1: :+1:

2018-10-19 13:04 UTC, simahawk approved these changes
LG :)
Can you squash the last 2 commits?

2018-10-19 13:05 UTC, simahawk commented
plus, please, prefix all commits w/ module name ;)

2018-10-26 08:48 UTC, astirpe commented
This one can be merged IMO

2018-10-26 09:29 UTC, merged

2018-10-26 09:29 UTC, pedrobaeza commented
Please include it in 12.0 migration