11.0
OCA/web pull request #1102
Opened 2018-11-14 20:55 UTC by jpcweb

Add filters in the 1st line to the exported file

2018-11-14 21:00 UTC, pedrobaeza commented
Next time please put a better title, not only `11.0`. I see that the changes seem to be higher than what you explain. Can you talk about this and put screenshots?

2018-11-14 23:37 UTC, jpcweb commented
I'm sorry about the title, your are right.
The main purpose is to add the filters in the exported excel file.
Indeed it could be interested to have the context of the export when sharing the document.
I've attached a screenshot and the export file.

The .txt file is a .xls file (you just have to change the file extension to .xls)

![filter_and_export](https://user-images.githubusercontent.com/5606551/48519787-40dbc480-e812-11e8-82a1-51d5c00118ef.png)

[product.template.txt](https://github.com/OCA/web/files/2583082/product.template.txt)

2018-11-15 00:57 UTC, pedrobaeza commented
Thanks for explaining. I'm not sure this is so interesting, but I let other reviewers to decide.

2018-11-15 01:04 UTC, moylop260 commented on web_export_view/controllers/controllers.py
> +import functools
Could you remove the unused libraries, please?

2018-11-15 01:05 UTC, moylop260 commented on web_export_view/controllers/controllers.py
> +import functools
FYI you can check them from: https://travis-ci.org/OCA/web/jobs/455191769#L564

2018-11-15 01:06 UTC, moylop260 reviewed
Is possible add a unittest?

2018-11-15 06:36 UTC, simahawk requested changes
please fix jslint + pylint.
Also, a screenshot of the final result to add to README would be nice.

2018-11-15 06:36 UTC, simahawk commented on web_export_view/controllers/controllers.py
> +                if isinstance(cell_value, bytes) and not isinstance(cell_value, pycompat.string_types):
I'd move this block out to a method returning cell_value and cell_style

2018-11-15 06:36 UTC, simahawk commented on web_export_view/controllers/controllers.py
> +        fp = io.BytesIO()
use a context manager

2018-11-15 06:36 UTC, simahawk commented on web_export_view/controllers/controllers.py
> +            self.from_data(columns_headers, rows, columns_searchs),
`search=columns_search`

2018-11-15 06:36 UTC, simahawk commented on web_export_view/static/src/js/web_export_view.js
> +            $('.o_facet_values > span').each(function() {
`this.$('.o_facet_values > span')`

2019-03-05 14:15 UTC, tarteo requested changes

2019-03-05 14:15 UTC, tarteo commented on web_export_view/controllers/controllers.py
> +            worksheet.write(pos, 0, "Les filtres: ")
Please use english `_t('Les filtres')`

2019-08-14 17:27 UTC, mreficent commented
conflicts

2019-10-24 13:19 UTC, daramousk requested changes
Hello and thanks for this,

Now, since this has been inactive for a while, I would like to ask if @jpcweb will continue with this or should someone else take over, if yes then please do the following so that people can properly review

1) Make everything in CI pipeline green, check the error messages one by one and fix them
2) Add tests. This seems like a complicated implementation and we need to be sure nothing breaks
3) Rebase on top of 11.0 to fix the conflicts.

Then we can continue with reviewing.

Thanks

2023-02-12 12:32 UTC, closed without merging