[12.0][MIG] web_ir_actions_act_view_reload
OCA/web pull request #1104
Opened 2018-11-19 16:30 UTC by alexey-pelykh

2018-11-19 16:31 UTC, alexey-pelykh commented
@pnajman-modoolar would like to ask for your review, if you don't mind

2018-11-19 16:41 UTC, pnajman-modoolar approved these changes
Thanks for the migration :)
Approved.

2018-11-19 16:43 UTC, alexey-pelykh commented
@pnajman-modoolar Thanks for the review! Do you know anyone else to summon who may review as well?

2018-11-19 16:59 UTC, pnajman-modoolar commented
@alexey-pelykh You could try with good people who reviewed version 11.0 of this module.
I would look them up in the 11.0 pull request.

2018-11-19 17:18 UTC, alexey-pelykh commented
Good people of 11.0 PR (@elicoidal @simahawk @bealdav @zaoral), I summon you to take a look on this PR if you don't mind

2018-11-20 02:07 UTC, elicoidal approved these changes
LGTM

2018-11-20 02:07 UTC, elicoidal commented on web_ir_actions_act_view_reload/views/web_ir_actions_act_view_reload.xml
> +# Copyright 2017 - 2018 Modoolar <info@modoolar.com>
remove `# `

2018-11-20 04:53 UTC, alexey-pelykh commented
Thanks for the reviews! I'd be glad to help likewise, thus feel free to summon me 👍

2018-11-20 08:26 UTC, simahawk requested changes
LG, just a question

2018-11-20 08:26 UTC, simahawk commented on web_ir_actions_act_view_reload/static/src/js/web_ir_actions_act_view_reload.js
> +                var controller = this.controllers[this.controllerStack[0]]
shouldn't you use `getCurrentController`?

2018-11-20 08:40 UTC, alexey-pelykh commented on web_ir_actions_act_view_reload/static/src/js/web_ir_actions_act_view_reload.js
> +                var controller = this.controllers[this.controllerStack[0]]
Good point, haven't found that function, thanks for hint - updated

2018-11-20 09:44 UTC, alexey-pelykh commented
@simahawk please re-review

2018-11-20 11:27 UTC, nikul-serpentcs requested changes
IMO Check Jslint

2018-11-20 11:28 UTC, nikul-serpentcs approved these changes
Otherwise Code LGTM

2018-11-20 11:33 UTC, alexey-pelykh commented
@nikul-serpentcs is there an automated check for it? I'm not sure how to run it on Odoo

2018-11-20 11:36 UTC, nikul-serpentcs commented
@alexey-pelykh Could you please check [here](https://travis-ci.org/OCA/web/jobs/457346440#L870-L873)

2018-11-20 13:19 UTC, simahawk commented
@alexey-pelykh LG, can you check the warnings @nikul-serpentcs linked?

2018-11-20 18:48 UTC, alexey-pelykh commented
@simahawk @nikul-serpentcs all good now

2018-11-21 10:12 UTC, simahawk commented
I still see `web_ir_actions_act_view_reload/static/src/js/web_ir_actions_act_view_reload.js:25: [W7903(javascript-lint), ] Trailing spaces not allowed. [Error/no-trailing-spaces]`

Am I wrong?

Sorry for this boring requirements but if we don't fix them while we here they are going to stay forever and maybe become errors in the future... thanks for your patience! :wink:

2018-11-21 10:14 UTC, alexey-pelykh commented
@simahawk sorry, dunno where I've looked exactly yet I can swear this warning wasn't there 🙈fixed!

2018-11-21 11:06 UTC, simahawk approved these changes

2018-11-21 11:07 UTC, merged

2018-11-21 11:07 UTC, simahawk commented
@alexey-pelykh thanks :)