[12.0] [MIG] web_tree_many2one_clickable
OCA/web pull request #1162
Opened 2019-01-20 04:10 UTC by anandkansagra

Issue [Reference](https://github.com/OCA/web/issues/1048)

2019-01-20 11:46 UTC, pedrobaeza requested changes
I'm seeing that this module has lost the possibility of defining an option as field level for indicating if clickable or not, as well as the system parameter that defines the behavior of making clickable all many2one. I think this has happened on v11

@simahawk I think you were the porter. Why removing that features?

2019-02-11 18:52 UTC, bealdav commented
@pedro I think lose the feature you said is not problematic if we can get this feature https://github.com/OCA/web/pull/1041 (not a lot of code).
May be in v12 no more fail with big web 10.0 branch.
What do you think ?

2019-02-11 19:37 UTC, pedrobaeza commented
Yes, if #1041 is implemented here, then it's enough IMO.

2019-05-25 19:04 UTC, pedrobaeza commented
Superseeded by #1290

2019-05-25 19:04 UTC, closed without merging