[ADD] web_widget_iframe: new module to display an iframe in a form view
OCA/web pull request #1165
Opened 2019-01-22 08:04 UTC by benwillig

This modules simply adds an iframe which display an iframe.

2019-01-22 08:42 UTC, tarteo requested changes
Very nice! Can you also look at the lint errors?

2019-01-22 08:42 UTC, tarteo commented on web_widget_iframe/README.rst
> +This module simply adds a new widget which display an Iframe for a given
Can you add an usage section

2019-01-22 08:42 UTC, tarteo commented on web_widget_iframe/static/src/js/web_widget_iframe.js
> +odoo.define('web_widget_iframe.web_widget_iframe', function(require) {
Can you rename the namespace to web_widget_iframe.FieldUrlIframe

2019-01-22 08:42 UTC, tarteo commented on web_widget_iframe/static/src/js/web_widget_iframe.js
> +            var self = this;
There's not really a reason for this variable you can just use `this`.

2019-01-22 08:42 UTC, tarteo commented on web_widget_iframe/static/src/js/web_widget_iframe.js
> +    var FieldChar = core.form_widget_registry.get('char');
You can also use FieldUrl which maybe automatically adds the protocol etc (don't know for sure :P).

2019-01-22 08:45 UTC, pedrobaeza commented
Isn't this a bit of security whole allowing any external object to catch data from backend?

2019-01-22 08:50 UTC, hbrunn commented
you should set `sandbox=""`, cf https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe to have this locked down by default and possibly add an option to the widget to selectively add permissions

2019-01-22 11:22 UTC, benwillig commented
@hbrunn Thanks for your feedback. I added the empty sandbox attribute by default and it can be overriden by specifying it on the field tag.

@tarteo Fixed the code based on your notes.

@pedrobaeza What do you mean?

2019-01-22 11:23 UTC, pedrobaeza commented
@benwillig the sandbox mode suggested by @hbrunn answers my concern.

2019-01-22 11:23 UTC, pedrobaeza commented on web_widget_iframe/README.rst
> +This module simply adds a new widget which display an Iframe for a given
Yes, please, with the `sandbox` part included.

2019-04-26 08:51 UTC, tarteo approved these changes

2023-03-26 12:30 UTC, closed without merging