[ADD][10.0] web_fullscreen
OCA/web pull request #1226
Opened 2019-03-26 13:34 UTC by KKamaa

2019-03-26 13:45 UTC, pedrobaeza commented
Having web_responsive, do you see this interesting?

2019-03-26 14:01 UTC, thomaspaulb commented
`web_responsive` is very cool, but pretty invasive. Customers have to really choose to go for the responsive experience. This module (ported from [v8](https://github.com/onesteinbv/addons-onestein/tree/8.0/web_fullscreen)) targets the traditional GUI and just adds a small fullscreen button on views, in order to see more clearly on small screens.

2019-03-26 14:09 UTC, pedrobaeza commented
Ok, let's have options. Please check Travis.

2019-03-26 17:19 UTC, thomaspaulb requested changes

2019-03-26 17:19 UTC, thomaspaulb commented on web_fullscreen/__manifest__.py
> +    'author': 'Onestein ,Suflower IT, Odoo Community Association (OCA)',
typo, comma position

2019-03-26 17:19 UTC, thomaspaulb commented on web_fullscreen/static/src/css/web_fullscreen.css
> +}
flake8

2019-03-26 17:19 UTC, thomaspaulb commented on web_fullscreen/static/src/js/web_fullscreen.js
> +
flake8

2019-03-26 17:48 UTC, thomaspaulb approved these changes

2019-03-26 17:49 UTC, thomaspaulb commented
@astirpe And here it is

2019-03-27 08:40 UTC, astirpe requested changes

2019-03-27 08:40 UTC, astirpe commented on web_fullscreen/__manifest__.py
> +    'website': 'http://www.onestein.eu',
```suggestion
    'website': 'https://github.com/OCA/web/',
```

2019-03-27 08:40 UTC, astirpe commented on web_fullscreen/__init__.py
> +# Copyright 2016 Onestein (<http://www.onestein.eu>)
You can remove the Copyright in the `__init__.py` file.

2019-03-27 08:40 UTC, astirpe commented on web_fullscreen/README.rst
> +
Somewhere in the readme it should be mentioned that this module is useless if `web_responsive` is installed.

And nice to have: screenshots in the readme, giving a visual effect of the functionality.

2019-04-04 10:05 UTC, nzaterrence approved these changes

2019-04-04 10:05 UTC, nzaterrence commented on web_fullscreen/static/src/xml/web_fullscreen_templates.xml
> +                <button class="btn btn-icon fa fa-lg fa-tablet"
@KKamaa We can find a better icon for this button, still looks weird.

2019-04-04 11:08 UTC, astirpe approved these changes

2019-04-09 14:32 UTC, tarteo requested changes

2019-04-09 14:32 UTC, tarteo commented on web_fullscreen/static/src/js/web_fullscreen.js
> +            this.$el.on('click', '.o_cp_fullscreen', function (e) {
Remove variable `e` and the eslint directive.

2019-04-09 14:32 UTC, tarteo commented on web_fullscreen/views/web_fullscreen_view.xml
> +<openerp>
change this to <odoo>

2019-04-09 14:32 UTC, tarteo commented on web_fullscreen/static/src/css/web_fullscreen.css
> +}
Add an extra empty line here

2019-04-09 14:32 UTC, tarteo commented on web_fullscreen/README.rst
> +==========
Add an extra empty line here otherwise the markup fails.

2019-04-09 14:32 UTC, tarteo commented
Small remarks otherwise :+1:

2019-04-16 07:40 UTC, tarteo approved these changes

2019-04-16 07:43 UTC, tarteo commented
@pedrobaeza Must the commit history be included for migration from 8 to 10?

2019-04-16 11:45 UTC, pedrobaeza commented
@tarteo I don't see this module in v8. Or it was in another repository?

2019-04-16 12:25 UTC, thomaspaulb commented
Comes from [here](https://github.com/onesteinbv/addons-onestein/tree/8.0/web_fullscreen), we had permission to introduce the port here.

2019-04-16 12:28 UTC, pedrobaeza commented
Then you must preserve commit history indeed.

2019-04-16 12:29 UTC, pedrobaeza submitted a review, later dismissed
Preserve commit history and squash your migration commits.

2019-04-17 15:27 UTC, thomaspaulb commented
@pedrobaeza Commits now retained, codecov error seems unrelated

2019-04-17 16:41 UTC, pedrobaeza commented
OK, I have removed my review as it was only for that. No review on the module itself.

2019-04-17 19:12 UTC, thomaspaulb commented
@astirpe ?

2019-04-17 19:33 UTC, thomaspaulb commented
@pedrobaeza How many more reviews do we need?

2019-04-17 19:34 UTC, pedrobaeza commented
OK, merging

2019-04-17 19:34 UTC, merged

2019-04-17 19:35 UTC, thomaspaulb commented
Thanks!