[12.0][ADD] web_widget_uom
OCA/web pull request #1279
Opened 2019-05-08 14:16 UTC by ageficent

This module aims to allow the user to decide how many decimal places should be displayed in the Odoo User Interface for each Unit of Measure.

![image](https://user-images.githubusercontent.com/44768500/57382108-9636d400-71ac-11e9-84f0-7ed33bcb4432.png)

2019-06-05 16:28 UTC, Tardo requested changes

2019-06-05 16:28 UTC, Tardo commented on web_widget_uom/static/src/js/widget.js
> +            var decimal_places = 4;
Never used

2019-06-14 23:25 UTC, Tardo commented on web_widget_uom/static/src/js/widget.js
> +            this._getDecimalPlaces().then(function (){
I think that 'always' would be more appropriate.

2019-10-21 09:42 UTC, daramousk reviewed
Thanks for this, I wonder if a purely backend solution would be feasible and/or more appropriate here, something like this:

1) For all the fields that are foreign keys to `uom.uom`
2) inject the digits attribute in the appropriate place in the initialization phase of the `class Float`

So now you could have a piece of code that runs once and avoids all the js.

What do you think?

2019-10-21 09:42 UTC, daramousk commented on web_widget_uom/static/src/js/widget.js
> +                method: 'get_decimal_places',
Why not just get the data here and avoid defining that `get_decimal_places` completely?

2019-10-21 09:42 UTC, daramousk commented on web_widget_uom/static/src/js/widget.js
> +        init: function () {
This init does not seem to be doing anything, the docstrings are pretty much copies of their super definitions so I believe you could remove these as well.

2023-06-18 12:29 UTC, closed without merging