[11.0][MIG] web_switch_company_warning
OCA/web pull request #1288
Opened 2019-05-24 12:03 UTC by ageficent

Standard migration of module web_switch_company_warning to v11 from #1287 

cc ~ @Eficent

2019-05-24 12:10 UTC, pedrobaeza commented
A bit of commit squashing is recommended

2019-05-24 12:30 UTC, tbaden requested changes
thanks for the work 👍 
I did a code review: here some changes.
for js it's the easiest way to use eslint with the oca [configuration](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#4javascript)

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/__manifest__.py
> +    "website": "http://akretion.com",
Please use the website https://github.com/OCA/web

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +    //Show a big banner in the top of the page if the company has been
[W7903(javascript-lint), ] Expected space or tab after '//' in comment. [Error/spaced-comment]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +    //changed in another tab or window (in the same browser)
[W7903(javascript-lint), ] Expected space or tab after '//' in comment. [Error/spaced-comment]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +        //not supported
[W7903(javascript-lint), ] Comments should not begin with a lowercase character. [Error/capitalized-comments]
[W7903(javascript-lint), ] Expected space or tab after '//' in comment. [Error/spaced-comment]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +        init: function() {
[W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +            var w = new SharedWorker('/web_switch_company_warning/static/src/js/switch_company_warning_worker.js');
W7903(javascript-lint), ] Line 19 exceeds the maximum line length of 80. [Error/max-len]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +                if(msg.data.newCtx === self.generateSignature()) {
[W7903(javascript-lint), ] Expected space(s) after "if". [Error/keyword-spacing]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +        generateSignature: function() {
[W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +        }
[W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +        init: function(parent) {
[W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +            // Choose where to append depending on whether web_responsive is installed or not
[W7903(javascript-lint), ] Line 42 exceeds the maximum line length of 80. [Error/max-len]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning.js
> +        }
[W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning_worker.js
> +"use strict";
[W7903(javascript-lint), ] Use the function form of 'use strict'. [Error/strict]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning_worker.js
> +//Show a big banner in the top of the page if the company has been
[W7903(javascript-lint), ] Expected space or tab after '//' in comment. [Error/spaced-comment]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning_worker.js
> +//changed in another tab or window (in the same browser)
[W7903(javascript-lint), ] Expected space or tab after '//' in comment. [Error/spaced-comment]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning_worker.js
> +var con = [];
[W7903(javascript-lint), ] Implicit global variable, assign as global property instead. [Error/no-implicit-globals]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning_worker.js
> +var lastCtx = null;
[W7903(javascript-lint), ] Implicit global variable, assign as global property instead. [Error/no-implicit-globals]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning_worker.js
> +addEventListener("connect", function(ee) {
[W7903(javascript-lint), ] Use the function form of 'use strict'. [Error/strict]
[W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]

2019-05-24 12:30 UTC, tbaden commented on web_switch_company_warning/static/src/js/switch_company_warning_worker.js
> +                eport.postMessage({type: "newCtx", "newCtx": newCtx, "lastCtx": lastCtx});
[W7903(javascript-lint), ] Line 17 exceeds the maximum line length of 80. [Error/max-len]

2019-06-06 09:43 UTC, LoisRForgeFlow approved these changes
Tested on EE version, :+1:

2019-06-11 08:13 UTC, lreficent commented
@tbaden all your comments were attended, could you please update your review?

@pedrobaeza are you ok with the renaming done here?

2019-06-11 08:15 UTC, pedrobaeza commented
Not sure if `context` is the best word. Maybe `environment`? But I don't have a strong opinion here, so proceed in the best way for you.

2019-06-14 13:18 UTC, tarteo approved these changes

2019-06-14 13:23 UTC, merged