11.0 mig web ir actions act window none
OCA/web pull request #1297
Opened 2019-05-31 12:11 UTC by daramousk

2019-06-26 23:44 UTC, Tardo requested changes

2019-06-26 23:44 UTC, Tardo commented on web_ir_actions_act_window_none/static/src/js/web_ir_actions_act_window_none.js
> +            }
return a resolved promise... ```$.when()```

2019-09-17 04:18 UTC, nikul-serpentcs reviewed
Nitpicking

2019-09-17 04:18 UTC, nikul-serpentcs commented on web_ir_actions_act_window_none/__manifest__.py
> +    "category": "Hidden/Dependency",
@daramousk Adding `website`

2023-07-02 12:33 UTC, closed without merging