[FIX] web_tree_many2one_clickable: reference field support
OCA/web pull request #1339
Opened 2019-07-24 13:18 UTC by thomaspaulb

Although support for Reference fields was mentioned in the README for this module, it didn't actually work. This fix makes it work.

2019-07-26 15:20 UTC, daramousk approved these changes
Thanks for this, works great and the failures on `web_widget_slick` seem to not be relevant to this change, I did run them locally, but we'll see what the rest of the members think.

2019-07-30 12:08 UTC, Tardo requested changes

2019-07-30 12:08 UTC, Tardo commented on web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
> +                let value = row_data[this.id].value;
Please, don't use ES6.

2019-07-30 12:08 UTC, Tardo commented on web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
> +                if (!!row_data[this.id + '__display']) {
Here perhaps can use a more readable syntax:
```suggestion
                if (_.has(row_data, this.id + '__display')) {
```

2019-07-30 12:08 UTC, Tardo commented on web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
> +        if ((this.type == 'many2one' || this.type == 'reference') &&
```suggestion
        if ((this.type === 'many2one' || this.type === 'reference') &&
```

2019-07-30 12:08 UTC, Tardo commented on web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
>              (this.widget == 'many2one_unclickable' || this.use_many2one_clickable) &&
```suggestion
            (this.widget === 'many2one_unclickable' || this.use_many2one_clickable) &&
```

2019-07-30 12:08 UTC, Tardo commented on web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
>              if (this.widget == 'many2one_unclickable') {
```suggestion
            if (this.widget === 'many2one_unclickable') {
```

2019-07-30 12:08 UTC, Tardo commented on web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
> +                if(this.type == 'reference') {
```suggestion
                if(this.type === 'reference') {
```

2019-07-30 12:09 UTC, pedrobaeza commented on web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
> +                let value = row_data[this.id].value;
Is there any possibility of detecting this via linter? So that we get a red status if so.

2019-08-21 13:36 UTC, thomaspaulb commented
@Tardo I think we fixed all?

2023-08-06 12:27 UTC, closed without merging