13.0 mig web m2x options
OCA/web pull request #1392
Opened 2019-10-02 13:06 UTC by jeroen7s

Mostly rewriting calls to use promises.
Feedback welcome.

2019-10-30 21:08 UTC, daramousk reviewed
Hi there, thanks for the migration.

Just run some functional tests and it seems to be working great, one of the things I saw is that some of the options that are being handled by this module have already been included on the base widget, I found some of those options but perhaps there are more..

Also, if there is time this could probably be a great opportunity for some qunit integration tests on this.

2019-10-30 21:08 UTC, daramousk commented on web_m2x_options/README.rst
> +Usage
It seems that some of this stuff now exists on v13, see them here,
I have outlined on comments below the ones that exist.
https://github.com/odoo/odoo/blob/13.0/addons/web/static/src/js/fields/relational_fields.js#L127

2019-10-30 21:08 UTC, daramousk commented on web_m2x_options/README.rst
> +``create`` *boolean* (Default: depends if user have create rights)
https://github.com/odoo/odoo/blob/13.0/addons/web/static/src/js/fields/relational_fields.js#L127

2019-10-30 21:08 UTC, daramousk commented on web_m2x_options/README.rst
> +``create_edit`` *boolean* (Default: depends if user have create rights)
https://github.com/odoo/odoo/blob/13.0/addons/web/static/src/js/fields/relational_fields.js#L129

2020-01-23 16:49 UTC, andrp92 commented
Hello @jeroen7s , Thanks for the migration. 

Have you get change to look up at @daramousk commnets? I would be great if we could have this merged.

2020-01-23 18:35 UTC, jeroen7s commented
To be honest, i'm not really much of a js developer, I just needed this module and wanted to make it work. So the functionality of the module should work fine. But adding Javascript unit tests and figuring out what functionality could be removed is not something I feel comfortable doing. 
Feel free to improve upon it and make an updated PR.

2020-01-24 20:54 UTC, andrp92 commented
Hey daramousk, seems like your requirement is out of @jeroen7s scope. Is there anyone at OCA that would be able to help us out with this one?

Thanks .!

2020-01-31 22:58 UTC, andrp92 commented
Hello, anyone can take a look at this? 

cc: @pedrobaeza @daramousk @Yajo @nikul-serpentcs @jcdrubay @ernestotejeda

2020-02-01 01:52 UTC, jcdrubay commented
@daramousk One of the main benefit of this module is to enable such field configuration at application level with the ir.config.parameter. Odoo only offers this at field level.

In several cases, we have disabled at project level the option `create` which is often the source of a lot of duplicate data.

2020-02-07 13:30 UTC, andrp92 commented
@pedrobaeza @daramousk any update on this one?

2020-02-19 10:33 UTC, yajo requested changes
I see you use a lot of rpc calls. Is it possible to restrict this to 0 or 1 per session? To avoid hitting performance.

2020-02-19 10:33 UTC, Yajo commented on web_m2x_options/readme/CONTRIBUTORS.rst
> +* Ernesto Tejeda <ernesto.tejeda87@gmail.com>
This was indented because all these contributors belong to Tecnativa. Please leave it as it was.

2020-02-19 10:33 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
>              var self = this;
It's v13, we have arrow functions!

```suggestion
```

2020-02-19 10:33 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +            var def = new Promise(function (resolve) {
```suggestion
            var def = new Promise(resolve => {
```

2020-02-19 10:33 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                    self.limit = parseInt(self.ir_options['web_m2x_options.limit'], 10);
```suggestion
                    this.limit = parseInt(self.ir_options['web_m2x_options.limit'], 10);
```

The same for all other `self`s

2020-02-19 10:33 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                }).then(function (result) {
```suggestion
                }).then(result => {
```

2020-02-19 10:33 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                    var values = _.map(result, function (x) {
```suggestion
                    var values = _.map(result, x => {
```

2020-02-19 10:33 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                        }).then(function (objects) {
```suggestion
                        }).then(objects => {
```

2020-02-24 01:09 UTC, pedrobaeza commented
Superseded by #1530

2020-02-24 01:09 UTC, closed without merging