[12.0][MIG] web_listview_invert_selection
OCA/web pull request #1412
Opened 2019-10-17 13:16 UTC by Martronic-SA

pin version,
changed less to scss

2019-10-18 13:50 UTC, tarteo requested changes

2019-10-18 13:50 UTC, tarteo commented on web_listview_invert_selection/static/src/js/web_listview_invert_selection.js
> +            var checked = self.$("tbody .o_list_record_selector input:checked");
`self` doesn't seem to be defined. Is it still needed? The functionality works in runbot :confused:

2019-10-21 11:14 UTC, daramousk approved these changes
Some comments

2019-10-21 11:14 UTC, daramousk commented on web_listview_invert_selection/__manifest__.py
> +# -*- coding: utf-8 -*-
Remove encoding statements from all the `*.py ` files.

2021-08-27 08:20 UTC, Martronic-SA commented
What is the status here? (@espo-tony )

2023-10-22 12:28 UTC, closed without merging