[13.0] ADD web chatt filtering functionality
OCA/web pull request #1415
Opened 2019-10-18 13:39 UTC by pegonzalezspesol

After working with Odoo a long time and load lot of loaded data, the amount of messages displayed inside the chatter of a record start to be significantly big

This module introduces a filter in the Chatter and next functionalities are provided:

Filter messages by content
Filter messages by author
Reverse filtering on author
F.ex. <-admin> will show all the messages in the chatt excluding the ones of the Administrator

2019-10-18 14:00 UTC, tarteo requested changes
Cool module!
I have some small remarks:
* When I search and there's 0 messages found it shows every message. Can you make it so something like "No messages found" appears.

2019-10-18 14:00 UTC, tarteo commented on web_chatt_filtering/__init__.py
> +##############################################################################
Please use a smaller copyright flag. https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py

2019-10-18 14:00 UTC, tarteo commented on web_chatt_filtering/__manifest__.py
> +    "website": "http://github.com/OCA/web",
https, please.

2019-10-18 14:00 UTC, tarteo commented on web_chatt_filtering/static/src/js/chatter.js
> +        filter_message: function (substring) {
Can you refactor this function so it's easier inheritable. E.g. put the rpc call inside a separate function.

2019-10-22 12:22 UTC, tarteo reviewed
The no messages found is now put into the search input box. Is this as intended? Now it seems there are conflicts can you fix those, please.

2019-10-25 10:31 UTC, tarteo approved these changes
Thanks!

2019-10-25 10:31 UTC, tarteo approved these changes
Thanks!

2019-10-25 12:37 UTC, pegonzalezspesol commented
> Thanks!

Thanks for your revision Dennis! @tarteo

2019-10-26 12:43 UTC, pegonzalezspesol commented
@hbrunn, @daramousk can any of you please review this PR?

2019-11-13 05:08 UTC, pegonzalezspesol commented
@angelmoya could you please review?

2021-11-29 14:39 UTC, dreispt commented
/ocabot merge nobump

2022-06-23 10:42 UTC, tarteo commented
/ocabot merge nobump

2023-10-22 12:28 UTC, closed without merging