13.0 mig web widget color
OCA/web pull request #1416
Opened 2019-10-21 15:17 UTC by ammarofficewla

2019-10-22 13:57 UTC, sudhir-erpharbor commented on web_widget_color/README.rst
> +* Ammar Offciewala <https://twitter.com/AmmarOfficewala>
It must be your email address.

2019-10-22 13:57 UTC, sudhir-erpharbor commented on web_widget_color/README.rst
> +This module is part of the `OCA/web <https://github.com/OCA/web/tree/12.0/web_widget_color>`_ project on GitHub.
13.0

2019-10-23 15:31 UTC, sudhir-erpharbor approved these changes
LGTM

2019-10-23 20:51 UTC, pedrobaeza requested changes
Please add to `view_base_document_layout` the widget in `primary_color` and `secondary_color` for both showcasing the widget and for improving that functionality, but making sure the output format is the expected one (I think so).

2019-10-24 03:21 UTC, ammarofficewla commented
> Please add to `view_base_document_layout` the widget in `primary_color` and `secondary_color` for both showcasing the widget and for improving that functionality, but making sure the output format is the expected one (I think so).

Sorry, I have not understood your change request.

2019-10-24 08:32 UTC, pedrobaeza commented
Modify that view for adding the widget in the specified fields.

2020-01-11 10:27 UTC, sbidoul commented
Is this still necessary? There is a `color` widget in Odoo CE that seems to do the same.

2020-01-22 21:56 UTC, pedrobaeza commented
This one is definitively not needed, so closing and amending OpenUpgrade part in https://github.com/OCA/OpenUpgrade/pull/2170

2020-01-22 21:56 UTC, closed without merging