[13.0][MIG] web_widget_bokeh_chart
OCA/web pull request #1463
Opened 2019-12-17 15:01 UTC by AdriaGForgeFlow

Standard migration of module web_widget_bokeh_chart to v13.

cc ~ @ForgeFlow

2019-12-18 09:22 UTC, LoisRForgeFlow requested changes
See comments below. Plus, please change of copyrights to Forgeflow

2019-12-18 09:22 UTC, LoisRForgeFlow commented on web_widget_bokeh_chart/__manifest__.py
>      "maintainers": ["lreficent"],
Change to LoisRForgeFlow

2019-12-18 09:22 UTC, LoisRForgeFlow commented on web_widget_bokeh_chart/__manifest__.py
>      "author": "Eficent, "
Change to ForgeFlow

2019-12-20 11:05 UTC, LoisRForgeFlow approved these changes
:+1:

2019-12-20 11:07 UTC, JordiBForgeFlow approved these changes

2019-12-20 11:07 UTC, JordiBForgeFlow commented
/ocabot merge

2019-12-23 11:21 UTC, JordiBForgeFlow commented
/ocabot merge

2019-12-23 11:34 UTC, merged