[13.0][MIG] web_widget_image_download: Migration to 13.0
OCA/web pull request #1506
Opened 2020-01-28 11:55 UTC by Tardo

cc @tecnativa TT19836

2020-01-30 15:36 UTC, pedrobaeza requested changes
Please split migration commit from black one

2020-01-30 16:51 UTC, Tardo commented
Done

2020-01-30 20:10 UTC, ernestotejeda approved these changes

2020-02-06 18:40 UTC, pedrobaeza approved these changes

2020-02-06 18:41 UTC, pedrobaeza commented
/ocabot merge

2020-02-06 19:02 UTC, merged