[13.0][MIG] web_widget_url_advanced
OCA/web pull request #1541
Opened 2020-03-02 13:54 UTC by JoanSForgeFlow

**web_widget_url_advanced** migration to v13.

cc ~ @LoisRForgeFlow

2020-03-02 15:24 UTC, LoisRForgeFlow approved these changes
LGTM!

2020-03-02 16:20 UTC, simahawk commented
would you mind considering https://github.com/OCA/web/pull/1234#issuecomment-511708931 to merge web_widget_prefixed_url into this?

2020-03-03 11:59 UTC, JoanSForgeFlow commented
@simahawk Of course, it's already done. Would you mind to review?

2020-03-04 07:03 UTC, simahawk requested changes

2020-03-04 07:03 UTC, simahawk commented on web_widget_url_advanced/static/src/js/url_widget.js
> +                var prefix = this.attrs.prefix_name || this.attrs.options.prefix_name;
I don't think this is correct/enough.
The `prefix_name` - as the word says - should be used to add a prefix to the link, such as `mailto:`.
Please check here how it's done https://github.com/OCA/web/blob/11.0/web_widget_prefixed_url/static/src/js/widget_prefixed_url.js#L20

2020-03-04 07:03 UTC, simahawk commented on web_widget_url_advanced/templates/assets.xml
> +<odoo>
can you rebase on 13.0 and run pre-commit? There's a fix for bad xml formatting.

2020-03-04 07:03 UTC, simahawk commented on web_widget_url_advanced/readme/DESCRIPTION.rst
> +With this module, you can use a field for link's inner text using attribute
this must be fixed according to `prefix_name` correct behavior.

2020-03-06 09:23 UTC, JoanSForgeFlow commented
Sorry, I had misunderstood the module's functionality. Now, the `prefix_name` adds a prefix to the link.
Thanks for your review.

2020-03-09 07:25 UTC, simahawk approved these changes

2020-03-09 07:25 UTC, simahawk commented
/ocabot merge minor

2020-03-09 07:36 UTC, merged