[FIX] web_widget_numeric_step: Fix _onChange input fields methods disabled by the widget
OCA/web pull request #1543
Opened 2020-03-04 00:19 UTC by sergio-teruel

cc @Tecnativa
ping @Tardo @pedrobaeza

2020-03-04 05:33 UTC, legalsylvain approved these changes
Thanks. Lgtm. No test.

2020-03-04 07:03 UTC, pedrobaeza approved these changes

2020-03-04 07:59 UTC, pedrobaeza commented
I'm now fearing that people click several times very quickly on the buttons + and -, and this triggers for each click an onchange. Can we set a reasonable time capture window for not launching the onchange until passed? I know this is done on website for the number of items in the cart before processing the update.

2020-03-04 08:35 UTC, Yajo commented
That should be done in the widget itself IMHO.

2020-03-04 08:37 UTC, Yajo commented
Yes, you can do that with a deferred/promise (I don't remember which one is preferred for v12) and a timeout.

2020-03-04 12:40 UTC, Tardo commented
Ummm i see the problem here... my initial intention wasn't overwrite '_onChange' method, i did it as a totally new one.
Now with these changes we have two 'change' (InputField + NumericStep) event calling the same method.

Please, remove the 'change' event declared by 'InputField' class... and the 'input' event need by changed too to listen the '.input_numeric_step' element (that is the real 'input' element).
In the NumericStep widget the $el var. is related to the group of input+buttons not only for the input.

A solution to not 'flood' the change event can be use: https://underscorejs.org/#throttle

2020-03-04 12:42 UTC, pedrobaeza commented
@Tardo, what about the suggestion of @Yajo's about deferred/promise with a timeout? Can you take over this as you are more experienced with JS?

2020-03-04 19:14 UTC, Tardo commented
Updated with some changes... finally i prefer use macrotask (setTimeout) instead of microtask (Promises) because in this case we don't need be "fast as possible". Underscore offers us 'dobounce' that for me is exactly that we need in this case.

2020-03-05 08:35 UTC, yajo requested changes
Looks neat! Minor details.

2020-03-05 08:35 UTC, Yajo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +        //
:wastebasket:

2020-03-05 08:35 UTC, Yajo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            this._super.apply(this, arguments);
Possibly not strictly needed, but this is the common pattern:

```suggestion
            return this._super.apply(this, arguments);
```

2020-03-05 15:43 UTC, Tardo commented
Changes done!

2020-03-06 12:08 UTC, yajo approved these changes

2020-03-06 12:09 UTC, Yajo commented
/ocamod merge minor

2020-03-06 12:09 UTC, pedrobaeza commented
/ocabot merge patch

2020-03-06 12:19 UTC, merged