[12.0][ADD] web_widget_daterange : this module adds widget daterange
OCA/web pull request #1614
Opened 2020-06-04 21:23 UTC by AyoubZahid

This widget allow user to select start and end date from a single picker .
( this is a backport from odoo 13.0)

2020-06-11 10:12 UTC, etobella requested changes
Can you add a readme on  the module?
I tried to make it work with `hr.holidays` and an error is raised. Can you check?
`ValueError: Wrong value for hr.leave.request_date_from_period: '2020-06-11T10:10:00.000Z'`

2020-06-11 10:12 UTC, etobella commented on web_widget_daterange/static/src/js/widget.js
> +});
New line

2020-06-11 10:12 UTC, etobella commented on web_widget_daterange/views/assets.xml
> +</odoo>
New line

2020-06-12 10:47 UTC, AyoubZahid commented
> Can you add a readme on the module?

Done 👍

2024-03-03 12:27 UTC, closed without merging