Update README.rst
OCA/web pull request #1633
Opened 2020-07-09 14:56 UTC by KENLYLST

Unresolved reference `self` and module `odoo.api` has no attribute `multi`

2020-07-09 17:28 UTC, legalsylvain approved these changes

2020-07-10 05:40 UTC, simahawk requested changes
@KENLYLST thanks for your contrib!

This change will be overridden because the README is computed w/ readme fragments.
It must be fixed here https://github.com/OCA/web/blob/e4004cccac2e10637527405eded7ba1eb4c8b3ef/web_ir_actions_act_view_reload/readme/USAGE.rst

Also, please, include module name in commit and PR title, thanks! :pray:

2020-07-12 19:51 UTC, KENLYLST reviewed
I have fixed https://github.com/OCA/web/blob/e4004cccac2e10637527405eded7ba1eb4c8b3ef/web_ir_actions_act_view_reload/readme/USAGE.rst.

2020-07-13 05:54 UTC, simahawk approved these changes

2020-07-13 05:54 UTC, merged