[13.0] [MIG] web_widget_domain_editor_dialog: Migration to v13.0
OCA/web pull request #1698
Opened 2020-10-08 13:20 UTC by CarlosRoca13

cc @Tecnativa TT25342

This module adds the posibility to generate the domain from the dialog how we see on next image.

![1](https://user-images.githubusercontent.com/35952655/95463895-9fb40500-0979-11eb-96ed-06ab36c3544e.gif)

Please @chienandalu @Yajo con you review this?

2020-10-08 14:22 UTC, chienandalu requested changes

2020-10-08 14:22 UTC, chienandalu commented on .vscode/settings.json
> +}
check your gitignore settings ;)

2020-10-08 14:22 UTC, chienandalu commented on web_widget_domain_editor_dialog/static/src/js/basic_fields.js
> +            const self = this;
Actually `_this` was more apropiate: https://developer.mozilla.org/en-US/docs/Web/API/Window/self

2020-10-08 14:22 UTC, chienandalu commented on web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.js
> +                        domain: JSON.parse(self.options.default_domain),
This is failing

2020-10-09 06:39 UTC, CarlosRoca13 commented
@chienandalu All changes done!

2020-12-01 11:29 UTC, Yajo approved these changes

2020-12-01 11:30 UTC, chienandalu approved these changes

2020-12-01 11:32 UTC, Yajo commented
/ocabot merge nobump

2020-12-01 11:45 UTC, merged