[13.0] [MIG] web_editor_background_color: Migration to v13.0
OCA/web pull request #1725
Opened 2020-11-05 12:24 UTC by CarlosRoca13

cc @Tecnativa TT25341

Here you have an example how it works
![1](https://user-images.githubusercontent.com/35952655/98240459-bb56ff00-1f69-11eb-8e71-ee4aa1533f67.gif)

Please @Yajo @Tardo can you review this

2020-11-17 16:17 UTC, victoralmau requested changes
Good job!! Some little changes.

2020-11-17 16:17 UTC, victoralmau commented on web_editor_background_color/__manifest__.py
> +# Copyright 2017 Jairo Llopis <jairo.llopis@tecnativa.com>
```suggestion
# Copyright 2017 Tecnativa -  Jairo Llopis
```

2020-11-17 16:17 UTC, victoralmau commented on web_editor_background_color/i18n/ca.po
> +#~ msgstr "Color"
```suggestion
```

2020-11-17 16:17 UTC, victoralmau commented on web_editor_background_color/i18n/es.po
> +#~ msgstr "Escoger el color de fondo"
```suggestion
```

2020-11-17 16:17 UTC, victoralmau commented on web_editor_background_color/i18n/fr.po
> +#~ msgstr "Mettre la couleur de fond"
```suggestion
```

2020-11-17 16:17 UTC, victoralmau commented on web_editor_background_color/i18n/sl.po
> +#~ msgstr "Izbira barve ozadja"
```suggestion
```

2020-11-17 16:17 UTC, victoralmau commented on web_editor_background_color/static/src/css/background_color.scss
> +/* Copyright 2017-2019 Jairo Llopis <jairo.llopis@tecnativa.com>
```suggestion
/* Copyright 2017-2019 Tecnativa - Jairo Llopis
```

2020-11-17 16:17 UTC, victoralmau commented on web_editor_background_color/static/src/js/background_color.js
> +/* Copyright 2016-2019 Jairo Llopis <jairo.llopis@tecnativa.com>
```suggestion
/* Copyright 2016-2019 Tecnativa - Jairo Llopis
```

2020-11-17 16:17 UTC, victoralmau commented on web_editor_background_color/templates/assets.xml
> +<!-- Copyright 2017-2019 Jairo Llopis <jairo.llopis@tecnativa.com>
```suggestion
<!-- Copyright 2017-2019 Tecnativa - Jairo Llopis
```

2020-11-18 07:30 UTC, CarlosRoca13 commented
@victoralmau changes done!

2020-11-18 07:35 UTC, victoralmau approved these changes

2020-11-18 09:29 UTC, pedrobaeza requested changes
It doesn't work for mass mailings:

![Peek 18-11-2020 10-29](https://user-images.githubusercontent.com/7165771/99511774-fbb27600-2988-11eb-9e44-948e3418f2aa.gif)

2020-11-18 10:30 UTC, CarlosRoca13 commented
@pedrobaeza Problem solved!

2020-11-18 11:08 UTC, pedrobaeza commented
It's still not working correctly. It doesn't work until you select first time another color, and then the custom color is applied, but if you try to set the custom color directly, it's not set.

2020-11-18 15:30 UTC, CarlosRoca13 commented
![1](https://user-images.githubusercontent.com/35952655/99550455-084fc200-29bb-11eb-9586-42f01204ef62.gif)
I don't see what you say... It could be that you haven't changed the opacity? The example that I paste is from runbot

2020-11-18 15:42 UTC, pedrobaeza commented
Yeah, that can definitively be, but then the next question is: why it appears with opacity = 0 by default? Is it the same in previous versions?

2020-11-18 15:56 UTC, CarlosRoca13 commented
Yes, in v12 works like here

2020-11-19 08:26 UTC, pedrobaeza approved these changes

2020-11-19 08:27 UTC, pedrobaeza commented
/ocabot merge nobump

2020-11-19 08:52 UTC, merged