[12.0][IMP]Add native notifications via desktop
OCA/web pull request #1727
Opened 2020-11-08 22:29 UTC by flotho

Also fix https://github.com/OCA/web/issues/723

2020-11-08 22:30 UTC, flotho commented
Hi @hbrunn , I would appreciate a review here.

2021-03-07 18:24 UTC, hbrunn requested changes
nice feature. Is it true that in v14 we get this for free?

2021-03-07 18:24 UTC, hbrunn commented on web_notify/static/src/js/web_client.js
> +        	if(message.allow_native_notifications){
I miss a call to https://developer.mozilla.org/en-US/docs/Web/API/Notification/permission here

2021-03-07 18:24 UTC, hbrunn commented on web_notify/models/res_users.py
> +            "allow_native_notifications": self.allow_native_notifications,
this makes all the comparisons in tests fail. You need to adapt https://github.com/OCA/web/blob/f56f71155f23ce07bad57b3a7f9d812412ff5e3a/web_notify/tests/test_res_users.py#L24 and below

2021-03-07 18:24 UTC, hbrunn commented on web_notify/static/src/js/services/notification_service.js
> +		notify: function (params) {
please explain this override

2021-03-07 18:24 UTC, hbrunn commented on web_notify/models/res_users.py
> +    allow_native_notifications = fields.Boolean(
I'm not sure if we need this at all - either the user has allowed desktop notifications, then I think we should use them too, or they didn't, and then we don't need this flag

2021-04-17 20:10 UTC, flotho commented
> nice feature. Is it true that in v14 we get this for free?

don't really know, I'll test it soon.

2021-04-17 20:28 UTC, pedrobaeza commented
Since v13, installing mail_bot, it ask you for that and you have it indeed "for free".

2021-04-17 20:43 UTC, flotho commented
maybe I should better check how it has been done in v13 and backport this.

2024-05-19 16:53 UTC, closed without merging