[12.0][IMP] web_m2x_options: Added limit for o2m field entries + efficiency
OCA/web pull request #1728
Opened 2020-11-09 09:38 UTC by CarlosRoca13

Added the system parameter "web_m2x_options.field_limit_entries" to set the limit of entries that can be displayed on One2many fields.

Improved the eficiency of code: With this improvement we achieve to just do an rpc call when the js file is called instead of do the call for each field.

Here you have an example:
![1](https://user-images.githubusercontent.com/35952655/98524456-87d0e900-2277-11eb-8977-b2ff88493255.gif)

Please @chienandalu @ernestotejeda can you review this

2020-11-09 10:39 UTC, pedrobaeza requested changes
The improvement for reading only one time should be split in a different commit from the new feature for limiting the number of entries in the one2many.

2020-11-09 10:39 UTC, pedrobaeza commented on web_m2x_options/README.rst
> +``web_m2x_options.field_limit_entries`` *int* (Default: odoo default value is ``40``)
There shouldn't be a default value, as if not defined, the limit is set by Odoo itself in their core, so IMO you shouldn't change that default value if not defined.

2020-11-09 10:50 UTC, CarlosRoca13 commented
@pedrobaeza Changes done

2020-11-09 10:52 UTC, pedrobaeza commented on web_m2x_options/readme/USAGE.rst
> +``web_m2x_options.field_limit_entries`` *int* (Default: odoo default value is ``40``)
This change is still in the wrong commit

2020-11-09 11:04 UTC, CarlosRoca13 commented
Sorry, changed yet @pedrobaeza

2020-11-09 11:46 UTC, pedrobaeza approved these changes

2020-11-16 07:23 UTC, joao-p-marques approved these changes
LGTM :+1:

2020-11-16 08:09 UTC, pedrobaeza commented
/ocabot merge major

2020-11-16 08:24 UTC, merged