[13.0][MIG] web_pivot_computed_measure: Migration to 13.0
OCA/web pull request #1746
Opened 2020-11-26 06:02 UTC by ernestotejeda

cc @Tecnativa TT25958

Main changes:
- Adapt the javascript code to the new data structure used to manage the data to be displayed in the pivot view.

2020-11-26 12:08 UTC, pedrobaeza approved these changes
Tested functionally on runbot and working. Maybe you can put in the same line the label and the dropdowns for saving vertical space.

2020-11-26 19:05 UTC, Tardo requested changes
Please, update source to use ES6 :) 

And take a look at this PR: https://github.com/OCA/web/pull/1700 maybe need be fixed on 13.0 too

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +    var QWeb = core.qweb;
```suggestion
    const core = require("web.core");
    const config = require("web.config");
    const PivotController = require("web.PivotController");

    const QWeb = core.qweb;
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +                });
```suggestion
                return Promise.resolve();
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            });
```suggestion
            return Promise.resolve();
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +            var state = this.model.get({raw: true});
```suggestion
            const res = this._super.apply(this, arguments);
            const state = this.model.get({raw: true});
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +            var $target = $(event.target);
```suggestion
            const $target = $(event.target);
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                var hideMenu = false;
```suggestion
                let hideMenu = false;
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                    var field1 = this.$buttons_measures_ex
```suggestion
                    const field1 = this.$buttons_measures_ex
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                    var field2 = this.$buttons_measures_ex
```suggestion
                    const field2 = this.$buttons_measures_ex
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                    var oper = this.$buttons_measures_ex
```suggestion
                    let oper = this.$buttons_measures_ex
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                    var name = this.$buttons_measures_ex
```suggestion
                    const name = this.$buttons_measures_ex
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                    var format = this.$buttons_measures_ex
```suggestion
                    const format = this.$buttons_measures_ex
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                    var uniqueId = new Date().getTime();
```suggestion
                    const uniqueId = new Date().getTime();
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +         * Render computed measures menu
```suggestion
         * Render computed measures menu
         *
         * @private
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +            var measures = _.sortBy(_.pairs(_.omit(this.measures, "__count")), function(
```suggestion
            const self = this;
            const measures = _.sortBy(_.pairs(_.omit(this.measures, "__count")), function(
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +         * @param {CustomEvent} ev
```suggestion
         * @private
         * @param {CustomEvent} ev
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +         * @param {CustomEvent} ev
```suggestion
         * @private
         * @param {CustomEvent} ev
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +         * @param {ChangeEvent} ev
```suggestion
         * @private
         * @param {ChangeEvent} ev
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +            var $option = $(ev.target.options[ev.target.selectedIndex]);
```suggestion
            const $option = $(ev.target.options[ev.target.selectedIndex]);
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                var format = $option.data("format");
```suggestion
                const format = $option.data("format");
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +    var _t = core._t;
```suggestion
    const core = require("web.core");
    const PivotModel = require("web.PivotModel");

    const _t = core._t;
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var measure = _.find(this._computed_measures, function(item) {
```suggestion
            const measure = _.find(this._computed_measures, function(item) {
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var oper_human = operation
```suggestion
            const fieldM1 = this.fields[field1];
            const fieldM2 = this.fields[field2];
            const cmId = "__computed_" + id;
            const oper = operation.replace(/m1/g, field1).replace(/m2/g, field2);
            const oper_human = operation
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var cmTotal = this._computed_measures.push({
```suggestion
            const cmTotal = this._computed_measures.push({
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +         * @param {Object} cmDef
```suggestion
         * @private
         * @param {Object} cmDef
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var arrFields = fields || this.fields;
```suggestion
            const arrFields = fields || this.fields;
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +         * @param {List of Strings} fields
```suggestion
         * @private
         * @param {List of Strings} fields
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var needLoad = false;
```suggestion
            let needLoad = false;
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            }
```suggestion
            for (const field of fields) {
                if (!this._isMeasureEnabled(field)) {
                    this.data.measures.push(field);
                    needLoad = true;
                }
            }
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +         * @param {String} field
```suggestion
         * @private
         * @param {String} field
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +         * @param {Object} subGroupData
```suggestion
         * @private
         * @param {Object} subGroupData
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var self = this;
```suggestion
            const self = this;
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            }
```suggestion
            for (const groupSubdivision of groupSubdivisions) {
                for (const subGroup of groupSubdivision.subGroups) {
                    this._fillComputedMeasuresData(subGroup);
                }
            }
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var computed_measures = [];
```suggestion
            const computed_measures = [];
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var res = this._super.apply(this, arguments);
```suggestion
            const res = this._super.apply(this, arguments);
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var self = this;
```suggestion
            const self = this;
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            }
```suggestion
            const toActive = [];
            for (const cmDef of this._computed_measures) {
                params.fields[cmDef.id] = {
                    type: cmDef.format,
                    string: cmDef.name,
                    __computed_id: cmDef.id,
                };
                toActive.push(cmDef.field1, cmDef.field2, cmDef.id);
            }
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +                    }
```suggestion
                    for (const cmDef of this._computed_measures) {
                        self.trigger_up("add_measure", {
                            id: cmDef.id,
                            def: self.fields[cmDef.id],
                        });
                    }
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            }
```suggestion
            for (const cmDef of this._computed_measures) {
                this._createVirtualMeasure(cmDef);
            }
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            }
```suggestion
            const fieldNames = Object.keys(this.fields);
            for (const fieldName of fieldNames) {
                const field = this.fields[fieldName];
                if (field.__computed_id) {
                    const cm = _.find(this._computed_measures, {id: field.__computed_id});
                    if (!cm) {
                        delete this.fields[fieldName];
                        this.data.measures = _.without(
                            this.data.measures,
                            fieldName
                        );
                        this.trigger_up("remove_measure", {
                            id: fieldName,
                        });
                    }
                }
            }
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            var res = this._super.apply(this, arguments);
```suggestion
            const res = this._super.apply(this, arguments);
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +                    });
```suggestion
                    return Promise.reject(
                        _t(
                            "This measure is currently used by a 'computed measure'. Please, disable the computed measure first."
                        )
                    );
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +                var toAnalize = [field];
```suggestion
                const toEnable = [];
                const toAnalize = [field];
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +                    var fieldDef = this.fields[afield];
```suggestion
                    const afield = toAnalize.shift();
                    const fieldDef = this.fields[afield];
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +                        var cm = _.find(this._computed_measures, {
```suggestion
                        const cm = _.find(this._computed_measures, {
```

2020-11-26 19:05 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +                        var toEnableFields = [];
```suggestion
                        const toEnableFields = [];
```

2020-11-27 18:28 UTC, ernestotejeda commented
@Tardo changes done. I applied the changes you proposed and I added https://github.com/OCA/web/pull/1700 fix in this migration because it is also needed in v13

2020-11-27 19:58 UTC, Tardo requested changes
Thanks! I see more changes to be made:
- Review 'let' usage instead of 'var'.
- Use arrow functions when possible... arrow functions do not have their own "this" value, so we can avoid 'self' usage.

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            });
```suggestion
            for (const cm of this._computed_measures) {
                if (!this._isMeasureEnabled(cm.id)) return;
                if (subGroupData.__count === 0) {
                    subGroupData[cm.id] = false;
                } else {
                    // eslint-disable-next-line no-undef
                    subGroupData[cm.id] = py.eval(cm.operation, subGroupData);
                }
            }
```

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                function(x) {
```suggestion
                (x) => {
```

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                        function(item) {
```suggestion
                        (item) => {
```

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +                                self.model.data.measures,
```suggestion
                                this.model.data.measures,
```

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_controller.js
> +            const self = this;
```suggestion
```

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            const measure = _.find(this._computed_measures, function(item) {
```suggestion
            const measure = _.find(this._computed_measures, (item) => {
```

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            const self = this;
```suggestion
```

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +            });
```suggestion
            return this._super(params).then(() => {
                _.defer(() => {
                    for (const cmDef of this._computed_measures) {
                        this.trigger_up("add_measure", {
                            id: cmDef.id,
                            def: this.fields[cmDef.id],
                        });
                    }
                });
                this._activeMeasures(toActive);
            });
```

2020-11-27 19:58 UTC, Tardo commented on web_pivot_computed_measure/static/src/js/pivot_model.js
> +                var umeasures = _.filter(this._computed_measures, function(item) {
```suggestion
                var umeasures = _.filter(this._computed_measures, (item) => {
```

2020-11-30 17:35 UTC, ernestotejeda commented
@Tardo Changes done

2020-12-01 19:38 UTC, Tardo approved these changes
:+1: Good! Thanks

2020-12-01 19:39 UTC, pedrobaeza commented
/ocabot merge nobump

2020-12-01 19:52 UTC, merged