[13.0] [MIG] web_widget_numeric_step: Migration to v13
OCA/web pull request #1790
Opened 2021-01-25 08:33 UTC by CarlosRoca13

cc @Tecnativa TT27480

please @Tardo @sergio-teruel review this.

2021-01-27 17:06 UTC, Tardo requested changes

2021-01-27 17:06 UTC, Tardo commented on .vscode/settings.json
> +}
:fire: this file

2021-01-28 07:06 UTC, CarlosRoca13 commented
@Tardo changes done

2021-01-28 13:36 UTC, Tardo requested changes
Try update js to use ES6 :)

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +    var FieldFloat = require("web.basic_fields").FieldFloat;
```suggestion
    const field_utils = require("web.field_utils");
    const Registry = require("web.field_registry");
    const FieldFloat = require("web.basic_fields").FieldFloat;
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +    var NumericStep = FieldFloat.extend({
```suggestion
    const NumericStep = FieldFloat.extend({
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            var min_val = this.nodeOptions.min;
```suggestion
            let max_val = this.nodeOptions.max;
            let min_val = this.nodeOptions.min;
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            }, this.DELAY_THROTTLE_CHANGE);
```suggestion
            this._lazyOnChangeTrigger = _.debounce(
                () => this.$input.trigger("change"),
                this.DELAY_THROTTLE_CHANGE);
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            });
```suggestion
            this._click_delay = this.DEF_CLICK_DELAY;
            this._autoStep = false;
            return this._super.apply(this, arguments).then(() => {
                document.addEventListener(
                    "mouseup",
                    this._onMouseUp,
                    false
                );
                document.addEventListener(
                    "touchend",
                    this._onMouseUp,
                    false
                );
            });
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            var parsedVal = this._super.apply(this, arguments);
```suggestion
            const parsedVal = this._super.apply(this, arguments);
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            var result = this._super.apply(this, arguments);
```suggestion
            const result = this._super.apply(this, arguments);
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            );
```suggestion
            _.defer(
                () => this.$el
                        .parents("td.o_numeric_step_cell")
                        .addClass("numeric_step_editing_cell")
            );
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            var cval = 0;
```suggestion
            let cval = 0;
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +                var field = this.record.fields[this.name];
```suggestion
                const field = this.record.fields[this.name];
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            var nval = this._sanitizeNumberValue(cval);
```suggestion
            const nval = this._sanitizeNumberValue(cval);
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +                var mode = ev.target.dataset.mode;
```suggestion
                const mode = ev.target.dataset.mode;
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +                );
```suggestion
                this._auto_step_interval = setTimeout(
                    this._whileMouseDown.bind(this, ev),
                    this._click_delay
                );
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            var mode = ev.target.dataset.mode;
```suggestion
            const mode = ev.target.dataset.mode;
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            var cval = Number(value);
```suggestion
            let cval = Number(value);
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            var field = this.record.fields[this.name];
```suggestion
            const field = this.record.fields[this.name];
```

2021-01-28 13:36 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +            return formattedValue;
```suggestion
            // formatted value
            return field_utils.format[field.type](cval, field, {
                data: this.record.data,
                escape: true,
                isPassword: false,
                digits: field.digits,
            });
```

2021-01-28 14:08 UTC, CarlosRoca13 commented
@Tardo changes done

2021-01-28 15:44 UTC, Tardo requested changes

2021-01-28 15:44 UTC, Tardo commented on web_widget_numeric_step/static/src/js/numeric_step.js
> +                document.addEventListener("touchend", this._onMouseUp, false);
```suggestion
                document.addEventListener("mouseup", this._onMouseUp.bind(this), false);
                document.addEventListener("touchend", this._onMouseUp.bind(this), false);
```

2021-01-28 15:49 UTC, CarlosRoca13 commented
@Tardo changed

2021-01-28 18:27 UTC, Tardo approved these changes
LGTM :+1: Thanks @CarlosRoca13

2021-01-28 18:49 UTC, pedrobaeza approved these changes

2021-01-28 18:49 UTC, pedrobaeza commented
/ocabot merge nobump

2021-01-28 18:56 UTC, lmignon commented
@pedrobaeza AFAIK it's important to bump the version when merging PR of migrated addon. Without bump the bot will not publish a new release of the addon, only a dev release...

2021-01-28 19:00 UTC, pedrobaeza commented
I don't like to have the initial version of a module as `13.0.1.0.1`. That requirement is very artificial, and due to all the overhead requires for the pip thing, that I don't share. If that's a problem for that part, I think the fix should come from the publishing method.

2021-01-28 19:18 UTC, merged