[14.0][mig] web drop target
OCA/web pull request #1794
Opened 2021-01-28 07:37 UTC by dsolanki-initos

2021-03-01 11:55 UTC, fshah-initos approved these changes

2021-03-02 04:59 UTC, dsolanki-initos commented
@jarroyomorales can you please review this PR?

2021-03-24 05:06 UTC, dsolanki-initos commented
@LoisRForgeFlow Will you please review this PR?
Thanks in advance!

2021-03-24 10:23 UTC, fuentes010 commented
Hi! Is this module necessary yet? In v14.0 by default you can drag&drop attachments 
This is a record from runbot.odoo.com
![drop](https://user-images.githubusercontent.com/4355395/112293872-e6c95480-8c92-11eb-8787-e4f084d06b56.gif)

2021-03-25 08:16 UTC, pedrobaeza commented
The idea of this module is to have the ability to drop objects in any place of the web client and react according that. It's for example used for dragging and dropping files in DMS. Said that, I don't know if this code is using core mechanism for that or implementing their owns.

2021-03-29 08:56 UTC, fuentes010 commented
Hi @pedrobaeza I know the idea of this module.
I don't know if it's an easy tasks but will be better deprecate this module and adapt DMS to use core mechanism?

OTOH, with this module installed you can see the message duplicate, is not a problem because the attachment is created only once
![captura-web-drop-target](https://user-images.githubusercontent.com/4355395/112811428-5c129c00-907c-11eb-80e1-f04706eb072f.png)

2021-03-29 08:59 UTC, pedrobaeza commented
If DMS can use drag & drop mechanism, indeed it would be better, but I don't know if a great amount of code is needed for that and a module like this one is still desirable for containing such amount of code. Maybe you draft something for using the core mechanism? :pray:

2021-03-30 15:18 UTC, victoralmau commented
According to mi tests that need it in https://github.com/OCA/dms/pull/66 work fine.

2021-03-30 15:18 UTC, victoralmau approved these changes

2021-03-30 15:22 UTC, pedrobaeza commented
I would remove that double entry in the UI, but I have also a doubt: it's supposed that the drag and drop feature for chatter is added in mail_drop_target, and this one doesn't depend on `mail`, so I don't know why this enables the other feature.

@etobella maybe you can help here.

2021-03-30 15:23 UTC, pedrobaeza commented on web_drop_target/static/src/js/web_drop_target.js
> +                var chatterContainerComponent = self.getChildren()[1]
I think this code is the offending one that is adding this double.

2021-04-06 09:26 UTC, victoralmau commented
IMO it's not ready yet because if i try to drop image in "attachments chatter" appear 2 attachments (duplicate).

2021-04-06 09:28 UTC, pedrobaeza commented
@victoralmau can you please check my comment about removing that code to see if it disappears? This module must not handle anything from `mail` module.

2021-04-06 10:27 UTC, victoralmau requested changes

2021-04-06 10:27 UTC, victoralmau commented on web_drop_target/static/src/js/web_drop_target.js
> +            });
```suggestion
            })
```

2021-04-06 10:27 UTC, victoralmau commented on web_drop_target/static/src/js/web_drop_target.js
> +            });
I have testing it locally and remove it to prevent duplicate attachment creation.

2021-04-06 10:35 UTC, pedrobaeza commented
@victoralmau I think you can supersede this, so we can merge it ASAP and don't block dependent modules.

2021-04-06 18:40 UTC, pedrobaeza commented
Superseded by #1892

2021-04-06 18:40 UTC, closed without merging