[13.0] mig web translate dialog
OCA/web pull request #1801
Opened 2021-02-03 05:20 UTC by fshah-initos

2021-03-01 12:17 UTC, dsolanki-initos approved these changes

2021-03-24 09:39 UTC, fshah-initos commented
@grindtildeath will you please review this PR?

2021-04-05 06:52 UTC, fshah-initos commented
@all Is it possible to add reviews here?

2021-04-06 06:00 UTC, simahawk requested changes

2021-04-06 06:00 UTC, simahawk commented on web_translate_dialog/__manifest__.py
> +    "depends": ["web", "product"],
product???

2021-04-06 06:00 UTC, simahawk commented on web_translate_dialog/tests/test_web_translate_dialog.py
> +        self.product = self.env["product.template"].create({"name": "English Name"})
you don't need this to add tests. Use another existing model from base (eg: res.partner.title)

2021-04-06 06:00 UTC, simahawk commented on web_translate_dialog/tests/test_web_translate_dialog.py
> +        translation = self.env["ir.translation"].create(
I don't understand the purpose of this test...

2021-04-06 06:00 UTC, simahawk commented on web_translate_dialog/tests/test_web_translate_dialog.py
> +        self.env["res.lang"].load_lang("de_DE")
same

2021-04-06 06:00 UTC, simahawk commented on web_translate_dialog/tests/test_web_translate_dialog.py
> +        self.env["res.lang"].load_lang("de_DE")
do not load the lang in the test, load it in setUpClass

2021-04-06 06:00 UTC, simahawk commented on web_translate_dialog/tests/test_web_translate_dialog.py
> +class TestWebTranslateDialog(TransactionCase):
use SavepointCase and load records in setUpClass

2021-04-07 05:52 UTC, dsolanki-initos commented
@simahawk can you please re-check it.

2021-04-07 05:52 UTC, fshah-initos commented
@simahawk can you please re-check it?

2021-04-30 13:22 UTC, fshah-initos commented
Hi @simahawk I have updated the PR you can re-check it

2021-05-03 09:57 UTC, simahawk requested changes

2021-05-03 09:57 UTC, simahawk commented on web_translate_dialog/__manifest__.py
> +    "InitOS Gmbh",
authors should always come before OCA. Nevertheless, you cannot add the company here since this is just a plain migration

2021-05-03 09:57 UTC, simahawk commented on web_translate_dialog/tests/test_web_translate_dialog.py
> +class TestWebTranslateDialog(TransactionCase):
what about this?

2021-05-07 11:26 UTC, grindtildeath reviewed
LG, but dependency to remove and I'll try to test it on runbot afterwards

2021-05-07 11:26 UTC, grindtildeath commented on web_translate_dialog/__manifest__.py
> +    "depends": ["web", "product"],
We definitely do not want this dependency :warning:

2021-05-07 11:26 UTC, grindtildeath commented on web_translate_dialog/tests/test_web_translate_dialog.py
> +    def test_language_translations(self):
From my POV this is a test about std behavior and doesn't bring much here, but it doesn't hurt...

2021-05-28 09:47 UTC, fshah-initos commented
Is it possible to merge it?

2021-05-28 10:58 UTC, simahawk commented
> Is it possible to merge it?

some important comments are not attended yet

2021-06-03 10:16 UTC, fshah-initos commented
I've updated the PR. Attended almost all the comments. Let me know if something is missed

2021-06-09 06:15 UTC, simahawk commented
/ocabot merge nobump

2021-06-09 06:15 UTC, simahawk approved these changes

2021-06-09 06:28 UTC, merged