[14.0] [mig] web translate dialog
OCA/web pull request #1812
Opened 2021-02-05 06:14 UTC by dsolanki-initos

2021-03-23 10:44 UTC, dsolanki-initos commented
@ferranmateu Will you please review this PR?

2021-03-29 10:58 UTC, claudiagn reviewed
It looks like these:
![captura_6](https://user-images.githubusercontent.com/61511679/112827261-6178e200-908e-11eb-89b8-e859495f2bb4.png)

And it should look like these:
![captura_5](https://user-images.githubusercontent.com/61511679/112827273-663d9600-908e-11eb-9ba1-5c0133c4b029.png)

The thing is that you can translate the name, but not all the fields, and also the field is duplicated.

2021-04-05 06:28 UTC, dsolanki-initos commented
Hi @claudiagn ,
can you please re-check it?

2021-04-06 06:02 UTC, simahawk requested changes
same remarks of https://github.com/OCA/web/pull/1801

2021-04-30 07:41 UTC, dsolanki-initos commented
I have fixed those remarks it would be great if it is reviewd and merge it ASAP.

2021-05-07 11:18 UTC, dsolanki-initos commented
I have fixed those remarks it would be great if it is reviewd and merge it ASAP.

2021-05-17 06:58 UTC, dsolanki-initos commented
Pre-commit is failed as I need to overide the method to fix the above issue.

2021-05-28 09:43 UTC, dsolanki-initos commented
It would be great if we get the review here

2021-06-04 12:31 UTC, dsolanki-initos commented
It would be great if we get the review here.

2021-06-11 08:49 UTC, dsolanki-initos commented
It would be great if we get the reviews here.

2021-06-17 08:36 UTC, dsolanki-initos commented
It would be great if we get the reviews here.

2021-07-01 10:23 UTC, dsolanki-initos commented
It would be great if we get the reviews here.

2021-07-08 09:06 UTC, dsolanki-initos commented
It would be great if we get the reviews here.

2021-07-12 12:19 UTC, gfcapalbo approved these changes
:+1 LGTM, tested and read, could not find problems.

2021-07-12 12:19 UTC, gfcapalbo commented on web_translate_dialog/models/base.py
> +    @api.model
it's appropriately model. it makes sense for this function. I agree with this.

2021-07-12 12:19 UTC, gfcapalbo commented on web_translate_dialog/static/src/js/web_translate_dialog.js
> +    var core = require("web.core");
all requires strictly needed no cruft here :+1:

2021-07-16 07:23 UTC, dsolanki-initos commented
It would be nice if we get the reviews here

2021-07-23 06:18 UTC, dsolanki-initos commented
Hi @claudiagn 
Can you please re-check the PR

2021-09-02 10:07 UTC, dsolanki-initos commented
Hi @claudiagn @simahawk 
Can you please re-check the PR

2021-09-06 14:15 UTC, simahawk commented
I got this on runbot http://3500856-1812-322b67.runbot1-3.odoo-community.org/web?debug=assets#id=23&action=278&model=product.template&view_type=form&cids=1&menu_id=174
```
Error:
TypeError: initialValue is undefined

http://3500856-1812-322b67.runbot1-3.odoo-community.org/web_translate_dialog/static/src/js/web_translate_dialog.js:204
Traceback:
_onSave/<@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web_translate_dialog/static/src/js/web_translate_dialog.js:204:21
_onSave@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web_translate_dialog/static/src/js/web_translate_dialog.js:202:67
_setButtonsTo/</<@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web/static/src/js/core/dialog.js:322:44
dispatch@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web/static/lib/jquery/jquery.js:5183:27
add/elemData.handle@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web/static/lib/jquery/jquery.js:4991:28
```
@dsolanki-initos could you check?

2021-10-08 12:22 UTC, dsolanki-initos commented
> I got this on runbot http://3500856-1812-322b67.runbot1-3.odoo-community.org/web?debug=assets#id=23&action=278&model=product.template&view_type=form&cids=1&menu_id=174
> 
> ```
> Error:
> TypeError: initialValue is undefined
> 
> http://3500856-1812-322b67.runbot1-3.odoo-community.org/web_translate_dialog/static/src/js/web_translate_dialog.js:204
> Traceback:
> _onSave/<@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web_translate_dialog/static/src/js/web_translate_dialog.js:204:21
> _onSave@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web_translate_dialog/static/src/js/web_translate_dialog.js:202:67
> _setButtonsTo/</<@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web/static/src/js/core/dialog.js:322:44
> dispatch@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web/static/lib/jquery/jquery.js:5183:27
> add/elemData.handle@http://3500856-1812-322b67.runbot1-3.odoo-community.org/web/static/lib/jquery/jquery.js:4991:28
> ```
> 
> @dsolanki-initos could you check?

Hi @simahawk 
I am not able to login with admin credentail with this link you shared. 
I've double verified it locally I am not getting such error. Can you please share video ?

2021-10-22 10:25 UTC, dsolanki-initos commented
Hi @gfcapalbo  @simahawk
Can you please re-check the PR?

2021-10-29 12:38 UTC, dsolanki-initos commented
Hi @gfcapalbo @simahawk
Can you please re-check the PR?

2021-11-12 11:06 UTC, dsolanki-initos commented
Hi @gfcapalbo @simahawk
Can you please re-check the PR?

2021-11-19 07:55 UTC, dsolanki-initos commented
Hi @gfcapalbo @simahawk
Can you please re-check the PR?

2021-11-26 09:41 UTC, dsolanki-initos commented
Hi @gfcapalbo @simahawk
Can you please re-check the PR?

2021-12-03 08:48 UTC, dsolanki-initos commented
Hi @simahawk
I've verified it locally I am not getting an error. Can you please share a video?

2021-12-03 15:15 UTC, simahawk requested changes
question: don't we need to fwd port this? https://github.com/OCA/web/pull/1974

2021-12-03 15:15 UTC, simahawk commented on web_translate_dialog/tests/test_web_translate_dialog.py
> +        self.partner_title = self.env["res.partner.title"].create({"name": "Doctor"})
Can you move this to `SavepointCase.setUpClass`? This code runs for all tests.

2021-12-03 15:16 UTC, simahawk commented
> Hi @simahawk I've verified it locally I am not getting an error. Can you please share a video?

sorry, I have no time now. I trust you've done proper testing :wink:

2021-12-10 08:50 UTC, dsolanki-initos commented
@simahawk could please give approval to this pull?

2021-12-10 09:24 UTC, simahawk commented
> @simahawk could please give approval to this pull?

have you seen my comment above?

2021-12-17 12:26 UTC, dsolanki-initos commented
@albariera could you please check this pull?

2021-12-24 10:42 UTC, dsolanki-initos commented
@simahawk could you please give approval to this pull?

2021-12-27 08:58 UTC, simahawk commented
@dsolanki-initos you pinged me already several times but my comments are still not attended, not even answered :man_shrugging: 


![image](https://user-images.githubusercontent.com/347149/147454621-b695e112-daa2-4b8d-a695-a9a3b736e06d.png)

2022-09-08 14:31 UTC, bosd commented
Interesting PR!

2024-08-11 12:33 UTC, closed without merging