[FIX] v13_web_responsive: fix error view image, pdf, video on mobile
OCA/web pull request #1911
Opened 2021-04-29 10:05 UTC by daonamutc1

Fix issuse #1910

2021-04-29 16:03 UTC, pedrobaeza commented
Why is that needed? I'm able to see images and video without it? Do you have any other module on top of this one?

2021-04-30 02:26 UTC, daonamutc1 commented
Please my video and image.
You will see .o_modal_fullscreen.o_document_viewer has z-index: 10 small than z-index: 1051 of .o_thread_window
Casue that o_modal_fullscreen will hide.

https://user-images.githubusercontent.com/55737816/116641057-2839d780-a996-11eb-81d0-31caa22e4a9a.mp4

![Uploading IMG_20210430_091915_hdr.jpg…]()

2021-04-30 06:20 UTC, pedrobaeza commented
In your video, it seems you have another theme on top of `web_responsive`. Unless you prove that in standard `web_responsive`, this is needed, this is not needed here, but on your customization.

2021-05-04 01:49 UTC, daonamutc1 commented
> In your video, it seems you have another theme on top of `web_responsive`. Unless you prove that in standard `web_responsive`, this is needed, this is not needed here, but on your customization. Check the same on runbot, and provide detailed steps to reproduce the problem (not only a video of the last step).

Please, check again.

https://user-images.githubusercontent.com/55737816/116952721-87109100-acb5-11eb-9c6a-b09eb1efd0ac.mp4

![Screen Shot 2021-05-04 at 08 43 50](https://user-images.githubusercontent.com/55737816/116952736-9263bc80-acb5-11eb-90e6-03a1603d703d.png)

2021-05-04 13:58 UTC, pedrobaeza approved these changes
OK, so it seems when you attach an image on a chat, it gets a higher z-index. Then it's OK for me to change it.

2021-05-04 16:18 UTC, Tardo requested changes
Thanks for the fix! Please, use sass variables instead of hardcoded values when possible.

2021-05-04 16:18 UTC, Tardo commented on web_responsive/static/src/css/web_responsive.scss
> +        z-index: 1052;
```suggestion
        z-index: $o-mail-thread-window-zindex + 1;
```

2021-05-05 01:14 UTC, pedrobaeza commented
Please squash both commits into one and change commit message to the proper one: it's not due to mobile, but previewing files from a chat window.

2021-05-05 10:41 UTC, Tardo commented
Please, normalize commit message to something like: 
`[FIX] web_responsive: Change z-index of document preview

Previous this commit, the document preview can't be used properly because ...
`

Thanks!

2021-05-18 14:55 UTC, pedrobaeza commented
@daonamutc1 thanks for the change, but I'm afraid you have put only the second line. Can you please put the whole commit message? You need also to throw a comment for the rest to be aware that you have made the change.

2024-09-08 12:35 UTC, closed without merging