[13.0][IMP] web_pwa_oca: Apple Icons
OCA/web pull request #1997
Opened 2021-07-30 17:08 UTC by Tardo

Improve support to display icons on IOS

cc @tecnativa TT31173

2021-07-30 17:51 UTC, pedrobaeza commented
Travis is red

2021-07-30 17:58 UTC, Tardo commented
Travis is happy

2021-07-31 10:33 UTC, pedrobaeza commented on web_pwa_oca/templates/assets.xml
> +                    sizes="57x57"
What about if we don't declare all these variants? It's too much noise IMO.

2021-08-03 06:39 UTC, Yajo requested changes
It seems ios can't handle transparency properly and applies a black background, so the little ant becomes invisible. Besides, that produces some animation glitches when closing the app. The icons should use a solid background. Other than that, it seems to work:

![imagen](https://user-images.githubusercontent.com/973709/127969429-62027318-920d-48e3-967f-46fa2887b0a5.png)

2021-08-03 06:39 UTC, Yajo commented on web_pwa_oca/models/res_config_settings.py
> +                            **{"icon_size": DEFAULT_ICON_SIZE}
```suggestion
                            icon_size=DEFAULT_ICON_SIZE
```

2021-08-03 06:39 UTC, Yajo commented on web_pwa_oca/models/res_config_settings.py
> +    (180, 180),
All sizes are square. Would it make sense to just write one of the dimensions?

2021-08-03 06:40 UTC, pedrobaeza commented
The idea is also to try custom image, as the default one was previously working.

2021-08-03 06:54 UTC, Yajo commented
Custom image works: 
![imagen](https://user-images.githubusercontent.com/973709/127971100-43d5372c-2eda-4a9b-937b-e18e38b2a81e.png)

2021-08-05 06:12 UTC, joao-p-marques approved these changes
Code and functional review :+1: 

As commented by @Yajo, it would be nice to solve the background issue, but it is not a blocking issue and it is working as expected I think.

2021-08-06 09:26 UTC, AntoniRomera approved these changes

2021-08-19 09:31 UTC, AntoniRomera commented
@Yajo We can merge this PR and open an issue for the background colour issue, I think it's not a bug that blocks usability.

2021-08-20 07:08 UTC, Yajo commented
Yes, after all I guess nobody will want to use the default icon, so the fact it doesn't look good is not a big problem.

2021-08-20 07:09 UTC, Yajo approved these changes

2021-08-20 07:09 UTC, Yajo commented
/ocabot merge patch

2021-08-20 07:16 UTC, pedrobaeza commented
I have aborted the merge. My comment still applies. This is adding too much noise and stored icons. I think only bigger one should be stored and declared, and Apple code should be smart enough to take the rest.

2021-09-08 17:30 UTC, Tardo commented
The problem with the background is because iPhone uses 'Maskable Icons' by default... currently chrome supports it. This  is the way that browsers adds support for "Adaptive Icons" in PWA.
So... one solution is to not use icons with alpha channel and follow the rule to make "maskable icons".

How "Maskable Icons" works:
https://storage.googleapis.com/web-dev-uploads/video/tcFciHGuF3MxnTr1y5ue01OGLBn2/mx1PEstODUy6b5TXjo4S.webm

2021-09-09 21:07 UTC, pedrobaeza commented
I insist in not putting that bunch of images, but only the minimal one. Can we put the bigger one and let iOS resize?

2021-09-10 12:25 UTC, Tardo commented
I will try with only 192x192 and 255x255 that its the minimum required by "lighthouse" to validate a PWA manifest.

And i will generate the new default icons with: https://maskable.app/editor

2024-12-15 12:40 UTC, closed without merging