[MIG] web_refresher: Migration to 15.0
OCA/web pull request #2056
Opened 2021-10-20 20:14 UTC by nabilragab

There is a minor issue I seem to understand, theoretically should work, but it doesn't render the refresher next to the pager components, the mistake I am doing is probably related to the core JS framework changes, can someone give a hint on how to  render the button :/

2021-10-21 15:10 UTC, SplashS requested changes
Hello! I think I give you enough feedback to make it works.

In v15 there are two implementations of ControlPanel.
In this PR module only legacy one has been patched.
Fortunately new implementation is used only for pivot and graph views. And web_refresher module doesn't support them anyway.

2021-10-21 15:10 UTC, SplashS commented on web_refresher/__manifest__.py
> +    'web.assets_qweb': [
You should put "web.assets_qweb" inside another dict. It should looks like "assets": { "web.assets_qweb": [...], },

2021-10-21 15:10 UTC, SplashS commented on web_refresher/static/src/legacy/xml/web_refresher.xml
> +        <xpath expr="//nav[hasclass('o_pager')]//span[1]" position="after">
Please prefer simple xpaths. in this case I suggest //span[hasclass('o_pager_counter')]

2022-10-25 15:47 UTC, pedrobaeza commented
Already merged through other PR.

2022-10-25 15:47 UTC, closed without merging