[15.0][MIG] web_widget_open_tab: Migration to 15.0
OCA/web pull request #2089
Opened 2021-11-22 04:27 UTC by BankyKmitl

2021-11-25 10:16 UTC, tarteo requested changes
Runbot didn't work so I tested it locally.

The widget doesn't seem to work:

![image](https://user-images.githubusercontent.com/10028499/143422887-cf95b853-47d2-4d24-b2f9-7bb03dca5e05.png)

2021-11-25 10:35 UTC, BankyKmitl commented
fixed

2022-02-09 03:37 UTC, BankyKmitl commented
@pedrobaeza Could you check this for a merge?

2022-02-09 07:12 UTC, pedrobaeza commented
Please follow the contribution guidelines https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review and start having green CI. You should review other PRs and ask in exchange that they review yours.

2025-03-02 12:36 UTC, closed without merging