[15.0][MIG] web_widget_bokeh_chart
OCA/web pull request #2107
Opened 2021-12-06 21:01 UTC by ChrisOForgeFlow

- Upgrade bokeh version to 2.4.2
- Refactor to user new module definitions
@ForgeFlow

2021-12-06 21:20 UTC, celm1990 requested changes
Please keep commit  history according https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

2021-12-06 21:20 UTC, celm1990 commented on web_widget_bokeh_chart/__manifest__.py
> +    "version": "15.0.2.3.1",
```suggestion
    "version": "15.0.1.0.0",
```

2021-12-06 21:20 UTC, celm1990 commented on web_widget_bokeh_chart/README.rst
> +This module is part of the `OCA/web <https://github.com/OCA/web/tree/14.0/web_widget_bokeh_chart>`_ project on GitHub.
```suggestion
This module is part of the `OCA/web <https://github.com/OCA/web/tree/15.0/web_widget_bokeh_chart>`_ project on GitHub.
```

2021-12-07 13:16 UTC, ChrisOForgeFlow commented
> Please keep commit history according https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

Thanks

2021-12-20 07:51 UTC, LoisRForgeFlow approved these changes
LGTM :+1:

2021-12-20 07:51 UTC, LoisRForgeFlow commented
@celm1990 Could you update your review?

2021-12-21 20:05 UTC, celm1990 commented on web_widget_bokeh_chart/static/src/js/web_widget_bokeh_chart.esm.js
> +            $("head").append(script);
Please if possible,  can comment your code, because is need do it??, only for understand

I see on V14 is simple `this.$el.html(val);` but here is more complex

2021-12-21 20:22 UTC, ChrisOForgeFlow commented on web_widget_bokeh_chart/static/src/js/web_widget_bokeh_chart.esm.js
> +            $("head").append(script);
When I tested in the new odoo framework it did not load the bokeh graph with the previous implementation, so I had to find a way to add the script in a more standard way for the browser

https://stackoverflow.com/questions/13121948/dynamically-add-script-tag-with-src-that-may-include-document-write

2021-12-22 03:23 UTC, celm1990 approved these changes

2022-01-10 15:21 UTC, LoisRForgeFlow commented
@OCA/web-maintainers This one can be merge IMO.

2022-01-10 15:21 UTC, etobella approved these changes

2022-01-12 14:44 UTC, LoisRForgeFlow commented
@pedrobaeza could you help to get this merged?

2022-01-12 15:36 UTC, pedrobaeza commented
/ocabot merge nobump
/ocabot migration web_widget_bokeh_chart

2022-01-12 15:41 UTC, merged