7.0 add web note and web note test
OCA/web pull request #216
Opened 2015-09-07 07:56 UTC by ntodorova

This module can be used for adding a notes field in any module that need them.
There are three type of notes - private, internal, external. 
Only the user that create a private note can see it. The other two types can be used for creating different views.
There is also a test module that shows use case.

2015-09-07 14:00 UTC, ntodorova commented
@rami-wafaie would you please review this?

2016-01-08 21:50 UTC, OSguard commented
2016-01-08 21:40:40,751 10470 WARNING 3139434-216-bd51b9-all openerp.modules.loading: The model web.note has no access rules, consider adding one. E.g. access_web_note,access_web_note,model_web_note,,1,1,1,1
2016-01-08 21:40:40,751 10470 WARNING 3139434-216-bd51b9-all openerp.modules.loading: The model web.note.container has no access rules, consider adding one. E.g. access_web_note_container,access_web_note_container,model_web_note_container,,1,1,1,1

should be fixed

2016-01-15 14:55 UTC, rami-wafaie commented
:thumbsup:

2016-01-29 16:12 UTC, OSguard commented on web_note/__openerp__.py
> +    'version': '0.1',
7.0.1.0

2016-04-06 18:43 UTC, hbrunn commented
nice idea. Why don't you provide an abstract model that has some predefined notes field, so that users of this function only need to say
```python
class MyModel(models.Model):
    _inherit = ['original.model', 'your.abstract.model']
```
and adapt their views? That's a lot more convenient imho

2016-04-06 18:45 UTC, hbrunn commented on web_note_test/__init__.py
> +# -*- coding: utf-8 -*-
don't add a demo module on this level. Put it into your actual module, if somebody want to try this out, this person can symlink it into the addons path

2016-10-20 12:58 UTC, pedrobaeza commented
There are comments unattended. Is there anyone interested in this?

2016-10-21 08:01 UTC, ntodorova commented
Yes, I would like to finish that one. @hbrunn I was just confused about your comment, what is your idea for abstract module with o2m field, how should the connection be implemented?

2016-10-21 11:03 UTC, hbrunn commented
don't worry about this for now, let's merge first

2016-10-24 06:12 UTC, ntodorova commented
Ok, so then from my side it is ready. What do we need so we can merge it?

2016-10-24 09:42 UTC, pedrobaeza requested changes

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/README.rst
> +Web Note
Please use latest README template: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/README.rst
> +Installing the module itself is enough.
Remove useless section like this one or configuration

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/README.rst
> +Versions
This section is not one of the valid ones.

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/__init__.py
> +##############################################################################
Please short headers like in https://github.com/OCA/maintainer-tools/blob/master/template/module/__init__.py

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/__openerp__.py
> +    'version': '7.0.1.0',
It should be 7.0.1.0.0

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/__openerp__.py
> +    'js': [
Remove empty keys

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/web_note.py
> +class web_note(orm.Model):
CamelCase for class name: `WebNote`

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/web_note.py
> +class web_note_container(orm.Model):
CamelCase

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/web_note.py
> +##############################################################################
Short header

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/__openerp__.py
> +##############################################################################
Short header

2016-10-24 09:42 UTC, pedrobaeza commented on web_note/web_note_view.xml
> +</openerp>
Linebreak at the end

2016-10-24 09:42 UTC, pedrobaeza commented on web_note_test/__init__.py
> +# -*- coding: utf-8 -*-
I agree this should go in the main module, as res.partner is a base model.

2016-10-24 09:42 UTC, pedrobaeza commented on web_note_test/web_note.py
> +        'res_partner_id':
Usual name for this field is `partner_id`. You should rename it

2016-10-25 13:17 UTC, ntodorova commented
@pedrobaeza I have made the changes you required.

2016-10-25 19:41 UTC, pedrobaeza approved these changes
Thanks for the changes

2016-10-25 19:41 UTC, merged