[14.0][ADD] web_widget_x2many_2d_matrix, no input as string
OCA/web pull request #2206
Opened 2022-05-01 08:01 UTC by kittiu

Do not allow character in the input field.

![no_char](https://user-images.githubusercontent.com/1973598/166137461-7348b13c-204b-48b2-b1ce-a3c470b0e583.gif)

2022-05-01 08:05 UTC, kittiu commented
@OCA/web-maintainers 
Because sometime user may accidentally include string and when saved it just disappear without warning.
But my JS is very limited, not sure this is the correct way to work with, please feel free to suggest. Thanks!

2022-05-03 13:47 UTC, tarteo approved these changes
Thanks, LGTM :+1:

2022-05-03 13:59 UTC, pedrobaeza commented
Not sure this limitation is OK, as you value field may be of any type. I think you should use the widget of the field type (or even allow to customize it).

2022-05-03 14:03 UTC, legalsylvain commented
> Not sure this limitation is OK, as you value field may be of any type. I think you should use the widget of the field type (or even allow to customize it).

Indeed, AFAIK, you can "matrix" any fields, including "char".

>  when saved it just disappear without warning.

Well, maybe that point should be improved ? adding a blocking message if data is not correct.

2022-05-03 14:06 UTC, hbrunn requested changes
you'll need to check if the field type is one of the numerical ones, as this widget also supports char fields.

I also think the check needs to be more complex, because any non-US way of formatting numbers won't pass through `isNaN`.

In the end, I think this is a job for https://github.com/OCA/OCB/blob/14.0/addons/web/static/src/js/fields/abstract_field.js#L305 where you can check if all your input is valid, and set error classes otherwise

2022-05-03 14:08 UTC, pedrobaeza commented
I don't have too much knowledge in JS, but populating the field widget isn't possible and you don't have to worry about these things?

2022-05-03 14:16 UTC, tarteo commented
If all field types are supproted it should be done by the field class (of the specific field type)

2022-05-04 01:59 UTC, kittiu commented
Hello Thanks to all pointers. In fact, I also not satisfied by what I need (so far it is ok only on my project).
I would love to make it on the field widget level, just that my JS is very poor. With the given pointer I will try again.

May be, I will check if it is possible to add field type as parameter of matrix widget. Thanks again.

2025-04-27 12:40 UTC, closed without merging