[15.0][MIG] web_timeline: Migration to 15.0
OCA/web pull request #2247
Opened 2022-07-05 12:48 UTC by cesar-tecnativa

cc @Tecnativa TT35806

2022-07-05 12:50 UTC, cesar-tecnativa commented
@CarlosRoca13 please review

2022-07-05 12:51 UTC, cesar-tecnativa commented
@Tardo please review

2022-07-05 21:34 UTC, pedrobaeza commented
Have you tested it in a real case like with `project_timeline`?

2022-07-05 21:49 UTC, cesar-tecnativa commented
> Have you tested it in a real case like with `project_timeline`?

This is the goal https://github.com/OCA/project/pull/942

2022-07-06 05:21 UTC, CarlosRoca13 requested changes

2022-07-06 05:21 UTC, CarlosRoca13 commented on web_timeline/__manifest__.py
> +    ],
```suggestion
    "assets": {
        "web.assets_backend": [
            "web_timeline/static/src/scss/web_timeline.scss",
            "web_timeline/static/src/js/timeline_view.js",
            "web_timeline/static/src/js/timeline_renderer.js",
            "web_timeline/static/src/js/timeline_controller.js",
            "web_timeline/static/src/js/timeline_model.js",
            "web_timeline/static/src/js/timeline_canvas.js",
        ]
    },
```

2022-07-06 07:18 UTC, CarlosRoca13 approved these changes

2022-07-15 20:52 UTC, cesar-tecnativa commented
@sergio-teruel plesae review

2022-07-26 07:51 UTC, cesar-tecnativa commented
@LudLaf please review

2022-07-28 13:51 UTC, jguenat reviewed
Hello,
I tested this with project_timeline.
See requested changes

2022-07-28 13:51 UTC, jguenat commented on web_timeline/__manifest__.py
> +        ]
```suggestion
        ],
        "web.assets_qweb": [
            "web_timeline/static/src/xml/web_timeline.xml",
        ],
```

2022-07-28 13:51 UTC, jguenat commented on web_timeline/static/src/js/timeline_view.js
> +        }),
```suggestion
        }),
        viewType: 'timeline',
```

2022-07-29 08:30 UTC, jguenat commented
Also, what do you think about updating vis-timeline-graph2d lib to V 7.7?
https://unpkg.com/vis-timeline@7.7.0/peer/umd/vis-timeline-graph2d.min.js
https://unpkg.com/vis-timeline@7.7.0/styles/vis-timeline-graph2d.min.css

2022-07-29 12:00 UTC, chrisandrewmann commented
Issue with grouping by many2many fields causes crash as mentioned here.
https://github.com/OCA/project/pull/942#issuecomment-1198966193

2022-08-02 12:41 UTC, chrisandrewmann commented
@CarlosRoca13 Thanks for that, awesome job with adding the m2m field grouping. I had tried myself but javascript is not my strongest point.

2022-08-02 12:42 UTC, CarlosRoca13 commented
Hi! I added the changes added on https://github.com/OCA/web/pull/2256

I have also corrected the implementation to allow grouping by m2m fields with some restrictions:
When grouping by m2m and more than one record is set, the timeline item appears just on one group.
When grouping by m2m and dragging for changing the time or the group, the changes on the group will not be set, because it could make disappear the records not related with the changes that we want to make.

2022-08-02 12:47 UTC, CarlosRoca13 commented
I also tried to add the new libraries, but more changes to adjust the code were needed,  so I have chosen to focus on the main problem

2022-08-02 14:54 UTC, chrisandrewmann commented
@CarlosRoca13 Have given it a quick test and only problem I see is that any M2M field (i.e Assignees on project.task) that have no value set no longer appear on the timeline. Was that intentional as I know there were some restrictions?
Previously and with M2O fields they would appear in category "UNASSIGNED".

2022-08-02 15:43 UTC, chrisandrewmann commented on web_timeline/static/src/js/timeline_renderer.js
> +            if (group && group instanceof Array) {
To fix issue where events are not displayed under UNASSIGNED group when using a M2M field.
Add this small change:

`            if (group && group instanceof Array && group.length > 0) {`

2022-08-02 16:45 UTC, LudLaf commented on web_timeline/static/src/js/timeline_renderer.js
> +            if (group && group instanceof Array) {
Suggested change `if (group && group instanceof Array && group.length > 0) {` added.

2022-08-03 11:30 UTC, CarlosRoca13 commented
Added fix and updated libraries as done in PR https://github.com/OCA/web/pull/2268

2022-08-03 16:43 UTC, pedrobaeza commented
Have you tested? I find weird behaviors when testing it in v14.

2022-08-04 04:46 UTC, CarlosRoca13 commented
Yes, and I didn't found that problems...

2022-08-04 06:40 UTC, pedrobaeza commented
/ocabot migration web_timeline
/ocabot merge nobump

2022-08-04 06:45 UTC, merged