[15.0] [mig] web_notify
OCA/web pull request #2273
Opened 2022-08-10 12:00 UTC by aiendry-aktivsoftware

2022-12-12 11:12 UTC, chienandalu requested changes
Functionally ok. Thanks!

Can you use ES6 completly (suggestions below; you'll also have to rename the js files to whatever_file.esm.js) so it's not necessary to do it in latter migrations?

2022-12-12 11:12 UTC, chienandalu commented on web_notify/static/src/js/services/notification_services.js
> +    const webNotificationService = {
```suggestion
/** @odoo-module **/

import { browser } from "@web/core/browser/browser";
import { registry } from "@web/core/registry";

export const webNotificationService = {
```

2022-12-12 11:12 UTC, chienandalu commented on web_notify/static/src/js/services/notification.js
> +    const {patch} = require("web.utils");
```suggestion
/** @odoo-module */

import {Notification} from "@web/core/notifications/notification";
import { patch } from "web.utils";

2022-12-12 11:28 UTC, CarlosRoca13 approved these changes
Thanks :+1: 

Please review the comments of @chienandalu

2022-12-12 11:53 UTC, pedrobaeza commented
/ocabot migration web_notify

2023-01-05 14:44 UTC, chienandalu approved these changes
Non blocking this

2023-01-05 14:58 UTC, pedrobaeza commented
@chienandalu I think you should supersede the PR respecting his attribution, but adding your improvements.

2023-01-05 15:53 UTC, pedrobaeza commented
Superseded by #2381

2023-01-05 15:53 UTC, closed without merging