[MIG] web_advanced_search: Migration to 16.0
OCA/web pull request #2357
Opened 2022-12-06 09:01 UTC by hvgollar

2022-12-06 12:00 UTC, StefanRijnhart requested changes, later dismissed
Runboat seems broken so I had to do a local install of your version of the module but it does not seem to work for me. The `Add advanced filter` option is missing from the search filter:
![image](https://user-images.githubusercontent.com/1033124/205905766-7bda74c4-2219-4a37-95df-1dc4c23cc247.png)

I'm also getting 'missing dependency' errors in the web developer console about this module:
```
Debug:                    
Object { "@web_advanced_search/js/legacy/CustomFilterItem.esm": {…}, "@web_advanced_search/js/legacy/FilterMenu.esm": {…}, "@web_advanced_search/js/owl/CustomFilterItem.esm": {…}, "@web_advanced_search/js/owl/FilterMenu.esm": {…} }
​
"@web_advanced_search/js/legacy/CustomFilterItem.esm": Object { dependencies: (3) […], dependents: [], name: "@web_advanced_search/js/legacy/CustomFilterItem.esm", … }
​​
dependencies: Array(3) [ "web.CustomFilterItem", "@web_advanced_search/js/RecordPicker.esm", "@web/core/utils/patch" ]
​​
dependents: Array []
​​​
length: 0
​​​
<prototype>: Array []
​​
missing: Array [ "@web_advanced_search/js/RecordPicker.esm" ]
​​​
0: "@web_advanced_search/js/RecordPicker.esm"
​​​
length: 1
​​​
<prototype>: Array []
​​
name: "@web_advanced_search/js/legacy/CustomFilterItem.esm"
​​
<prototype>: Object { … }
​
"@web_advanced_search/js/legacy/FilterMenu.esm": Object { dependencies: (3) […], dependents: [], name: "@web_advanced_search/js/legacy/FilterMenu.esm", … }
​​
dependencies: Array(3) [ "@web_advanced_search/js/legacy/AdvancedFilterItem.esm", "web.FilterMenu", "@web/core/utils/patch" ]
​​
dependents: Array []
​​
missing: Array [ "@web_advanced_search/js/legacy/AdvancedFilterItem.esm" ]
​​
name: "@web_advanced_search/js/legacy/FilterMenu.esm"
​​
<prototype>: Object { … }
​
"@web_advanced_search/js/owl/CustomFilterItem.esm": Object { dependencies: (3) […], dependents: [], name: "@web_advanced_search/js/owl/CustomFilterItem.esm", … }
​​
dependencies: Array(3) [ "@web/search/filter_menu/custom_filter_item", "@web_advanced_search/js/RecordPicker.esm", "@web/core/utils/patch" ]
​​
dependents: Array []
​​
missing: Array [ "@web_advanced_search/js/RecordPicker.esm" ]
​​
name: "@web_advanced_search/js/owl/CustomFilterItem.esm"
​​
<prototype>: Object { … }
​
"@web_advanced_search/js/owl/FilterMenu.esm": Object { dependencies: (3) […], dependents: [], name: "@web_advanced_search/js/owl/FilterMenu.esm", … }
​​
dependencies: Array(3) [ "@web_advanced_search/js/owl/AdvancedFilterItem.esm", "@web/search/filter_menu/filter_menu", "@web/core/utils/patch" ]
​​
dependents: Array []
​​
missing: Array [ "@web_advanced_search/js/owl/AdvancedFilterItem.esm" ]
​​
name: "@web_advanced_search/js/owl/FilterMenu.esm"
​​
<prototype>: Object { … }
​
<prototype>: Object { … }
boot.js:355
```
Did this module work for you when you were porting it?

2022-12-14 13:36 UTC, nicolascol approved these changes
LGTM

2022-12-15 18:35 UTC, rven commented
@StefanRijnhart Can you verify if everything is fine now?

2022-12-19 12:42 UTC, pablontura commented
review functional LGTM

2023-01-13 16:37 UTC, chienandalu requested changes
The many2one custom filter *is equal to* doesn't work:

![Peek 13-01-2023 17-35](https://user-images.githubusercontent.com/5040182/212371937-f42a2a62-d5ed-47b7-a590-f629ba009a22.gif)

2023-01-24 15:00 UTC, rven commented
The error is fixed, but the filter's dropdown will be closed after a selection.

Could anyone suggest what needs to be changed to prevent this?

This does not work anymore
```python
    /**
     * Stop propagation of the autocompleteselect event.
     * Otherwise, the filter's dropdown will be closed after a selection.
     *
     * @override to stop propagating autocompleteselect event
     */
    start: function () {
        this._super(...arguments);
        this.$input.on("autocompleteselect", (event) => event.stopPropagation());
    },
```

2023-02-03 13:33 UTC, dynapps commented
I figured out after long investigation why the Filter menu was closed after selecting a value in the RecordPicker Component.
The selection values are added at this place
![image](https://user-images.githubusercontent.com/14269909/216615074-42190f1a-8286-4aa6-a2f3-d5765bf40a3f.png)
This causes the filter menu to be closed, when selecting a value, because it reaches this code in Odoo
https://github.com/odoo/odoo/blob/16.0/addons/web/static/src/core/dropdown/dropdown.js#L277-L305
`gotClickedInside` results in false, because the ul element doesn't belong to the `o_add_custom_filter_menu`
![image](https://user-images.githubusercontent.com/14269909/216615861-0b75f588-2daa-437b-833c-b259870b0185.png)
If somebody knows a better solution than patching the `dropDown` component please let me know!
But for now the solution is working fine!

2023-02-17 13:38 UTC, kmagusiak commented
In debug mode, inputting the domain in the editor seems to have no effect. It was a very handy feature if you copy-paste a domain.
![image](https://user-images.githubusercontent.com/1943198/219667004-8bc489ad-b0db-46c9-90cf-c4d73c3d7781.png)

2023-02-17 13:39 UTC, pedrobaeza commented
But that's something of this module, or something of the domain editor widget of Odoo core?

2023-02-17 15:16 UTC, rven commented
> But that's something of this module, or something of the domain editor widget of Odoo core?

I think this is something that is fixed by this https://github.com/odoo/odoo/pull/109238

2023-03-07 12:12 UTC, liebana commented
There's a weird behaviour searching in one 2 many fields in custom filter (not in advanced). For example, filtering products that contains product category "furniture" it makes the search, but replaces the text string by "e" in the filter bar.

![image](https://user-images.githubusercontent.com/7783296/223418586-1ccf82a5-dd24-4e7f-bc73-e1d284478b2c.png)

2023-03-07 13:51 UTC, rven commented
> [liebana](/liebana)

This should be fixed!

2023-03-07 14:00 UTC, liebana commented
> > There's a weird behaviour searching in one 2 many fields in custom filter (not in advanced). For example, filtering products that contains product category "furniture" it makes the search, but replaces the text string by "e" in the filter bar.
> > ![image](https://user-images.githubusercontent.com/7783296/223418586-1ccf82a5-dd24-4e7f-bc73-e1d284478b2c.png)
> 
> This should be fixed! ![image](https://user-images.githubusercontent.com/8638295/223442552-8cd80a67-d456-4db9-861d-15602afcfd97.png) I also remove the old legacy code, because tree view is now also converted to OWL in 16.0.

Partially fixed :(

I write "Furniture" in the field box, but when I focus outside it changes to "u"... although the search is made with "furniture".

[Odoo - Products.webm](https://user-images.githubusercontent.com/7783296/223443946-75900dd2-07eb-4141-b471-d0574c99e704.webm)

2023-03-07 15:16 UTC, rven commented
> I write "Furniture" in the field box, but when I focus outside it changes to "u"... although the search is made with "furniture".

@liebana Should be fixed now!

2023-03-08 12:41 UTC, liebana commented
Solved, thanks!

2023-03-09 09:13 UTC, StephaneMangin commented
cc @StefanRijnhart Is it ok for you now ?

2023-03-09 09:20 UTC, chienandalu commented
This is still failing (https://github.com/OCA/web/pull/2357#pullrequestreview-1247999672)

![advanced-search-v16](https://user-images.githubusercontent.com/5040182/223977045-1de9be6e-0b33-47ca-87e6-407c77234d4a.gif)

2023-03-09 15:09 UTC, rven commented
I'm stuck here, my knowledge of the OWL framework is not enough to handle this error.
Somebody else should pick this up!

2023-03-09 15:17 UTC, chienandalu commented
Ok, it's kinda tricky as it's related to compatibility layer between OWL and the legacy widget system.

2023-03-13 09:28 UTC, kmagusiak commented
> > I write "Furniture" in the field box, but when I focus outside it changes to "u"... although the search is made with "furniture".
> 
> @liebana Should be fixed now!

Pasting the domain in the debug mode works but is not reflected in the user interface. After saving the label on the filter is also wrong probably because it's based on what is displayed to the user. Probably something for odoo to fix.

2023-03-13 09:30 UTC, rven commented
> > > I write "Furniture" in the field box, but when I focus outside it changes to "u"... although the search is made with "furniture".
> > 
> > 
> > @liebana Should be fixed now!
> 
> Pasting the domain in the debug mode works but is not reflected in the user interface. After saving the label on the filter is also wrong probably because it's based on what is displayed to the user. Probably something for odoo to fix.

This is already fixed!

I only have a problem with the search more functionality, it does a trigger_up until it gets to the "dummy" object and there the error is raised.

2023-03-13 16:21 UTC, rven commented
> This is still failing ([#2357 (review)](https://github.com/OCA/web/pull/2357#pullrequestreview-1247999672))
> 
> ![advanced-search-v16](https://user-images.githubusercontent.com/5040182/223977045-1de9be6e-0b33-47ca-87e6-407c77234d4a.gif) [ ![advanced-search-v16](https://user-images.githubusercontent.com/5040182/223977045-1de9be6e-0b33-47ca-87e6-407c77234d4a.gif) ](https://user-images.githubusercontent.com/5040182/223977045-1de9be6e-0b33-47ca-87e6-407c77234d4a.gif) [ ](https://user-images.githubusercontent.com/5040182/223977045-1de9be6e-0b33-47ca-87e6-407c77234d4a.gif)

I have found a fix for this, for me it's working fine now!
Only I don't know if it's ok regarding the OWL JS guidelines ;-)

2023-03-14 12:01 UTC, liebana commented
Some testing on my side. Everything seems fine, thank you very much.

I haven't tested in previous versions, but I find this padding on the filter box annoying:

![image](https://user-images.githubusercontent.com/7783296/224992573-4c31ba99-209d-4f00-a831-2d1db2195d27.png)

IMHO at least the "and" and "or" querys should be concatenated in a new line and the box has to be resized to the longest line. Or maybe we can "resume" somehow the query.

2023-03-14 12:08 UTC, chienandalu commented
> I have found a fix for this, for me it's working fine now! Only I don't know if it's ok regarding the OWL JS guidelines ;-)

Great! Well, the surrounding implementation is quite hackish anyway. Let's hope in a future it can be fully implemented in OWL so everything is more transparent

2023-03-14 12:08 UTC, chienandalu approved these changes

2023-03-14 18:11 UTC, pedrobaeza commented
@StefanRijnhart is it ok for you?

2023-03-14 20:14 UTC, pedrobaeza commented
/ocabot migration web_advanced_search

2023-03-23 11:42 UTC, StephaneMangin commented
@StefanRijnhart Can you update your review please to go further ? Thanks

2023-04-04 12:19 UTC, vib-adhoc commented
Hi @rven , I detected an error with the Odoo Enterprise Timesheets application. 

![Odoo - My Timesheets](https://user-images.githubusercontent.com/96496796/229788179-f6fc64b1-77b3-4a19-b611-759f4847f22f.gif)

Full traceback:

`UncaughtPromiseError > OwlError
Uncaught Promise > Cannot find the definition of component "AdvancedFilterItem"
OwlError: Cannot find the definition of component "AdvancedFilterItem"
    at http://16.odoo.localhost/web/assets/409-49aa605/web.assets_common.min.js:2073:33
    at FilterMenu.slot2 (eval at compile (http://16.odoo.localhost/web/assets/409-49aa605/web.assets_common.min.js:2040:370), <anonymous>:69:11)
    at callSlot (http://16.odoo.localhost/web/assets/409-49aa605/web.assets_common.min.js:1652:25)
    at Dropdown.template (eval at compile (http://16.odoo.localhost/web/assets/409-49aa605/web.assets_common.min.js:2040:370), <anonymous>:33:18)
    at RootFiber._render (http://16.odoo.localhost/web/assets/409-49aa605/web.assets_common.min.js:1477:96)
    at RootFiber.render (http://16.odoo.localhost/web/assets/409-49aa605/web.assets_common.min.js:1476:6)
    at ComponentNode.render (http://16.odoo.localhost/web/assets/409-49aa605/web.assets_common.min.js:1562:56)`
   
Could you review this before merging?

2023-04-04 12:55 UTC, chienandalu commented
@vib-adhoc the compatibility scope for OCA modules is limited to Odoo core (CE) and optionally other OCA modules. Enterprise or other private modules compatibility should be non blocking IMO.

2023-04-21 00:49 UTC, rafaelbn commented
Thank you for this great work @hvgollar @rven ! 😄 ❤️ 

@modon MT-2797

2023-04-21 08:41 UTC, fcvalgar approved these changes
Functional review.
LGTM, Thank you @hbrunn @StefanRijnhart and all maintainers.

2023-04-27 12:58 UTC, yajo commented
> I detected an error with the Odoo Enterprise Timesheets application



It turns out that [Odoo 16 is still using the `web.FilterMenu` legacy widget for the also legacy `web.ControlPanel` widget](https://github.com/odoo/odoo/blob/04d11bf763068dabedc667266e1a6adf0b5db8c0/addons/web/static/src/legacy/js/control_panel/control_panel.js#L8). Also turns out that the timesheets app uses those legacy widgets.

This PR is removing legacy widget support (which was included for v15). Thus, that app breaks.

This can be considered a regression, because that support was there in the previous version. Happens in the timesheet app, but chances are that it happens on any other custom apps that use legacy widgets too.

A good solution, to avoid supporting those legacy widgets, is to disable the feature on legacy contexts. A better one would be to not remove the files and update them instead.

2023-04-27 13:04 UTC, rven commented
> > I detected an error with the Odoo Enterprise Timesheets application
> 
> It turns out that [Odoo 16 is still using the `web.FilterMenu` legacy widget for the also legacy `web.ControlPanel` widget](https://github.com/odoo/odoo/blob/04d11bf763068dabedc667266e1a6adf0b5db8c0/addons/web/static/src/legacy/js/control_panel/control_panel.js#L8). Also turns out that the timesheets app uses those legacy widgets.
> 
> This PR is removing legacy widget support (which was included for v15). Thus, that app breaks.
> 
> This can be considered a regression, because that support was there in the previous version. Happens in the timesheet app, but chances are that it happens on any other custom apps that use legacy widgets too.
> 
> A good solution, to avoid supporting those legacy widgets, is to disable the feature on legacy contexts. A better one would be to not remove the files and update them instead.

Ok, I didn't know why those files were in there, I'll have a closer look at them

2023-04-27 14:44 UTC, rven commented
Hi @vib-adhoc, I solved the error with the Odoo Enterprise Timesheets application. I also verified it already.

Can you re-test this?

2023-04-27 18:40 UTC, vib-adhoc commented
Hi, @rven it works fine!
Thank you

2023-04-28 06:19 UTC, yajo approved these changes
Tested it on Timesheets too, and elsewhere. Thanks!

/ocabot merge patch

2023-04-28 06:42 UTC, hbrunn commented
I just want to say thank you to everyone involved for how you carried what I once started through all the Odoo versions so far, and making it better on the way :cake:

2023-04-28 08:13 UTC, merged

2023-05-23 00:18 UTC, augusto-weiss commented
Hi everyone!!  I notice an error selecting many2one fields in the Custom filter. 
When select to add a field "is equal to" and adding an extra condition like the first one, the filter disappears!
Whats about that ?? Somebody know??

@rven @chienandalu @pedrobaeza 

https://drive.google.com/file/d/1snJ6Rhxr11JobjKkP9nVXCbELxH5qH--/view

2023-05-23 06:46 UTC, rven commented
@augusto-weiss please check https://github.com/OCA/web/pull/2513 if this is ok for you?

2023-05-23 12:02 UTC, augusto-weiss commented
Hi @rven! Works as expected!! Thanks a lot! i will comment on PR