[ADD] tooltip_menu
OCA/web pull request #2421
Opened 2023-03-01 13:25 UTC by cuongnmtm

Source of the module is here https://apps.odoo.com/apps/modules/13.0/menu_tooltip/ 

I do the migration to 14.0 and add to oca-web.

2023-03-01 13:36 UTC, legalsylvain commented
Hi @cuongnmtm. 
Are you member of  Moltis Technologies ?

2023-03-01 13:44 UTC, cuongnmtm commented
Hi @legalsylvain .
I am not member of Moltis Technologies. Am I able to do this?

2023-03-01 13:48 UTC, legalsylvain requested changes
Hi @cuongnmtm 

Thanks for your answer. I'm not expert, but i think you should have the consentment of the original author.
To contribute to OCA, the author have to sign a CLA, because OCA have then the right to change the licence. So the author should be agree.
could you ask to the company ? 

thanks !

2023-03-02 06:59 UTC, cuongnmtm commented
Hi @legalsylvain 

Thanks for your help. 
I will try to ask for the consentment and sign the CLA of Moltis Technologies.

2023-03-02 12:59 UTC, jcdrubay commented
Thank you @legalsylvain , we will try that.

2023-03-02 13:10 UTC, legalsylvain commented
> Thank you @legalsylvain , we will try that.

Thanks ! 

Note, if accepted, I think the name of the module should be changed. (tooltip_menu -> web_tooltip_menu). 
1) according to the OCA convention
2) that will prevent conflict in appstore.

2023-03-17 01:18 UTC, jcdrubay commented
Hi,

I suspect that Moltis is not active anymore and I did not receive any reply from them. I will try one more time to contact them today.

As a result this might just hang there forever.

I see the next possible next steps:

- We can find evidence  that Moltis is closed, but I am not sure where I could find such evidence. Also, this does not seem to be completely the case as the website is up.
- We close this merge request as we cannot be sure of anything

Let me know if you have any recommendation on how to proceed next.

For reference:

https://moltis.net/
https://www.facebook.com/moltisinc/
https://www.upwork.com/o/companies/~016a04650b65574582/
https://www.linkedin.com/company/moltistech/about/
https://github.com/moltisinc

2025-09-28 12:40 UTC, closed without merging