[ADD] web_model_read_only
OCA/web pull request #2509
Opened 2023-05-19 10:50 UTC by ilyasProgrammer

2023-05-19 13:33 UTC, yostashiro commented
@ilyasProgrammer Not sure your business requirement but could https://github.com/OCA/server-tools/tree/14.0/base_model_restrict_update cover your use case?

2023-05-19 17:08 UTC, francesco-ooops commented
Hi @yostashiro, thanks for the heads up! I'm a functional and I was testing your module, if I understand correctly: 

- you can set one or more models to be edited only by "permitted" users

- "permitted" users can edit all restricted models?

I ask as I tried to test on runbot but couldn't find either "Grant Update Permit" or "Readonly User" in user form.

2023-05-20 04:35 UTC, yostashiro commented
> * you can set one or more models to be edited only by "permitted" users
> * "permitted" users can edit all restricted models?

@francesco-ooops Yes for both.

> I ask as I tried to test on runbot but couldn't find either "Grant Update Permit" or "Readonly User" in user form.

I realize that the button presentation in the user form has been broken and created a PR to fix it here: https://github.com/OCA/server-tools/pull/2626

2023-05-22 13:57 UTC, francesco-ooops commented
Hi @yostashiro , 

your solution works as described but has two limitations IMHO: 

- I cannot allow User A to edit Model 1 but not Model 2, and User B to edit Model 2 but not Model 1

- If I have 10 users allowed to edit Model 1 and I need to restrict one of those users from editing it, I need to set 9 users as "permitted", which is a bit counterintuitive

On the other hand, I like that the flag "read only" sets virtually the whole DB in "guest mode", although the "read only" implemented only restricts user from saving records, but allows for example to browse related objects (eg: read-only user in SO cannot change customer, but can check all customer records)

I think the solution proposed in this module is different enough to allow both modules to be published in OCA :)

2023-06-07 13:58 UTC, francesco-ooops approved these changes
Functional review ok!

2023-06-07 13:58 UTC, francesco-ooops commented
@yostashiro what do you think?

2023-06-12 08:20 UTC, geomer198 reviewed
Please add test coverage for functional.

2023-06-12 08:20 UTC, geomer198 commented on web_model_read_only/models/models.py
> +            model = self.env["ir.model"].search([("model", "=", self._name)])
You could use `_get` function get model record by model name.
For example:
```
self.env['ir.model']._get(self._name)
```

2023-06-13 02:44 UTC, yostashiro commented
@francesco-ooops I see that the design concept of this module is somewhat similar to that of https://github.com/OCA/server-ux/tree/14.0/base_menu_visibility_restriction - normally Odoo makes things more permissive for groups in the upper node, but the design of this module works in the opposite way.  Therefore, I suppose that you are naturally expected to define new groups to be assigned to users and models, specifically for the purpose of access restriction.

I think the function can be useful as long as the usage is properly documented.

I was thinking, however, it may still be good to conflate the proposed function into base_model_restrict_update.  Maybe we can think about it for future versions.

Shouldn't this module be put in https://github.com/OCA/server-tools instead?

2023-06-13 12:22 UTC, geomer198 requested changes
Please add tests for functional.

2023-06-29 21:42 UTC, geomer198 requested changes
Please fix comments.

2023-06-29 21:42 UTC, geomer198 commented on web_model_read_only/tests/test_models.py
> +        cls.ir_model = cls.env["ir.model"].create(
For what you create new model? Could you use existing model for example `res.partner`?

2023-06-29 21:42 UTC, geomer198 commented on web_model_read_only/tests/test_models.py
> +        User = cls.env["res.users"]
Better change naming. For this situation and similar use: `res_users obj`. `obj` suffix used for the showing what variable contain empty model object.

2023-06-29 21:42 UTC, geomer198 commented on web_model_read_only/tests/test_models.py
> +    def test_check_access_rights(self):
Please split this function on the separate cases.
And will make more tests for the coverage all cases.

2023-07-10 13:51 UTC, geomer198 reviewed
For all assertion check need will add message.

2023-07-12 13:35 UTC, francesco-ooops commented
@ilyasProgrammer can you close this one?

2023-07-12 13:36 UTC, closed without merging