[16.0][MIG] web_remember_tree_column_width: Migration to 16.0
OCA/web pull request #2510
Opened 2023-05-19 11:45 UTC by cuongnmtm

2023-05-22 07:57 UTC, kikopeiro approved these changes
:+1:  LGTM (without code review)

2023-05-26 09:46 UTC, quannguyen1560 approved these changes
Functional Review: LGTM (without code review)

2023-05-26 10:00 UTC, CoraVanga approved these changes
LGTM

2023-05-27 05:40 UTC, Leonidas-VII requested changes

2023-05-27 05:40 UTC, Leonidas-VII commented on web_remember_tree_column_width/static/src/js/list_renderer.esm.js
> +        thElements.forEach(function (el, elIndex) {
For this line, we could use the lambda function, we can improve like this

`thElements.forEach((el, elIndex) => {`

Then no need to assign self=this anymore, we can re-use `this`

2023-05-27 05:40 UTC, Leonidas-VII commented on web_remember_tree_column_width/static/src/js/list_renderer.esm.js
> +                    "odoo.columnWidth." + self.props.list.resModel + "." + fieldName
For this line, we can use `template literals` here for more simple

![image](https://github.com/OCA/web/assets/62236456/a2114459-924e-4405-b8fe-f81cd8917c34)

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#syntax

2023-06-02 09:53 UTC, minhthie commented
functional test: lgtm

2023-06-06 15:43 UTC, liebana commented
@cuongnmtm were you able to attend @Leonidas-VII comments?

From my side, functional revision LGTM without those requests

2023-06-07 06:50 UTC, cuongnmtm commented
> @cuongnmtm were you able to attend @Leonidas-VII comments?
> 
> From my side, functional revision LGTM without those requests

@liebana I will attend to those comments this week.
Those suggested changes are for code refactoring which uses new Javascript ES6 features to make the code look better.

2023-06-20 09:58 UTC, dsolanki-initos commented
Hi @cuongnmtm, Could you please adjust your commit as per the OCA guidelines? Refer https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

2023-06-20 10:43 UTC, Leonidas-VII approved these changes
LGTM 😄

2023-07-21 09:35 UTC, StefanRijnhart commented
/ocabot migration web_remember_tree_column_width

2023-07-21 09:44 UTC, StefanRijnhart approved these changes
Thanks! (Code review + functional test)

2023-07-21 10:03 UTC, pedrobaeza commented
/ocabot merge nobump

2023-07-21 10:11 UTC, merged