[16.0][MIG] web_widget_bokeh_chart: Migration to 16.0
OCA/web pull request #2526
Opened 2023-06-06 11:55 UTC by OriolMForgeFlow

2023-06-13 07:25 UTC, hailangvn approved these changes
Functional test ok. Thanks for the work.

2023-06-14 09:59 UTC, LoisRForgeFlow approved these changes
LGTM

2023-06-14 10:00 UTC, LoisRForgeFlow commented
I think I can merge as maintainer of the module, let's see...

/ocabot merge nobump

2023-06-14 10:00 UTC, DavidJForgeFlow approved these changes
LGTM!

2023-06-14 10:02 UTC, LoisRForgeFlow commented
> Sorry @LoisRForgeFlow you are not allowed to merge.
> 
> To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.
> 
> If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

@OCA/web-maintainers I guess, the module maintainer merging rights does not work on migrations. Could someone do the honors? Thanks!

2023-06-14 10:11 UTC, legalsylvain requested changes
> I think I can merge as maintainer of the module, let's see...

https://github.com/OCA/oca-github-bot/issues/226

Hi @OriolMForgeFlow 

Thanks for porting this usefull module.


Quick question : why do you pin the version bokeh ? AFAIK, the lib is stable, so it could be great to install allways the latest supported version. don't you think or do you see a risk  ?

otherwise LGTM.

2023-06-14 13:46 UTC, LoisRForgeFlow commented on web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-3.1.1.min.js
@legalsylvain because the pip package need to match the JS assets being added with this module

2023-06-14 14:05 UTC, legalsylvain commented on web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-3.1.1.min.js
oh ! you're right. Thanks.

2023-06-14 14:05 UTC, legalsylvain approved these changes
/ocabot merge patch

2023-06-14 14:12 UTC, merged