[16.0][MIG] web_ir_actions_act_window_page
OCA/web pull request #2548
Opened 2023-06-28 19:57 UTC by hbrunn

This addon allows a developer to return the following action types:

`{'type': 'ir.actions.act_window.page.next'}`

or:

`{'type': 'ir.actions.act_window.page.prev'}`

which trigger the form's controller to page into the requested direction on the client
side.

A use case could be the case of a validation flow. As a developer, you set up a tree
view with a domain on records to be validated. The user opens the first record in a form
view and validates the record. The validation method returns the 'next' action type so
that the browser window of the user is presented with the next record in the form view.

2023-07-11 07:53 UTC, tarteo approved these changes
Thanks! Tested locally works perfectly

![image](https://github.com/OCA/web/assets/10028499/7bd36528-23a3-4040-923a-1dc3848f4d6f)

2023-07-21 09:54 UTC, StefanRijnhart commented
/ocabot migration web_ir_actions_act_window_page

2023-07-21 09:56 UTC, StefanRijnhart commented
Please mention the version number in your migration commits.
![image](https://github.com/OCA/web/assets/1033124/d6fa9966-4c5d-4358-994c-a20b36d1677a)

2023-07-21 09:58 UTC, StefanRijnhart commented on web_ir_actions_act_window_page/__init__.py
> -#    This module copyright (C) 2013 Therp BV (<http://therp.nl>).
Maybe keep the original credits?

2023-07-21 10:02 UTC, StefanRijnhart commented on web_ir_actions_act_window_page/__init__.py
> -#    This module copyright (C) 2013 Therp BV (<http://therp.nl>).
Oh I do still see them elsewhere, so that's OK.

2023-07-21 10:03 UTC, StefanRijnhart requested changes
This is beautifully adapted to the new upstream code. The use of the bus is revealing.
Please fix the commit messages.

2023-07-21 13:08 UTC, ged-odoo commented on web_ir_actions_act_window_page/static/src/web_ir_actions_act_window_page.esm.js
> +        const handleNavigate = (ev) => this._handleNavigate(ev);
random unsolicited code review. I hope it's not rude. You can import `useBus` from `"@web/core/utils/hooks"`. It allow you to register when mounted and it will take care of unregistering when unmounted:
```js
  useBus(this.env.bus, "pager:navigate", handleNavigate);
```

2023-07-31 09:23 UTC, hbrunn commented on web_ir_actions_act_window_page/static/src/web_ir_actions_act_window_page.esm.js
> +        const handleNavigate = (ev) => this._handleNavigate(ev);
on the contrary, very much appreciated and sorry for the long delay! Took your suggestion in 3a0e116feac

2023-07-31 18:46 UTC, StefanRijnhart approved these changes

2023-08-08 07:58 UTC, StefanRijnhart commented
/ocabot merge nobump

2023-08-08 08:05 UTC, merged