[16.0][MIG] web_m2x_options_manager : Migrate to 16.0
OCA/web pull request #2587
Opened 2023-08-11 05:02 UTC by QuocDuong1306

This PR takes over:
- https://github.com/OCA/web/pull/2448

2023-08-11 05:41 UTC, pedrobaeza commented
/ocabot migration web_m2x_options_manager

2023-08-23 11:38 UTC, Kinyuaeric commented on web_m2x_options_manager/models/ir_model.py
> +    @api.model
@QuocDuong1306 kindly check this function .it has completely changed in odoo v16.

2023-08-23 11:39 UTC, Kinyuaeric reviewed
check the  last function on file ir_model.py  

def name_serch.....it has changed in  odoo v16

2023-09-04 05:50 UTC, QuocDuong1306 commented
Thanks for your reviews, I updated

2023-09-25 09:52 UTC, sebalix approved these changes

2023-09-25 10:49 UTC, ajaniszewska-dev approved these changes

2023-12-18 11:31 UTC, moitabenfdz commented
Can you check if the "Create & Edit Wizard" is working? I don't see any difference when is True and when is False.

2024-04-15 11:02 UTC, dreispt commented
/ocabot merge nobump

2024-05-06 07:54 UTC, danielduqma commented
@QuocDuong1306 could you please fix [pre-commit issues](https://github.com/OCA/web/actions/runs/8688022732/job/23822755913)? Thanks!

2024-05-06 10:41 UTC, viviana1503 requested changes
Currently, the module is not achieving its primary goal of properly managing the options for creation and editing/creation. I have made specific configurations in the res.partner and sale.order models to eliminate the options of "Create" and "Edit/Create".
In the attached video, it can be observed that for the sale.order model, I have configured the "Force remove" option for the partner_id and tag_ids fields. These configurations were applied correctly, preventing the possibility of "Create" and "Edit and Create".
However, when dealing with the res.partner model, I used the same "Force remove" configuration for the team_id and user_id fields. Unfortunately, while this configuration works for team_id, it does not effectively transfer to the user_id field, meaning that editing and creation in this field are still allowed.

https://github.com/OCA/web/assets/159796631/9663dcfc-007a-4c25-b371-03d35eafffd0

2024-07-11 15:48 UTC, aliciagaarzo commented
@QuocDuong1306 After reviewing the previous comment in the PR where the error is located, will changes be added to continue the migration?

2024-07-15 01:05 UTC, QuocDuong1306 commented
Hi, sorry for the delay, I will update the PR asap

2024-08-06 07:06 UTC, QuocDuong1306 commented
Hello guys, the PR is updated

2024-08-06 07:22 UTC, QuocDuong1306 commented
>However, when dealing with the res.partner model, I used the same "Force remove" configuration for the team_id and user_id fields. Unfortunately, while this configuration works for team_id, it does not effectively transfer to the user_id field, meaning that editing and creation in this field are still allowed.

Hello @aliciagaarzo , the issue is fixed, could you have a look?

[Screencast from 2024-08-06 14-18-37.webm](https://github.com/user-attachments/assets/9ec31b9e-b98c-4bb3-a51b-97aff47ef561)

2024-08-26 09:19 UTC, acsonefho approved these changes

2024-08-26 09:21 UTC, aliciagaarzo approved these changes
LGTM!!

2024-11-13 14:31 UTC, kikopeiro approved these changes
LGTM, thanks @QuocDuong1306  

I have validated the functionality, and everything seems to be working as expected

Could it be merged??? CC @pedrobaeza 
:+1:

2024-11-13 15:56 UTC, pedrobaeza commented
Trusting in reviewers

/ocabot merge nobump

2024-11-13 16:04 UTC, merged