[FIX] web_advanced_search: Fixed changes from code editor not propagated
OCA/web pull request #2625
Opened 2023-09-27 12:25 UTC by coffeinisfun

Fix for changes from code editor not propagated to upper section

![web_advanced_search_fix](https://github.com/OCA/web/assets/86827803/52511db4-9290-4f1f-b291-e334baf5f011)

2023-09-27 13:25 UTC, chienandalu reviewed
This indeed seems to be a deliberate change: https://github.com/odoo/odoo/pull/79855

Anyway, I'd target a patch to Odoo.

I just tested removing this `debug` flag that is passed to the `domain_changed` custom event and everything works flawlessly: https://github.com/odoo/odoo/blob/540dcc714acacc57bd3e971c758eb7d29941398d/addons/web/static/src/legacy/js/widgets/domain_selector.js#L604

My guess would be that the cause for the original patch maybe no longer applies. Indeed this functionality is recoverd in the new search tool for v17 that hopefully will deprecate this OCA module :)

2023-10-10 15:26 UTC, chienandalu requested changes
Hi, @coffeinisfun I made a little research myself and got to the conclussion that your solution is quite aimed. Some suggestions to improve it

2023-10-10 15:26 UTC, chienandalu commented on web_advanced_search/static/src/js/DomainSelector.esm.js
> +    },
I'd limit this override to the case we're on the advanced search dialog:
```suggestion
    /**
     * Our event is losing itself on our custom dialog. Just trigger the redraw
     * immediately
     * @override
     */
    _onDebugInputChange (e) {
        if (!$(".o_add_advanced_search").length) {
            return this._super(...arguments);
        }
        const rawDomain = e.currentTarget.value;
        try {
            Domain.prototype.stringToArray(rawDomain);
        } catch (err) { // If there is a syntax error, just ignore the change
            this.displayNotification({ title: _t("Syntax error"), message: _t("Domain not properly formed"), type: 'danger' });
            return;
        }
        this._redraw(Domain.prototype.stringToArray(rawDomain)).then(
            function () {
                this.trigger_up("domain_changed", {
                    child: this,
                    alreadyRedrawn: true,
                });
            }.bind(this)
        );
    },
```

2023-10-10 15:26 UTC, chienandalu commented on web_advanced_search/static/src/js/DomainSelector.esm.js
We can include this patch as well so the domain also re-renders when the field widget is being used in a form field

```js
patch(FieldDomain.prototype, "web.basic_fields", {
    /**
     * Odoo restricts re-rendering the domain from the debug editor for supposedly
     * performance reasons. We didn't ever came up with those and in v17 it's supported
     * in the new advanced search.
     * @override
     */
    _onDomainSelectorValueChange(event) {
        this._super(...arguments);
        // Deactivate all debug conditions that cripple the functionality
        this.debugEdition = false;
    },
});
```

2023-10-11 08:57 UTC, coffeinisfun commented
> Hi, @coffeinisfun I made a little research myself and got to the conclussion that your solution is quite aimed. Some suggestions to improve it

thanks for the suggestion! Seems to be a more elegant solution. I just adjusted it

2023-10-11 09:06 UTC, chienandalu commented on web_advanced_search/static/src/js/DomainSelector.esm.js
Can you include this as well so it's usable in forms as well?

2023-10-12 09:29 UTC, coffeinisfun commented on web_advanced_search/static/src/js/DomainSelector.esm.js
> Can you include this as well so it's usable in forms as well?

Done

2023-10-19 08:47 UTC, chienandalu approved these changes
Thanks!

2023-10-19 08:51 UTC, CarlosRoca13 approved these changes
Thx :)

2023-10-19 08:51 UTC, pedrobaeza approved these changes
/ocabot merge patch

2023-10-19 08:58 UTC, merged

2023-10-19 09:00 UTC, chienandalu commented
@coffeinisfun Will you forward it to v16?