[7.0-Backported] web tree date search
OCA/web pull request #264
Opened 2015-11-25 11:21 UTC by fossoult

2015-11-25 12:10 UTC, elicoidal commented on web_tree_date_search/README.rst
> +==============================
Hi @fossoult  thanks for your contribution
I will check mostly format and guidelines in your PR
Can you remove extra underline and adjust with sentence length?

2015-11-25 12:11 UTC, elicoidal commented on web_tree_date_search/README.rst
> +This module allow you to easily add dates range search fields on top of List View rows.
s/allow/allows
s/on top of List View rows./on top of the tree view.

2015-11-25 12:12 UTC, elicoidal commented on web_tree_date_search/README.rst
> +How to do ?
usage
=====

2015-11-25 12:12 UTC, elicoidal commented on web_tree_date_search/README.rst
> +How to do ?
Add:
This module requires developer skills to be used.

2015-11-25 12:13 UTC, elicoidal commented on web_tree_date_search/README.rst
> +Credits
I miss
* the bug tracker section
* Try me on Runbot section

2015-11-25 12:13 UTC, elicoidal commented on web_tree_date_search/README.rst
> +   :target: http://odoo-community.org
https

2015-11-25 12:13 UTC, elicoidal commented on web_tree_date_search/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
https

2015-11-25 12:13 UTC, elicoidal commented on web_tree_date_search/__init__.py
> +##############################################################################
Please use simple headers following OCA templates
https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3

2015-11-26 09:10 UTC, fossoult commented
@elicoidal  Should I remove the line 33 to pass the test ?

.. image:: https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas
   :alt: Try me on Runbot
   :target: https://runbot.odoo-community.org/runbot/162/7.0

2015-11-26 09:38 UTC, elicoidal commented
cc @pedrobaeza

2015-11-26 09:44 UTC, fossoult commented
I can update with " # noqa: skip 79 char because I can't change the URL"

2016-04-04 10:13 UTC, fossoult commented
Can you merge it plz ?

2016-04-06 18:29 UTC, hbrunn commented
@fossoult when backporting stuff, pick the original commits as explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8.0#how with the necessary changes

2016-11-16 09:08 UTC, rousseldenis requested changes
code review. Minor comment

2016-11-16 09:08 UTC, rousseldenis commented on web_tree_date_search/__openerp__.py
> +        'static/src/xml/*.xml',
@fossoult Please name your file(s). Not very safe

2016-11-16 09:17 UTC, rousseldenis reviewed
@fossoult Have you done all modifications requested by @elicoidal and @hbrunn ?

2016-11-24 11:55 UTC, rousseldenis reviewed
@tfossoulw Can you check lint errors in javascript and solve them?

2016-11-25 08:16 UTC, gurneyalex commented
Hello @fossoult 

I'm having issues on runbot with this PR. Would you mind making a new commit and pushing

2016-11-25 12:51 UTC, fossoult commented
@gurneyalex I relaunch the runbot and it run without any problems. Can you tell me what you saw ?

2016-11-25 14:04 UTC, rousseldenis approved these changes
:+1: Seems ok. Flake8 error generated by web_warning_on_save module

2016-11-28 08:23 UTC, gurneyalex commented
ok then I consider this part of the docker migration of runbot solved. Thanks for you patience @fossoult

2021-11-07 12:29 UTC, closed without merging