[IMP] web_remember_tree_column_width: adjust SCSS selector
OCA/web pull request #2720
Opened 2024-01-12 12:46 UTC by cuongnmtm

Previously, only columns with the class o_column_sortable had the custom SCSS applied to them. As a result, columns like HTML were not sortable and didn't benefit from the custom SCSS.

This pull request made changes to the SCSS selector to include all table columns in the list view. However, the record selector (the first checkbox column) and column optional (the last column) that have the class o_list_controller were excluded.

Related issue: https://github.com/OCA/web/issues/2717

2024-01-23 07:37 UTC, AurelijaNorvaisaite commented
@cuongnmtm It works!

2024-01-29 08:10 UTC, AurelijaNorvaisaite approved these changes

2024-05-08 07:19 UTC, paulius-sladkevicius commented
Hello @pedrobaeza, could you help with an extra review and possible merge?

2024-05-08 07:20 UTC, pedrobaeza commented
Sorry, I don't use this module.

2024-05-08 07:22 UTC, paulius-sladkevicius commented
Guys @luisg123v, @frahikLV , can you check it out?

2024-05-08 17:16 UTC, luisg123v requested changes
Regarding code: LGTM

Regarding commit message:
- Lines are too long, they should be split to 72 characters
- It says "this pull request", but it's a commit.

2024-05-09 05:30 UTC, cuongnmtm commented
I updated the commit message, thanks @luisg123v .

2024-05-09 16:27 UTC, luisg123v approved these changes
LGTM :+1:

2024-05-09 16:27 UTC, luisg123v commented
/ocabot merge patch

2024-05-09 16:31 UTC, merged