[15.0][MIG] web_widget_mermaid
OCA/web pull request #2763
Opened 2024-03-09 15:18 UTC by dreispt

- [ADD] web_widget_mermaid from v12.0
- [IMP] Add assets
- [REM] Remove web_widget_mermaid_view.xml
- [FIX] ESLint messages
- [IMP] Add themeVariables to defaultConfig
- [REM] Remove web_widget_mermaid_default_theme.scss
- [FIX] pre-commit issues (prettier)
- [UPD] Readme fragments

2024-03-09 15:21 UTC, dreispt commented
/ocabot merge nobump

2024-03-09 15:44 UTC, dreispt commented
/ocabot merge nobump

2024-05-16 05:46 UTC, bofiltd approved these changes

2024-05-16 08:08 UTC, dreispt commented
/ocabot merge nobump

2024-05-26 10:03 UTC, idamonli commented
@dreispt Do you have plans to migrate this module to version 16.0?

2024-05-27 13:13 UTC, bosd commented
Would like to test this, but runboat is not available :(

2025-07-18 09:04 UTC, hbrunn commented
/ocabot rebase

2025-08-09 13:17 UTC, bosd requested changes
This does not seem to be working:
<img width="1969" height="1006" alt="image" src="https://github.com/user-attachments/assets/94314918-d85b-4e31-9dc4-0c23ae9b98ab" />

<img width="1969" height="1006" alt="image" src="https://github.com/user-attachments/assets/147e1dad-aaee-4f76-b898-e94c6cc5cde4" />

2026-05-24 13:45 UTC, closed without merging