17.0 mig web dialog size
OCA/web pull request #2769
Opened 2024-03-14 12:03 UTC by jethavadakshal

- Migrated web dialog size module.
- Removed LegacyComponent as it's deprecated on version 17 and used component instead.
- Created json controller to get the value of web_dialog_size.default_maximize from system parameters.
- Removed additional argument from dialog patch.

2024-03-14 13:07 UTC, pedrobaeza commented
/ocabot migration web_dialog_size

Please take car about the PR title for being proper, or it won't appear on searches over the module name.

2024-03-14 13:25 UTC, jethavadakshal commented
Hello @pedrobaeza ,
Thanks for your quick response on this PR.
can you please guide me as to why the last 2 checks failed?
Also is there anything missing in this module or is it not properly migrated?

2024-03-14 14:42 UTC, pedrobaeza commented
Don't worry about the codecov thing. It's just a quality measure about the test coverage. It's not mandatory to comply with it.

Now the PR should be reviewed by people, as stated in https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md

2024-03-14 14:59 UTC, jethavadakshal commented
Thanks, @pedrobaeza
The document you provided is really helpful.
From now onward I will take care of the things which are written in documentation while contributing to OCA.

2024-07-29 12:18 UTC, CarlosRoca13 requested changes
Hi @jethavadakshal! 

First of all thanks for the work, but it's important to follow the steps defined on https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0 because you have to preserve the commit history.

Please, force push the changes by following this steps :smile:

2024-07-31 09:29 UTC, jethavadakshal commented
Hello @CarlosRoca13,
i have checked the doc shared by you.
and I tried my best to perform the steps.
can you please check and if it's incorrect please guide me on this.
Thanks

2024-07-31 10:04 UTC, CarlosRoca13 commented
The steps are:

```
$ git clone https://github.com/OCA/$repo -b 17.0
$ cd $repo
$ git checkout -b 17.0-mig-$module origin/17.0
$ git format-patch --keep-subject --stdout origin/17.0..origin/16.0 -- $module | git am -3 --keep
$ pre-commit run -a  # to run pre-commit linters and formatters (please ignore pylint errors at this stage)
$ git add -A
$ git commit -m "[IMP] $module: pre-commit auto fixes"  --no-verify  # it is important to do all the formatting in one commit the first time
```
Then apply your changes and finally commit your changes to force push to this branch. :smile: The importance of doing this is to ensure that the work done by other contributors is not forgotten.

2024-07-31 10:07 UTC, CarlosRoca13 commented
And please avoid multiples commits for the migration process to avoid noice, your commits on the migration should be 2:
 - `[IMP] $module: pre-commit auto fixes`
 - `[MIG] $module: Migration to 17.0`

2024-08-16 11:05 UTC, pedrobaeza commented
Superseded by #2919

2024-08-16 11:05 UTC, closed without merging