[17.0][MIG] web_m2x_options: Migration to 17.0
OCA/web pull request #2772
Opened 2024-03-15 10:50 UTC by Ammar-OSI

2024-03-15 14:57 UTC, pedrobaeza commented on web_m2x_options/static/src/components/base.xml
> +    <!-- <t
You can't comment a part of the code.

2024-03-25 10:31 UTC, mostafabarmshory commented
@Ammar-OSI 

Could you fix this issue?

2024-03-25 11:00 UTC, Sanazzzmi commented
I also need this module. Please complete it as soon as possible. Thank you

2024-03-27 13:46 UTC, CRogos requested changes
Could you also adapt the commits (rename/squash) according to the migration guide.

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

Some samples:
![image](https://github.com/OCA/web/assets/1799080/72c5dcd2-3da9-439d-987b-5e72bb13fc27)

2024-03-28 14:41 UTC, CasVissers-360ERP commented
@Ammar-OSI are you going to continue here?

2024-03-29 07:25 UTC, mostafabarmshory commented
> @Ammar-OSI are you going to continue here?

Dear @CasVissers-360ERP 

He does not reply here.

I`m ready to create a new PR and follow the MIG.

2024-04-01 09:19 UTC, Ammar-OSI commented
Hello Team , 

Yes I am working on this module we will update you in a 2 days

2024-04-02 10:35 UTC, mostafabarmshory commented
@Ammar-OSI 

I launch and use it with odoo community 17. It faces many problems. 

The main issue is that some fields (such as the sale order line field) are inherited from the relation field primarily. 

However, the props schema does not contain items such as searchMore.

Would you test the module side by side with the following ones:

- Sale
- Project

tx

2024-04-09 08:06 UTC, mostafabarmshory commented
> Yes I am working on this module I will update you i

@Ammar-OSI  did you finish this one?

2024-04-09 11:05 UTC, Ammar-OSI commented
> @Ammar-OSI
> 
> I launch and use it with odoo community 17. It faces many problems.
> 
> The main issue is that some fields (such as the sale order line field) are inherited from the relation field primarily.
> 
> However, the props schema does not contain items such as searchMore.
> 
> Would you test the module side by side with the following ones:
> 
> * Sale
> * Project
> 
> tx

Yes @mostafabarmshory , 

I currently stuck on that issue and currently working on that issue, 

for this which is not module working on debug mode. 

That's i also face dealy on push a code.

2024-04-09 16:43 UTC, mostafabarmshory commented
> > @Ammar-OSI
> > I launch and use it with odoo community 17. It faces many problems.
> > The main issue is that some fields (such as the sale order line field) are inherited from the relation field primarily.
> > However, the props schema does not contain items such as searchMore.
> > Would you test the module side by side with the following ones:
> > 
> > * Sale
> > * Project
> > 
> > tx
> 
> Yes @mostafabarmshory ,
> 
> I currently stuck on that issue and currently working on that issue,
> 
> for this which is not module working on debug mode.
> 
> That's i also face dealy on push a code.

@Ammar-OSI tx

Hope you find a way. 

I try to find a way and test more. I feedback you.

2024-04-23 04:55 UTC, mostafabarmshory reviewed
This is a basic problem and adding properties into sub-classes is not a good idea.

2024-04-23 04:55 UTC, mostafabarmshory commented on web_m2x_options/static/src/components/form.esm.js
> +SaleOrderLineProductField.props = {
There are many other classes which extend from Many2OneField (ex. ProjectMany2OneField). All of them face with such issue. 
Bad idea to patch them in a base module (a dependency required).

We have to look for a better idea.

2024-04-23 04:55 UTC, mostafabarmshory commented on web_m2x_options/static/src/components/form.esm.js
> +import { SaleOrderLineProductField } from '@sale/js/sale_product_field';
This add-on is not depended on odoo/sale. So this component may not exist at runtime.

2024-04-23 04:55 UTC, mostafabarmshory commented on web_m2x_options/static/src/components/relational_utils.esm.js
> +        console.log("this.ir_options: ",this.ir_options);
Do not add console.log

Please use developer tools and debugger instead.

2024-04-24 09:42 UTC, manuelregidor requested changes

2024-04-24 09:42 UTC, manuelregidor commented on web_m2x_options/static/src/components/relational_utils.esm.js
> +        if (this.props.nodeOptions.search_more !== "undefined") {
Should undefined be without quotes?

2024-04-24 09:42 UTC, manuelregidor commented on web_m2x_options/static/src/components/relational_utils.esm.js
> +        } else if (this.ir_options["web_m2x_options.search_more"] !== "undefined") {
Should undefined be without quotes?

2024-04-24 10:40 UTC, manuelregidor reviewed
Have you thought of calling super loadOptionsSource function and then remove the elements that should not be applied?
Super loadOptionsSource could be called in line 23 in relational_utils.esm.js file. Then lines 118-137 could be replace by the following code:

```
        if (!(
            create_enabled &&
            !this.props.nodeOptions.no_quick_create &&
            request.length > 0 &&
            !raw_result.includes(request) &&
            show_create
        )) {
                        options.splice(options.findIndex(e => e.classList === "o_m2o_dropdown_option o_m2o_dropdown_option_create"),1);

        }
```

This way, the function would not be completely overidden plus only those elements that are necessary would be added. For example, the "Start typing..." element would be already added by the super function.

2024-05-30 09:22 UTC, jeroenev commented
seems multiple dependencies are missing, partner_autocomplete, mail, sale etc...
Also should be made to work if partner_autocomplete or sale are not installed

2024-06-10 08:11 UTC, cle-enovea commented
Any updates on this PR ?

2024-06-25 10:04 UTC, pedrobaeza commented
Superseded by #2847, as this one is not completed.

2024-06-25 10:04 UTC, closed without merging