[17.0] [MIG] web_ir_actions_act_window_message: Migration to 17.0
OCA/web pull request #2812
Opened 2024-04-25 14:16 UTC by bizzappdev

2024-05-20 12:51 UTC, JasminSForgeFlow approved these changes

2024-07-15 11:49 UTC, ferran-S73 approved these changes
Functional review

2025-01-28 14:25 UTC, zamberjo approved these changes

2025-03-05 09:18 UTC, MateuGForgeFlow approved these changes

2025-07-18 06:51 UTC, hbrunn requested changes
please also consider adding a server action in demo data showing off all features - this makes reviewing/testing things much easier

2025-07-18 06:51 UTC, hbrunn commented on web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_msg_component.esm.js
> +        for (var i = 0; i < action.buttons.length; i++) {
```suggestion
        for (var i = 0; action.buttons && i < action.buttons.length; i++) {
```

otherwise this fails if there are no buttons in the action dictionary

2025-07-18 06:51 UTC, hbrunn commented on web_ir_actions_act_window_message/static/src/xml/web_ir_actions_act_window_message.xml
> +                <t t-esc="props.body" />
```suggestion
                <t t-out="props.body" />
```

2025-07-18 06:51 UTC, hbrunn commented on web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_message.esm.js
> +import {ActWindowMessageDialog} from "./web_ir_actions_act_window_msg_component.esm";
```suggestion
import {ActWindowMessageDialog} from "./web_ir_actions_act_window_msg_component.esm";
import {markup} from "@odoo/owl";
```

2025-07-18 06:51 UTC, hbrunn commented on web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_message.esm.js
> +        body: action.message,
```suggestion
        action.is_html_message ? markup(action.message) : action.message,
```

you need to explicitly mark html as safe by now to avoid escaping

2026-08-16 12:47 UTC, closed without merging