[17.0][MIG] web_company_color: Migration to 17.0
OCA/web pull request #2813
Opened 2024-04-26 10:35 UTC by peluko00

2024-07-05 17:41 UTC, NL66278 commented
I tested it, but setting company colors does not have any effect on the UI. I noted the same on Odoo 16.0 (even though filling all company colors to avoid the bug on 16.0). This did work before. Apparently something changed in core, both in 16.0 and 17.0, that makes the module ineffective. Unfortunately I am not well versed in either scss or bootstrap to find the cause myself, without a lot of time that I currently do not have.

2024-07-31 09:24 UTC, CarlosRoca13 commented
I have added a fix to the problem mentioned in this PR, please note it for when merging to cherry-pick the commit.

https://github.com/OCA/web/pull/2902

2024-11-29 16:58 UTC, micheledic commented
Hello,
the module is not working.
Instead of compiling the file, the file is printed on the HTML

2024-12-11 12:35 UTC, LoisRForgeFlow requested changes
Functional test in local, it does not work:

![Uploading image.png…]()

2025-02-14 07:59 UTC, PieterPaulussen commented
I believe this PR can be closed because this has been merged: https://github.com/OCA/web/pull/3025

2025-02-14 07:59 UTC, closed without merging