[16.0] [IMP] web_responsive showing main menu when no application is selected
OCA/web pull request #2816
Opened 2024-05-06 12:45 UTC by eLBati

2024-05-07 11:48 UTC, Tardo commented
Code OK. But idk how to "solve" the tests...

2024-05-07 11:48 UTC, Tardo approved these changes

2024-05-08 14:58 UTC, Jaimermaccione approved these changes
LGTM! Functional review on runboat

2024-05-08 21:29 UTC, pedrobaeza requested changes
This must be something optional.

2024-05-24 14:42 UTC, eLBati commented
Hi @pedrobaeza , what problem do you see in setting [this](https://github.com/OCA/web/pull/2816#issue-2280800222) as default behavior o the module?
Thanks!

2024-05-25 08:52 UTC, pedrobaeza commented
For several reasons:

- It's not what users are used to.
- A lot of users have an initial action set. How does this combine with that?
- There are modules like https://github.com/OCA/server-ux/tree/16.0/announcement that shows popups on login that will conflict.

If you assure that there are no problems with points 2 and 3, then 1 can be ignored.

2024-10-24 09:50 UTC, primes2h commented
Thanks @eLBati. 
Whether it is optional or not, I consider this a must have feature.

2024-10-25 08:45 UTC, primes2h commented
> 
>     * A lot of users have an initial action set. How does this combine with that?

It works well with home action.

![home_action](https://github.com/user-attachments/assets/d63e697d-7866-4624-b93b-2227011ac346)



> 
>     * There are modules like https://github.com/OCA/server-ux/tree/16.0/announcement that shows popups on login that will conflict.

It works well with announcements too.

![announcements](https://github.com/user-attachments/assets/fa6f651e-b6af-471d-b613-4e536fc4e112)

2024-10-25 08:47 UTC, primes2h commented
@eLBati 

I would hide the top left button after login.

![web_responsive](https://github.com/user-attachments/assets/89cecc20-8202-48fc-bc7f-1a8a7f092814)

2026-08-16 12:47 UTC, closed without merging