[16.0][ADD] web_calendar_slot_duration_by_user
OCA/web pull request #2819
Opened 2024-05-10 15:43 UTC by imlopes

2024-05-24 13:44 UTC, imlopes commented
@yajo 

Can you check this PR too ?
Here my objective is to add a slot duration by user.

Context :

In some cases, an employee will plan by default meets each hour. But another employee (in another department) will plan his meets each 30min.

2024-06-05 12:00 UTC, yajo requested changes

2024-06-05 12:00 UTC, yajo commented on web_calendar_slot_duration_by_user/models/res_users.py
> +    )
I think you can just set a default slot duration for everybody and remove the boolean field.

Also the duration should be IMHO a `Float` using the `float_time` widget for better UI consistency.

2024-06-05 12:00 UTC, yajo commented on web_calendar_slot_duration_by_user/views/res_users.xml
> +                        help="Duration of the default duration for the calendar view in the format HH:MM:SS"
Add help directly in the model.

2024-11-01 12:47 UTC, imlopes commented
@yajo this one too, can you check ?
Thanks

2024-11-04 10:18 UTC, yajo requested changes

2024-11-04 10:18 UTC, yajo commented on web_calendar_slot_duration_by_user/models/res_users.py
> +        default="1",
issue: if field is float, default value should be float/int:

```suggestion
        default=1.0,
```

2026-08-16 12:47 UTC, closed without merging