[17.0][MIG] web_chatter_position: Migration to 17.0
OCA/web pull request #2833
Opened 2024-05-23 06:22 UTC by Jp-alitec

Migrated to V17.

2024-05-23 09:24 UTC, Jp-alitec commented
hey @legalsylvain i have closed the previous PR and created this new one following every guideline , can you please review?

2024-05-24 08:59 UTC, Rad0van commented
This does not work at all for me. It breaks My Preferences dialog completely and I have a feeling it breaks other dialogs as well. Teste on fresh clean 17.0
![image](https://github.com/OCA/web/assets/19169467/2b6b50d2-d503-4462-9e7e-00dff3605366)

2024-05-24 09:52 UTC, Jp-alitec commented
@Rad0van Oh ! its because of the optional chaining 

if (child.attributes?.name?.value !== "button_box") {
    append(form, this.compileNode(child, params));
}
I have fixed this and code is working as expected but , the optional chaining is not accepted by pre-commit !! it fails , ehat should i do to fix that ?

2024-05-24 12:20 UTC, MihranThalhath requested changes

2024-05-24 12:20 UTC, MihranThalhath commented on pandoc-3.2-1-amd64.deb
Please remove this

2024-05-24 12:24 UTC, Jp-alitec commented on pandoc-3.2-1-amd64.deb
@MihranThalhath Sorry but what ?

2024-05-24 12:26 UTC, MihranThalhath commented on pandoc-3.2-1-amd64.deb
@Jp-alitec pandoc deb file

2024-05-24 12:32 UTC, Jp-alitec commented on pandoc-3.2-1-amd64.deb
@MihranThalhath Removed it !

2024-05-24 12:46 UTC, pedrobaeza commented on pandoc-3.2-1-amd64.deb
And both commits should be squashed together, or there will be 60 MB of diff

2024-05-24 12:52 UTC, MihranThalhath commented
![image](https://github.com/OCA/web/assets/22158587/72bb9839-aa41-40ea-bbce-c9d2ebf6e5c7)
checked on runboat and this is how it looks on invoice view

2024-05-24 12:56 UTC, Jp-alitec commented on pandoc-3.2-1-amd64.deb
@pedrobaeza Sqashed / rebase everything according to guidelines

2024-05-24 12:57 UTC, pedrobaeza commented on pandoc-3.2-1-amd64.deb
The binary file is still here.

2024-05-24 13:00 UTC, Jp-alitec commented on pandoc-3.2-1-amd64.deb
@pedrobaeza Where , sorry its not visible to me !

2024-05-24 13:03 UTC, pedrobaeza commented on pandoc-3.2-1-amd64.deb
![imagen](https://github.com/OCA/web/assets/7165771/eeb0ffa7-3b2f-4ca1-a232-7cf675f90d79)

Now to fix it you need to undo the removal in this commit, put it on a separate one, and then squash with the previous commit (pre-commit auto-fixes)

2024-06-01 01:43 UTC, duyquyen96 commented
@Jp-alitec PR https://github.com/OCA/web/pull/2795#issue-2242298187 Does this have any effect on PR?

2024-06-05 16:59 UTC, ryantran-novobi requested changes
This pull request works great on my end, even with Web Responsive and Odoo Enterprise.

I suggested a few changes just to have the layout better represented on a big monitor.

2024-06-05 16:59 UTC, ryantran-novobi commented on web_chatter_position/static/src/scss/form_controller.scss
> +}
```suggestion
.o_form_view {
    .o_form_renderer {
        max-width: none;
    }
    .o_form_sheet_bg {
        max-width: none;

        .o_form_statusbar {
            max-width: $o-form-view-sheet-max-width;
            width: 100%;
            margin: 0px auto;
        }
    }
    .o_form_sheet {
        max-width: $o-form-view-sheet-max-width;
        width: 100%;
        @include media-breakpoint-up(md) {
            margin: $o-sheet-vpadding * 0.2 auto;
        };
        @include media-breakpoint-down(sm) {
            width: unset !important;
        }
    }
}
```

2024-06-05 17:00 UTC, ryantran-novobi commented on web_chatter_position/static/src/scss/form_controller.scss
> +}
☝️ @Jp-alitec

2024-06-17 05:44 UTC, dustinhoanghavi commented
@Jp-alitec In the Invoice view form, I see duplicate chatter, can you fix it? It could be even better. Thank you!
![image](https://github.com/OCA/web/assets/143161607/316cc4a0-4c78-49f5-a8bc-9f141bb6bf89)

2024-06-27 08:36 UTC, tva-subteno-it commented
Hi, I tried this module for myself because one my client needs it. It works really well on my end, with no bug. You only have the pre-commit formatting left to do.
What is the stage of progress of this PR?

2024-07-17 14:08 UTC, icf20 commented
> @Jp-alitec  I see duplicate chatter, can you fix it? 

confirmed

2024-07-21 09:49 UTC, trisdoan commented
> > @Jp-alitec  I see duplicate chatter, can you fix it?
> 
> confirmed

Hi @ryantran-novobi, I am working on fixing the duplicate issue and want to include your suggestion. As I tried, I saw no effect on the form view. Could you please elaborate (nicer with images)?

2024-07-25 02:19 UTC, trisdoan commented
> > > @Jp-alitec  I see duplicate chatter, can you fix it?
> > 
> > 
> > confirmed
> 
> Hi @ryantran-novobi, I am working on fixing the duplicate issue and want to include your suggestion. As I tried, I saw no effect on the form view. Could you please elaborate (nicer with images)?

Hello everyone, I fixed the issue and prepared this https://github.com/OCA/web/pull/2893

Please help to review

2024-10-17 10:31 UTC, BialArno commented
mhm, oficially OCA module hasn't been migrated, but based on OCA module someone has already published their own version, that seems to work in 17.0 (tho not a single word regarding the usage of OCA module, tho code is 1:1 besides minor changes to form compiler).

2024-10-17 10:38 UTC, CRogos requested changes
be carefull... the *.deb file is still in the commit history and should be removed from the first commit. Everything in the history will blowup the repository size.

![image](https://github.com/user-attachments/assets/159ac01c-16dd-45c2-b02c-59282c86ccda)

![image](https://github.com/user-attachments/assets/38162f86-375a-40c6-a181-41a17de4dd9c)

2024-10-23 15:51 UTC, BT-aleonard commented
What's the status of removing the deb from the commit? @Jp-alitec

2024-12-03 10:53 UTC, yajo commented
Superseded by https://github.com/OCA/web/pull/2893.

2024-12-03 10:53 UTC, closed without merging