[17.0][FIX] web_m2x_options: Error when installing employee module
OCA/web pull request #2921
Opened 2024-08-22 13:50 UTC by CRogos

When web_m2x_options is installed, and you install the employee module, you cannot open the employee app and get this error message: 

![image](https://github.com/user-attachments/assets/d42c2939-1a56-4b40-9f9f-ae821c640bbd)

The components Many2OneAvatarUserField and KanbanMany2OneAvatarUserField causing this error.

I am not sure if this is the best solution, because it also changes the dependency from "web" to "mail". 
Review feedback highly welcome.

2024-08-22 14:42 UTC, CarlosRoca13 commented
Are you sure the problem is with this module? I've installed it with `hr` locally and haven't had any issue (all without including your changes).

Do you have any extra module installed on your instance?

2024-08-22 16:01 UTC, CRogos commented
I could reproduced the issue in runbot, by installing the hr module.

But I just realized this issue only occurs in the development mode! (?debug=1)

http://oca-web-17-0-f4885276a6e4.runboat.odoo-community.org/web?debug=1#menu_id=106&action=160&model=res.partner&view_type=form

2024-08-23 05:02 UTC, CarlosRoca13 requested changes
Make this changes to avoid changing the dependency

2024-08-23 05:02 UTC, CarlosRoca13 commented on web_m2x_options/static/src/components/form.esm.js
> +
```suggestion
KanbanMany2OneAvatarField.props = {
    ...KanbanMany2OneAvatarField.props,
    fieldColor: {type: String, optional: true},
    fieldColorOptions: {type: Object, optional: true},
};
```

And change this line https://github.com/OCA/web/pull/2921/files#diff-ca954d78dad7b4338381958be4abd93f5fbea46f766a6af5e914a9bd74017737R9 by this 
```javascript
import {Many2OneAvatarField, KanbanMany2OneAvatarField} from "@web/views/fields/many2one_avatar/many2one_avatar_field";

2024-08-23 05:02 UTC, CarlosRoca13 commented on web_m2x_options/__manifest__.py
> +    "depends": ["mail"],
Don't change the dependency

2024-08-23 05:02 UTC, CarlosRoca13 commented on web_m2x_options/static/src/components/form.esm.js
> +
```suggestion
```

2024-08-23 07:02 UTC, pedrobaeza commented
It seems that we will have the same problem with any other custom m2o widget, isn't it? Can't we do anything that don't force to declare that extra options on each widget?

2024-08-23 07:08 UTC, CarlosRoca13 commented
I think it's not possible to make it more abstract... I have tried different options to avoid that extensions but nothing works... @chienandalu do you have any ideas to avoid them?

2024-08-23 07:47 UTC, chienandalu reviewed
> I think it's not possible to make it more abstract... I have tried different options to avoid that extensions but nothing works... @chienandalu do you have any ideas to avoid them?

What catches my eye is that these components already take their props from the `Many2OneField.props` so it should work with no extension somehow: https://github.com/OCA/OCB/blob/5eb4c06a5d26476cd47cfff0df23d5e05f5318b6/addons/web/static/src/views/fields/many2one_avatar/many2one_avatar_field.js#L16-L18

Did you try tweaking the assets loading order?

2024-08-23 08:19 UTC, CarlosRoca13 commented
Yes, I tried changing the order of asset loading, but I wasn't able to make the error go away.

2024-08-23 08:42 UTC, chienandalu commented
What about using `patch()`: https://github.com/odoo/documentation/blob/17.0/content/developer/reference/frontend/javascript_reference.rst?plain=1#L168-L169

2024-08-23 08:44 UTC, chienandalu commented
> What about using `patch()`: https://github.com/odoo/documentation/blob/17.0/content/developer/reference/frontend/javascript_reference.rst?plain=1#L168-L169

An example: https://github.com/OCA/OCB/blob/5eb4c06a5d26476cd47cfff0df23d5e05f5318b6/addons/sms/static/src/components/phone_field/phone_field.js#L8-L21

2024-08-23 08:44 UTC, CarlosRoca13 commented
Ups :sweat_smile:

2024-08-23 08:45 UTC, CarlosRoca13 commented
I will try it, I have tried with patch but patching the props directly

2024-08-23 08:47 UTC, CRogos commented
Any idea why this only occur in developer mode?

2024-08-23 08:49 UTC, CarlosRoca13 commented
> Any idea why this only occur in developer

Sometimes non-blocking errors are hidden to users, so they are only visible to developers. However, this doesn't mean they shouldn't be fixed.

2024-08-23 12:38 UTC, CarlosRoca13 commented
> What about using `patch()`: https://github.com/odoo/documentation/blob/17.0/content/developer/reference/frontend/javascript_reference.rst?plain=1#L168-L169

It does not work either

2024-08-28 06:29 UTC, CRogos commented
@CarlosRoca13 @chienandalu can we go with this solution as long we do not have any better way?

2024-09-05 13:15 UTC, CarlosRoca13 commented
What do you think @chienandalu?

2024-09-13 07:20 UTC, CRogos commented
@CarlosRoca13 shall we continue without @chienandalu ?
Maybe this solution is not the best, but it fixes the js error in developer mode.

2024-09-16 06:24 UTC, CarlosRoca13 approved these changes
Yes I think it's the only way to achieve this

2024-09-16 06:25 UTC, pedrobaeza commented
/ocabot merge patch

2024-09-16 06:52 UTC, merged