[18.0][MIG] web_datetime_picker_default_time: Migration to 18.0
OCA/web pull request #3024
Opened 2024-12-18 04:46 UTC by natuan9

2025-01-06 19:38 UTC, ivantodorovich approved these changes
Seems good.

It's a shame we don't have unit tests, though.
How do you feel about adding some?

2025-01-20 08:03 UTC, natuan9 commented
Hi @ivantodorovich , I added some test cases for this module.

2025-01-20 12:02 UTC, ivantodorovich requested changes
Thanks a lot!

As far as I remember, and as far as I can see on the CI logs, we need to explicitly execute these tests from a python test.

Here's an example on a 16.0 module: https://github.com/OCA/web/blob/16.0/web_domain_field/tests/test_qunit.py

2025-01-20 12:02 UTC, ivantodorovich commented on eslint.config.cjs
> -    files: ["**/*.esm.js"],
These files are synchronized from time to time from the https://github.com/oca/oca-addons-repo-template
This change will then be lost..

I recommend to simply use the `.test.esm.js` suffix on your filename, then it'd be selected by this existing pattern

2025-01-21 03:07 UTC, natuan9 commented on eslint.config.cjs
> -    files: ["**/*.esm.js"],
I tried using the suffix `.test.esm.js`, but Hoot doesn't work with this file extension. The guy in this video mentioned that test files must end with `.test.js`.
[Test your JS Code with Hoot](https://www.youtube.com/watch?v=QNHwykNNg2E&t=235s)
![image](https://github.com/user-attachments/assets/f449773f-6deb-46d9-a14b-52465aa9cd94)

2025-01-22 15:25 UTC, grindtildeath requested changes
Looks good but setting of default time while entering manually the date with keyboard does not work. (it used to in v16.0)

2025-02-03 05:04 UTC, natuan9 commented
> Looks good but setting of default time while entering manually the date with keyboard does not work

Hi @grindtildeath , is your default time field a JSON field? Do you mean editing the JSON field directly?

2025-02-11 11:19 UTC, natuan9 commented
Hi @grindtildeath , I resolved issue

2025-03-17 12:39 UTC, ivantodorovich reviewed
The code has gotten a lot more complicated than before. But I think it's mostly due to the amount of full overwrites we have in here, which should be avoided as much as possible

If you could try to reduce them, that'd be great

2025-03-17 12:39 UTC, ivantodorovich commented on web_datetime_picker_default_time/static/src/js/datetimepicker_service.esm.js
> +                const onInputChange = (ev) => {
Can we avoid re-defining methods that we don't want to override/change?

If the method is exactly the same as the original, then you can probably reference the one in `originalService`

2025-03-17 12:39 UTC, ivantodorovich commented on web_datetime_picker_default_time/static/src/js/datetimepicker_service.esm.js
> +// OVERRIDE:
See my other comment about trying to keep here only the methods that are actually overriden

2025-04-01 09:21 UTC, natuan9 commented
Hi @ivantodorovich , I updated, please help to review

2025-04-01 11:32 UTC, ivantodorovich approved these changes
Thanks @natuan9 ! LG technically now 👍🏻

2025-04-15 09:00 UTC, sebalix approved these changes
Tested locally, working well :+1:

2025-05-21 14:03 UTC, chienandalu approved these changes
Tested :+1:

2025-10-09 10:50 UTC, simahawk commented
Rebased and replaced here to speed it up https://github.com/OCA/web/pull/3311
Thanks!

2025-10-09 10:50 UTC, closed without merging