[18.0][MIG] web_responsive: Migration to 18.0
OCA/web pull request #3037
Opened 2024-12-24 17:58 UTC by kobros-tech

2024-12-24 18:29 UTC, kobros-tech commented
@lasley 
@danieltorres7 
@yajo 
@zeroheure 

I wonder why I see this error:

`File "/opt/odoo/odoo/sql_db.py", line 572, in execute
    return self._cursor.execute(*args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column res_users.user_year_born does not exist
LINE 1: ...apps_menu_theme", "res_users"."is_redirect_home", "res_users...`

despite the tests succeed in a clean new database locally.
![Screenshot from 2024-12-24 21-16-11](https://github.com/user-attachments/assets/cefe8f0c-e5e1-4023-b2ae-7de7f2d65648)


I searched for this field user_year_born in odoo CE but it is not there, and I don't know where it came from.

2024-12-24 21:22 UTC, kobros-tech commented
The issue is inside web_pivot_computed_measure module tests.
I introduced a PR of a fix to the tests #3038

2025-01-22 03:30 UTC, chaule97 commented
Hi, I opened another PR https://github.com/OCA/web/pull/3057, welcome you review it

2025-01-27 14:59 UTC, CarlosRoca13 commented
Please, note this pr https://github.com/OCA/web/pull/3069

2025-01-27 15:02 UTC, carlos-lopez-tecnativa requested changes

2025-01-27 15:02 UTC, carlos-lopez-tecnativa commented on web_responsive/static/tests/test_patch.js
> +    steps: () => [
Take into account, this is not a test; it is a patch.

2025-01-27 15:02 UTC, carlos-lopez-tecnativa commented on web_responsive/static/tests/test_patch.js
> +            trigger: '.o_navbar_apps_menu"]',
This expression is wrong; it is missing parentheses.

2025-01-27 17:28 UTC, kobros-tech commented on web_responsive/static/tests/test_patch.js
> +            trigger: '.o_navbar_apps_menu"]',
dear @CarlosRoca13 if this file is not correct, the test will fail and we will see red alarm by oca boat.

I don't believe if the syntax is wrong or the registry is not for tests, are you a developer?

we use pre-commit in OCA and this command is reviewing the syntax, as long as it is not raising errors here, then the syntax is correct too!

2025-01-27 17:32 UTC, kobros-tech commented on web_responsive/static/tests/test_patch.js
> +            trigger: '.o_navbar_apps_menu"]',
look at this properly and you will see that the file has run and succeeded:

https://github.com/OCA/web/actions/runs/12946365358/job/36110738186?pr=3037#step:8:297

2025-01-27 17:34 UTC, pedrobaeza commented on web_responsive/static/tests/test_patch.js
> +            trigger: '.o_navbar_apps_menu"]',
Everyone can make a mistake. I think you should reduce your tone with things like `are you a developer?`.

2025-01-27 18:40 UTC, carlos-lopez-tecnativa requested changes

2025-01-27 18:40 UTC, carlos-lopez-tecnativa commented on web_responsive/static/tests/test_patch.js
> +            trigger: '.o_navbar_apps_menu"]',
> dear @CarlosRoca13 if this file is not correct, the test will fail and we will see red alarm by oca boat.
> 
> I don't believe if the syntax is wrong or the registry is not for tests, are you a developer?
> 
> we use pre-commit in OCA and this command is reviewing the syntax, as long as it is not raising errors here, then the syntax is correct too!

@kobros-tech  The original purpose of this code is to `patch` the original function of Odoo, not to add a new test. 
Therefore, this code is not executed when `pre-commit` is run or when tests are executed. It is used in other modules when you import `showAppsMenuItem`.

If you review the expression `.o_navbar_apps_menu"]`, it is syntactically incorrect. It should be:

```suggestion
            trigger: '.o_navbar_apps_menu',
```
Note: The extension of this filename must be renamed to` .esm.js.`

Sorry if I wrote parentheses instead of brackets; I edited my comment.

2025-01-27 18:40 UTC, carlos-lopez-tecnativa commented on eslint.config.cjs
> +        sourceType: "module",
Why did you change this?

2025-01-27 18:51 UTC, pedrobaeza commented on eslint.config.cjs
> +        sourceType: "module",
Probably because he didn't rename to `.esm.js` the other file...

2025-01-27 20:53 UTC, kobros-tech commented on eslint.config.cjs
> +        sourceType: "module",
correct 👌

2025-01-27 21:34 UTC, kobros-tech commented on web_responsive/static/tests/test_patch.js
> +            trigger: '.o_navbar_apps_menu"]',
@carlos-lopez-tecnativa 

thanks for clarification :)

now for this file, I copied it from 17.0 to 18.0, maybe there was a change of it during migration in the original PR

please review and if there is any bug tell me.

2025-01-27 23:01 UTC, kobros-tech commented
Wow wow wow
finally all tests succeed :)
@pedrobaeza

2025-01-28 07:56 UTC, pedrobaeza commented
I see that #3057 doesn't require to do anything in the tests on `web_pivot_computed_measure` to have a green CI. Can you check and try to not modify anything else?

2025-01-28 08:01 UTC, pedrobaeza commented
Testing the module in runboat, I detect that all the part that neutralizes the automatic preview seems to be not working (and consequently, the own sided preview).

2025-01-28 11:09 UTC, kobros-tech commented
> @lasley @danieltorres7 @yajo @zeroheure
> 
> I wonder why I see this error:
> 
> `File "/opt/odoo/odoo/sql_db.py", line 572, in execute return self._cursor.execute(*args, **kwargs) File "/opt/odoo/odoo/sql_db.py", line 354, in execute res = self._obj.execute(query, params) psycopg2.errors.UndefinedColumn: column res_users.user_year_born does not exist LINE 1: ...apps_menu_theme", "res_users"."is_redirect_home", "res_users...`
> 
> despite the tests succeed in a clean new database locally. ![Screenshot from 2024-12-24 21-16-11](https://private-user-images.githubusercontent.com/93363076/398464026-cefe8f0c-e5e1-4023-b2ae-7de7f2d65648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgwNjI1MjgsIm5iZiI6MTczODA2MjIyOCwicGF0aCI6Ii85MzM2MzA3Ni8zOTg0NjQwMjYtY2VmZThmMGMtZTVlMS00MDIzLWIyYWUtN2RlN2YyZDY1NjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI4VDExMDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5M2RlYzU3YTcyM2I4NGYyOTM3MjI3YzJjYzdmMGM3YTU1OGUxZmNkZTNjNTMxMjdlMzkxMTEzNWM2ZGFlMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ajBIVyyzt5Fgupq8hG-G2sIaV5P6aDFEO2i39Q-kROg)
> 
> I searched for this field user_year_born in odoo CE but it is not there, and I don't know where it came from.

@pedrobaeza 

what is the value of this conversation if the old tests is not interfering the migration?

even the other migration that you mentioned does not include all tests, but removed some of them.

if you want to see the errors with the other PR ask the contributor to leave the tests as they are and you will see this same error.

Even you can try it locally and catch the error.

I seek to correct not to mock the correctness

2025-01-28 11:13 UTC, pedrobaeza commented
OK, just asking. I always try to touch the minimum the existing things. Please check my other comment that affects the functionality.

2025-01-28 11:13 UTC, kobros-tech commented
> Testing the module in runboat, I detect that all the part that neutralizes the automatic preview seems to be not working (and consequently, the own sided preview).

we observed some errors in the UI we will fix, I don't know if they are the same but I am happy if you share them.

2025-01-28 11:21 UTC, pedrobaeza commented
I have already commented the problem. Is it not clear?

2025-01-28 11:29 UTC, kobros-tech commented
> I have already commented the problem. Is it not clear?

I will check it and compare to the issues we found, give me some time.

thanks for reviewing and helping me to improve the migration.

2025-01-28 11:35 UTC, kobros-tech commented
> OK, just asking. I always try to touch the minimum the existing things. Please check my other comment that affects the functionality.

nevermind, this seems complicated and worrying and shall see the value when all gaps get filled.

Thanks for inquiry.

2025-01-28 12:45 UTC, kobros-tech commented
> I have already commented the problem. Is it not clear?

Can you provide me with screenshots or log messages, we are fixing an error with the urls of search results

2025-02-03 09:58 UTC, pilarvargas-tecnativa commented
Please include https://github.com/OCA/web/pull/3075 and https://github.com/OCA/web/pull/3074

2025-02-04 12:09 UTC, kobros-tech commented
I will add merged commits to this PR, thanks 
@kobros-tech

2025-02-06 04:09 UTC, Ngquang commented
Ping @pedrobaeza @carlos-lopez-tecnativa @pilarvargas-tecnativa any news guys

2025-02-06 07:01 UTC, pilarvargas-tecnativa commented on web_responsive/static/src/views/form/status_bar_buttons.xml
> +        <!-- <xpath expr="//t[@t-set-slot='toggler']" position="replace">
This is no longer necessary?

2025-02-06 10:12 UTC, kobros-tech commented on web_responsive/static/src/views/form/status_bar_buttons.xml
> +        <!-- <xpath expr="//t[@t-set-slot='toggler']" position="replace">
yes, thanks

2025-03-05 08:30 UTC, Ngquang commented
ping @kobros-tech , any news man ?

2025-03-27 16:21 UTC, kobros-tech commented
PR #3105 is here too

2025-03-27 17:55 UTC, kobros-tech commented
@pedrobaeza @carlos-lopez-tecnativa @pilarvargas-tecnativa @Ngquang 

Dear gyps, I ask people in charge if @pedrobaeza can also work on having #3038 merged as this migration is dependednt on the improved tests cases there.
No need to create a demo model with fields while we can test already existing ones.

Please work on merging that PR so I can focus on add any value from #3057 with @chaule97 
His commit is here now and I am validating and work on keeping only the necessary changes, if any.

And please forgive me rage sometimes as I am used to be tough especially when I see the danger.

2025-03-27 20:35 UTC, kobros-tech commented
@chaule97 

I invite you to pull this branch: 
https://github.com/kobros-tech/web/tree/18.0-mig-web_responsive

or that one:
https://github.com/kobros-tech/web/tree/18.0-mig-web_responsive

and then add ONLY the necessary changes, we do migration as priority then add fixes that are against migrations

but entire chages they may not like here, and I in person I couldn't review all of your commit nicely as the changes are everywhere, and I assume the entire module is not bad to need changes everywhere.

2025-03-28 13:05 UTC, carlos-lopez-tecnativa requested changes
Functional review (tested locally)

2025-03-28 13:05 UTC, carlos-lopez-tecnativa commented on web_responsive/static/src/components/apps_menu/apps_menu.xml
> +                title="Home Menu XXX"
???

2025-03-28 13:05 UTC, carlos-lopez-tecnativa commented on web_responsive/readme/DESCRIPTION.md
> +  ![image](../static/img/listview.gif)
This is now native to the Odoo server starting from V17, but I noticed that on mobile, the list view header is hidden. Is it possible to check this, or is this out of scope for this module?

![image](https://github.com/user-attachments/assets/de7650b9-36dd-4904-b9c9-6b88ca89aa6a)

2025-03-28 13:05 UTC, carlos-lopez-tecnativa commented on web_responsive/readme/DESCRIPTION.md
> +- Control panel buttons use icons to save space.
I got this error when trying to expand the action buttons.

![image](https://github.com/user-attachments/assets/b6e501cb-01b4-470f-bf7e-aceb41698da0)


![image](https://github.com/user-attachments/assets/f1e3a2cd-4d88-43b9-bf1d-0ecf88c43c59)


Additionally, I don't see the buttons.

![image](https://github.com/user-attachments/assets/43337ada-2efc-42fb-b152-1c206eb3e141)

2025-03-28 13:05 UTC, carlos-lopez-tecnativa commented on web_responsive/static/src/components/menu_odoo_searchbar/searchbar.scss
This file is empty. Can it be removed?

2025-03-28 13:05 UTC, carlos-lopez-tecnativa commented on web_responsive/static/tests/test_patch.js
> +        const {patch} = require("@web/core/utils/patch");
Please convert to ESM

2025-04-11 03:26 UTC, kobros-tech commented on web_responsive/static/src/components/apps_menu/apps_menu.xml
> +                title="Home Menu XXX"
ok thanks

2025-04-11 03:28 UTC, kobros-tech commented on web_responsive/readme/DESCRIPTION.md
> +  ![image](../static/img/listview.gif)
let me check if it is related to that module or not

2025-04-11 03:29 UTC, kobros-tech commented on web_responsive/readme/DESCRIPTION.md
> +- Control panel buttons use icons to save space.
all right

2025-04-11 04:57 UTC, kobros-tech commented on web_responsive/readme/DESCRIPTION.md
> +  ![image](../static/img/listview.gif)
tell me which mobile type you use and which os version?

![IMG_20220511_192601](https://github.com/user-attachments/assets/bae36b1f-4583-4800-895c-19bbec78bae1)

2025-04-11 04:59 UTC, kobros-tech commented on web_responsive/readme/DESCRIPTION.md
> +  ![image](../static/img/listview.gif)
![Screenshot_2025-04-11-07-53-37-12_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/a7132a58-90f8-4a73-bf42-5928552c1a07)

2025-04-11 05:48 UTC, kobros-tech commented on web_responsive/readme/DESCRIPTION.md
> +- Control panel buttons use icons to save space.
action button in 18.0 is containing smart buttons even after uninstalling the module 

I fixed xpath error as well

![Screenshot_2025-04-11-08-22-26-78_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/509b7846-0ab2-46c1-b840-3989aced92e3)

2025-04-11 06:17 UTC, pedrobaeza commented
This migration still loses the preview display that is not opening automatically the attachments (for example in invoices), and that has the previous possibilities. Please restore that behavior.

2025-04-11 06:37 UTC, kobros-tech commented
> This migration still loses the preview display that is not opening automatically the attachments (for example in invoices), and that has the previous possibilities. Please restore that behavior.

yes, its a bug here
I will work on it

2025-04-11 07:08 UTC, kobros-tech commented
> This migration still loses the preview display that is not opening automatically the attachments (for example in invoices), and that has the previous possibilities. Please restore that behavior.

There was an issue with scss, on my side I saw chatter is taking 90% of the page I am still seeing document but in the big view only.

please check again if you don't see the document try to minimize the fonts or maximize the resolution.

2025-04-14 04:09 UTC, chaule97 commented
Hi @kobros-tech , I have created refactor code PR https://github.com/kobros-tech/web/pull/1 in your repo. Please review, merge and squash it

2025-04-17 13:18 UTC, etobella commented
@kobros-tech I made a basic functional test and everything looks great. What is missing?

2025-04-17 13:24 UTC, kobros-tech commented
> @kobros-tech I made a basic functional test and everything looks great. What is missing?

@etobella 
Thanks very much, I think nothing is missing after I compared my PR to another one.
I did changes requested by reviewers and merged some commits here as requested and merged in 17.0 too.

2025-04-17 13:40 UTC, etobella approved these changes

2025-04-17 15:57 UTC, pedrobaeza requested changes
Please avoid this ugly view if no icon defined:

![imagen](https://github.com/user-attachments/assets/37b70e81-2f30-44d3-9f7a-09fbc48bfe27)

And this is still not covering the requirement of not auto-showing attachment for example in invoices:

![imagen](https://github.com/user-attachments/assets/e8a33d4c-37d9-4b0b-9223-7b193cf6e569)

and you have to use the other preview "style" where you can maximize it. Why are you ignoring me on this?

2025-04-17 16:36 UTC, kobros-tech commented
@pedrobaeza 

after I ran tests twice I confirm the timeout issue is solved by increasing the step_delay, reference:
https://github.com/odoo/odoo/blob/18.0/addons/im_livechat/tests/test_chatbot_form_ui.py#L42

PR:
https://github.com/OCA/web/pull/3158

2025-04-17 16:49 UTC, kobros-tech commented
@pedrobaeza 
good idea to add a default icon similar to modules don't have icons.

but for the preview, if I didn't understand you or I did and having it fine.

as if I zoom out screen it pops up and if I zoom in the previow goes away, and I will record a video to show.

2025-04-17 16:50 UTC, kobros-tech commented
@pedrobaeza 

I can't ignore you, but sometimes I misunderstand or unable to answer if I have a good answer.
I am sorry really.

2025-04-17 16:58 UTC, kobros-tech commented
### Preview in invoices screen:

https://github.com/user-attachments/assets/593e6725-d183-4df0-92cc-7ad1f85991dd

2025-04-17 17:01 UTC, pedrobaeza commented
I already stated in https://github.com/OCA/web/pull/3057#pullrequestreview-2721982131 and here in https://github.com/OCA/web/pull/3037#issuecomment-2795934987.

My initial comment with detailed explanation: https://github.com/OCA/web/pull/2405#issuecomment-1435661180

Extracted from there:

4. **Document viewer**

   Odoo includes natively the possibility of viewing in an embedded popup PDF files, videos or images. On previous versions, as the community edition always put the chatter on the bottom, these documents were previewed full size, covering the contents and not letting you to work side by side.

   ![Selección_016](https://user-images.githubusercontent.com/7165771/219865126-43de4b4f-596b-44a0-8c5d-8e4081ca8e20.png)


   `web_responsive` then included code for working on a more similar way than enterprise: putting the document viewer on the side, for easing the input for example on vendor bills, copying things side by side:

   ![Selección_017](https://user-images.githubusercontent.com/7165771/219865375-dfe9ce03-228e-43b7-b5c1-9c5c7d4f3eba.png)

   But it was also decided to do it in a more convenient way:

   - Don't opening by default the so considered main attachment by Odoo. This is not always what you want to do, and it covers the conversation (or move it to the bottom, being not consistent where to find it).
   - Allow to display this way any of the attachments, not only what they consider the main one.

   Odoo has now included these enterprises features in the community edition, but they use a different "document viewer" for the side view, and it still has the first mentioned flaw. So I think we need to tackle this in the OCA module. Possible options:

   1. Disable the "side viewer", and use the main document viewer in the same way as in previous versions.
   2. Don't move the chatter to bottom, don't open the side viewer in any case, opening it when clicking the attachments, and put a close X icon on the side viewer to "return" to the chatter.

----

See also #2745, and how it was added in 17 in #2795

2025-04-17 17:08 UTC, pedrobaeza commented
@kobros-tech I insist: the problem is the automatic display of that preview in the invoices. It should be disabled by default. We want the preview, but not automatic. Do you understand me?

2025-04-17 17:13 UTC, pedrobaeza commented
And that automatic preview is not using the same stuff:

![imagen](https://github.com/user-attachments/assets/a1066d38-7343-4487-b62f-e4760f8481c9)

2025-04-17 17:56 UTC, kobros-tech commented
let me understand this and see what I can do, at least to try.

2025-04-17 18:03 UTC, kobros-tech commented
@pedrobaeza 

I did try odoo without web_responsive and with it.

I saw the preview is poping up automatically, and in case of clicking the attachment the big screen of it pops up.

If I catch your point, I am asked to disable the default one but keeping the function if I click on attachmen?

becaue of the pros of the one we see when cliking on attachment over the other auto one?

If I am correct ok, I will try.

2025-04-17 18:15 UTC, pedrobaeza commented
> I am asked to disable the default one but keeping the function if I click on attachmen?

Yes. This is what we have as part of `web_responsive` module since a lot of versions ago, and what you have to keep migrating the module. It's not something new that is asked.

> becaue of the pros of the one we see when cliking on attachment over the other auto one?

Yes, already explained in quotes, but summarizing:

- Chatter visible without scrolling.
- Maximize possibility.
- Be able to see this way more than one attachment, not the main one.

2025-04-21 10:30 UTC, pedrobaeza commented
/ocabot migration web_responsive

2025-04-21 10:40 UTC, pedrobaeza reviewed
Functionally tested on runboat and now the part about not auto-previewing the attachment is working correctly.

Three comments inline for being clarified before proceeding with the merge, waiting also for some confirmation of the rest of the contributors/reviewers. cc @carlos-lopez-tecnativa @chaule97

2025-04-21 10:40 UTC, pedrobaeza commented on web_responsive/static/src/components/apps_menu/apps_menu.xml
> +                data-hotkey="shift+h"
Why are you changing this hotkey and making it more complicated?

2025-04-21 10:40 UTC, pedrobaeza commented on web_responsive/static/src/views/form/form_statusbar.scss
> +            overflow: unset;
Why changing this to `unset`?

2025-04-21 10:40 UTC, pedrobaeza commented on web_responsive/static/tests/test_patch.esm.js
> -        "use strict";
Why removing this? It should be set always.

2025-04-21 12:52 UTC, carlos-lopez-tecnativa reviewed
Tested and working. Just a few comments related to the features that work fine on desktop, and I think they can be improved to work well on mobile. Please let me know if they can be improved or if they are out of the scope of this module.

2025-04-21 12:52 UTC, carlos-lopez-tecnativa commented on web_responsive/readme/DESCRIPTION.md
> +  ![image](../static/img/listview.gif)
Sorry for the delay. I uploaded a video to explain my comment. Please let me know if this case can be handled by this module or not.

https://github.com/user-attachments/assets/aecf4654-27c6-4821-8f3e-30160656845b

2025-04-21 12:52 UTC, carlos-lopez-tecnativa commented on web_responsive/static/src/components/apps_menu_item/apps_menu_item.xml
> +            draggable="false"
In Odoo enterprise, now it is possible to change the order of the menu items. I'm not sure if support for this can be added here, or if this attribute prevents its use.

https://github.com/user-attachments/assets/262b8cdf-df9c-4164-88e4-2659c9ab8631

2025-04-21 12:52 UTC, carlos-lopez-tecnativa commented on web_responsive/static/tests/test_patch.esm.js
> +odoo.define(
Does `odoo.define` still have support? In my previous comment, I said to convert it to ESM, not just the file extension, but the code as well.

2025-04-22 10:09 UTC, kobros-tech commented
Are we ready for migration or is there any remaining comment?

2025-04-22 18:02 UTC, pedrobaeza commented
It seems there are 2 pending comments: https://github.com/OCA/web/pull/3037#discussion_r2052302234 and https://github.com/OCA/web/pull/3037#discussion_r2052290984

2025-04-23 11:11 UTC, kobros-tech commented
the two comments are not applied in version 17.0

2025-04-23 11:24 UTC, kobros-tech commented
### Differences between version 18.0 and version 17.0, open for opinions and comments:

![Screenshot from 2025-04-23 14-21-59](https://github.com/user-attachments/assets/30981a9e-f97a-43db-80f3-5a9ad61457a1)
![Screenshot from 2025-04-23 14-22-10](https://github.com/user-attachments/assets/0c22f2ac-b1cd-4266-ba61-dff861819cf1)
![Screenshot from 2025-04-23 14-22-20](https://github.com/user-attachments/assets/a42a3cd3-1a4e-4917-95c4-084e2c253264)
![Screenshot from 2025-04-23 14-22-35](https://github.com/user-attachments/assets/3a227525-c6ee-433f-a6dd-9fe0a560ba4e)
![Screenshot from 2025-04-23 14-22-52](https://github.com/user-attachments/assets/c3458202-ad44-4571-b9d5-f6ab0386f84d)
![Screenshot from 2025-04-23 14-23-11](https://github.com/user-attachments/assets/29a024e5-e8f2-49d0-bef5-8ee7fefea4b4)

2025-04-23 13:36 UTC, kobros-tech commented
Any specific migration comments?

I welcome migration related comments, but any new feature I can not add here now.

2025-04-23 14:25 UTC, carlos-lopez-tecnativa commented on web_responsive/static/src/components/apps_menu_item/apps_menu_item.xml
> +            draggable="false"
Ok for me, this commit can be considered a new feature.

2025-04-23 14:29 UTC, carlos-lopez-tecnativa approved these changes
I wish the issue mentioned in this comment https://github.com/OCA/web/pull/3037#discussion_r2052290984 could be handled by this module, because it works fine on desktop, but in mobile view the header is not sticky.
But anyway, let's go!

2025-04-23 16:11 UTC, kobros-tech commented
it should be in a separate PR as the issue you mentioned is coming from old version, I see it as a feature in fact.

2025-04-23 18:19 UTC, pedrobaeza approved these changes
OK, let's go with this. Thanks for all the work.

/ocabot merge nobump

2025-04-23 18:26 UTC, merged

2025-04-24 11:39 UTC, houssine78 commented
thank you @pedrobaeza for having push the review so far !

thank you @kobros-tech for this most wanted PR