Made web_send_message_popup installable in 8.0
OCA/web pull request #371
Opened 2016-06-09 13:22 UTC by lbonjean

2016-06-09 13:45 UTC, guewen commented
tested, works fine, thanks
:+1:

2018-10-10 09:20 UTC, simahawk requested changes
lint needs fixes

![image](https://user-images.githubusercontent.com/347149/46726399-8854bb00-cc7e-11e8-8c5c-6d0ba4d6e108.png)

2018-10-10 09:20 UTC, simahawk commented on web_send_message_popup/__openerp__.py
>   'website': 'http://www.camptocamp.com',
https://github.com/OCA/web

2018-10-10 09:21 UTC, simahawk commented
@lbonjean would you mind to get back here for an easy fix?

2021-12-19 12:31 UTC, closed without merging