WIP: migrate to 9.0
OCA/web pull request #457
Opened 2016-10-31 19:15 UTC by ovnicraft

* [ ] check framework about `is_action_enabled()`

2018-02-12 10:42 UTC, zakiuu requested changes

2018-02-12 10:42 UTC, zakiuu commented on web_action_conditionable/__openerp__.py
> +    'version': '9.0.0.1.0',
@ovnicraft 'version': '9.0.1.0.0'

2018-02-12 10:43 UTC, zakiuu commented
@ovnicraft Are you willing to finish the PR?

2018-02-14 18:53 UTC, ovnicraft commented
I consider more important migration to 10 and 11.

Closing this.

2018-02-14 18:53 UTC, closed without merging

2018-02-15 15:45 UTC, zakiuu commented
@ovnicraft thanks for the reply. You can review this one if you have time #861.
@pedrobaeza