Porting to 10
OCA/web pull request #464
Opened 2016-11-04 16:53 UTC by danieltorres7

- Changed model to installable.
- Tested and everything seems ok.

2016-11-09 13:00 UTC, danieltorres7 commented
@leorochael, can you take a look?

2016-11-09 13:02 UTC, pedrobaeza commented
You should switch to new JS API

2016-11-09 13:17 UTC, leorochael commented
@pedrobaeza Can you give us some pointers? Where can we find docs or examples of the new JS API?

2016-11-09 13:19 UTC, pedrobaeza commented
I'm afraid there isn't. You need to see sample in OCA/web repository for 9.0 and odoo itself.

2016-11-09 13:30 UTC, leorochael commented
@pedrobaeza, if it's a v9 new JS API, isn't the changes landed in #290, enough?

2016-11-09 14:03 UTC, pedrobaeza commented
Yeah, indeed, sorry for the noise. I though it was a direct migration from 8.0. Then it's enough.

2016-11-09 14:05 UTC, leorochael requested changes

2016-11-09 14:05 UTC, leorochael commented on web_tree_image/__manifest__.py
> -    'version': '9.0.1.1.0',
Please merge this commit with the previous one

2016-11-09 14:23 UTC, leorochael commented on web_tree_image/static/src/js/web_tree_image.js
> +odoo.define('web.WebTreeImage', function (require) {
@pedrobaeza @StefanRijnhart, What do you think of this change?

It looks ok to me, though it doesn't seem strictly necessary to port to v10

2016-11-09 14:24 UTC, leorochael reviewed
LGTM :+1:

2016-11-09 14:24 UTC, pedrobaeza commented on web_tree_image/static/src/js/web_tree_image.js
> +odoo.define('web.WebTreeImage', function (require) {
This only impacts in possible module that inherits this, so no actual problem I think.

2016-11-14 07:26 UTC, StefanRijnhart approved these changes
All good, thank you!

2016-11-14 07:27 UTC, pedrobaeza approved these changes

2016-11-14 07:27 UTC, merged