9.0 mig web widget one2many tags
OCA/web pull request #502
Opened 2016-11-28 01:57 UTC by susport

Mig to 9.0 web_widget_one2many_tags

2016-11-29 20:08 UTC, jjscarafia commented
I've try it locally but widget is displayed on the default way.
See image attached
![seleccion_051](https://cloud.githubusercontent.com/assets/3016656/20726983/7c460d4a-b656-11e6-9a2f-c4d7badd5369.png)

2017-01-09 11:59 UTC, hbrunn requested changes

2017-01-09 11:59 UTC, hbrunn commented on web_widget_one2many_tags/README.rst
> +*Adhoc SA <jjs@adhoc.com.ar>
add a space

2017-01-09 11:59 UTC, hbrunn commented on web_widget_one2many_tags/README.rst
> +* Iv??n Todorovich <ivan.todorovich@gmail.com>
@ivantodorovich's accented a didn't survive the replaying

2017-01-09 11:59 UTC, hbrunn commented on web_widget_one2many_tags/static/src/js/web_widget_one2many_tags.js
> +                            var list_view = new widget_one2many_tag.web.form.One2ManyListView(
no. all of them need to be required at the top of the file, then used in the code. Won't repeat this for every instance, but you basically need to change this in every changed line of code in this file

2017-01-09 11:59 UTC, hbrunn commented on web_widget_one2many_tags/static/src/js/web_widget_one2many_tags.js
> +});
you need to return the classes this addons creates here in order to have then accessible for other addons

2017-01-09 11:59 UTC, hbrunn commented on web_widget_one2many_tags/static/src/xml/web_widget_one2many_tags.xml
> +     <t t-name="FieldOne2ManyTag" t-extend="FieldMany2ManyTag" />
the code above says we need both

2017-01-09 11:59 UTC, hbrunn commented on web_widget_one2many_tags/views/templates.xml
> +        </template>
watch your indentation

2017-01-09 11:59 UTC, hbrunn commented on web_widget_one2many_tags/static/src/js/web_widget_one2many_tags.js
> +    });
you don't return anything, this means the classes defined here are not accessible to other addons

2017-01-09 11:59 UTC, hbrunn commented on web_widget_one2many_tags/static/src/js/web_widget_one2many_tags.js
> +                            var list_view = new widget_one2many_tag.web.form.One2ManyListView(
this a absolutely not the correct way to refer to objects that were accessed via `instance` in earlier versions. You need to `require` every object used above where you also require `Model`. And the canonical name then is the last dotted chunk.
You do this all over the place in this file, and need to change it everywhere

2017-01-27 22:18 UTC, lasley commented
Hi @susport - are you planning on continuing this PR?

2019-02-27 14:01 UTC, daramousk commented
@hbrunn I need this ported to 10.0. Should I take over from here since there is no response?

2019-02-27 14:14 UTC, hbrunn commented
in principle, yes, but check first if the user has submitted a CLA to the OCA. Without this, we can't merge the commits and then you'll be better off doing the migration yourself.

Closing this meanwhile for inactivity.

2019-02-27 14:14 UTC, closed without merging