[MIG][10.0] web_tree_many2one_clickable
OCA/web pull request #531
Opened 2017-01-19 11:11 UTC by SodexisTeam

Minor changes only
cc: @pedrobaeza @antespi @Yajo

2017-01-19 11:13 UTC, pedrobaeza commented on web_tree_many2one_clickable/migrations/9.0.1.0.0/pre-migration.py
> +# -*- coding: utf-8 -*-
Please remove this file

2017-01-20 07:53 UTC, atchuthan commented on web_tree_many2one_clickable/migrations/9.0.1.0.0/pre-migration.py
> +# -*- coding: utf-8 -*-
@pedrobaeza removed the migration

2017-01-20 09:09 UTC, pedrobaeza commented
Better to remove the commit that add it (it's separated) and then the repo final size will be smaller

2017-01-20 12:00 UTC, atchuthan commented
@pedrobaeza removed the commit

2017-01-20 14:37 UTC, pedrobaeza commented on web_tree_many2one_clickable/__manifest__.py
> +              "Sodexis, "
The changes you have made don't make that you should put it on the author list

2017-01-20 14:42 UTC, pedrobaeza requested changes
Tried on runbot and working as expected, but the author thing is blocking IMO

2017-01-23 09:03 UTC, Yajo commented on web_tree_many2one_clickable/__manifest__.py
> +              "Sodexis, "
I don't think contributions should always be counted as number of LOC. Migrating an addon involves time (test it, fix it, send PR...). IMHO it's fair to let the contributors be honoured by these little credits.

2017-01-23 09:03 UTC, yajo approved these changes

2017-01-23 09:18 UTC, pedrobaeza commented on web_tree_many2one_clickable/__manifest__.py
> +              "Sodexis, "
@Yajo, I repeat, it's not the case (see diff), and this is not contribution, it's authorship.

2017-01-26 15:02 UTC, tarteo approved these changes
Thanks!

2017-01-26 16:46 UTC, pedrobaeza commented
Please change authorship and I'll merge.

2017-01-27 06:24 UTC, dvdhinesh commented
@pedrobaeza 

@atchuthan is off for a week. He will continue to work on this by next week. Thanks.

2017-02-01 06:21 UTC, atchuthan commented
corrections done

2017-02-01 07:40 UTC, pedrobaeza approved these changes

2017-02-01 07:40 UTC, merged