[10.0][ADD][web_listview_multi_select]
OCA/web pull request #532
Opened 2017-01-19 20:23 UTC by tarteo

Enables the user to select a range of records with the shift key.

2017-01-19 20:24 UTC, pedrobaeza commented
Reading the description, better to call it `web_listview_range_select` :wink: 

Very good modules you are contributing anyway! I'll review it soon

2017-01-19 20:26 UTC, tarteo commented
@pedrobaeza Good one, I'll change it! Thanks :).

2017-01-19 22:21 UTC, rafaelbn approved these changes
Tested in runbot

2017-01-19 22:27 UTC, pedrobaeza requested changes
If you want to select several ranges, the module is not working correctly, as you can only do one range. The ideal is that the code go from the row where you have click with Shift pressed and find going up the first selected row (not the first absolute selected row). Do you understand me?

2017-01-23 12:46 UTC, tarteo commented
@pedrobaeza Do you mean that the selected range does not reset if the user click + shift click multiple times?

like this:

Step 1:
normal click on row 0
shift click on row 3
selected rows are now 0 to 3

Step 2.1:
normal click on row 5
shift click on row 8
selected rows are now 5 to 8

Step 2.2:
shift click on row 5
selected rows are now 0 to 5

Currently it always extends the range resulting in rows 0 to 8 to be selected (step 1 + step 2.1).

2017-01-23 12:56 UTC, pedrobaeza commented
That's the problem. What I want is to have selected multiple ranges. These are my expected steps:

Step 1:
normal click on row 0
shift click on row 3
selected rows are now 0 to 3

Step 2.1:
normal click on row 5
shift click on row 8
selected rows are now **0 to 3 and 5 to 8**

2017-01-23 13:04 UTC, tarteo commented
Clear! I'll work on it ASAP.

2017-01-23 13:32 UTC, houssine78 commented
possible to cherry pick individual rows through CTRL + click?

2017-01-23 13:36 UTC, pedrobaeza commented
Well, that's the normal behavior without Ctrl key

2017-01-23 13:44 UTC, houssine78 commented
ok I just get the thing(checkbox of the line is checked) I though that it was selecting all the line for a copy paste(like you could do in excel).

2017-01-23 13:46 UTC, tarteo commented
@houssine78 With Odoo's default behavior you already can cherry pick rows by just left clicking (without  using the ctrl key)

2017-01-23 13:55 UTC, tarteo commented
@houssine78 Yes, this module only enables the user to select multiple rows with shift + click.

2017-01-23 14:16 UTC, houssine78 commented
ok thanks! it's already nice feature!

2017-01-23 19:59 UTC, tarteo commented
@pedrobaeza It's now possible to select multiple ranges.

2017-01-23 20:00 UTC, pedrobaeza commented
Cool, I'll check it when runbot finishes

2017-01-24 08:16 UTC, pedrobaeza approved these changes
Working flawlessly! Only one minor comment

2017-01-24 08:16 UTC, pedrobaeza commented on web_listview_range_select/README.rst
> +#. hold shift and click another record.
You can add here:
```
#. You can repeat the operation as many times as you want.
```

2017-01-24 08:50 UTC, tarteo commented on web_listview_range_select/README.rst
> +#. hold shift and click another record.
Done :)

2017-01-25 09:42 UTC, espo-tony commented
:+1: Great feature!

2017-01-25 11:23 UTC, legalsylvain commented
Tested on runbot. works perfectly. Cool feature, thanks.
:+1: .

2017-01-25 11:23 UTC, merged

2017-01-25 12:01 UTC, pedrobaeza commented
@legalsylvain please don't merge as is the PR, as you have included 7 useless commits, that are using more space, and are mixed on the commits view. Use "squash and merge" option if all commits come from the same author and can be grouped, or ask a logical squashing to the contributor otherwise.

2017-01-25 12:21 UTC, legalsylvain commented
@pedrobaeza. Thanks for this information (squash and merge), i didn't know this new feature. I'll do it for the next PRs.

kind regards.