[IMP] migrated to new API
OCA/web pull request #547
Opened 2017-02-02 21:29 UTC by ovnicraft

2017-03-02 22:42 UTC, ovnicraft commented
anyone for review it ?

2017-03-02 23:14 UTC, moylop260 commented
@oscarolar @hugho-ad
Could you help to review it, please?

2017-03-03 00:13 UTC, hugho-ad approved these changes

2017-03-03 07:28 UTC, simahawk commented on web_action_conditionable/__manifest__.py
> +    "version": "10.0.0.1.0",
shouldn't be 10.0.1.0.0?

2017-03-03 07:31 UTC, simahawk requested changes
Beside the version question I'd update xml view declaration to use ``<odoo />`` instead of ``<openerp /><data />`` see https://github.com/ovnicraft/web/blob/b7848efb45c613c33506455a7544eaf9cc0f883f/web_action_conditionable/views/view.xml

2017-03-07 20:15 UTC, ovnicraft commented
Done.
Ref for #435

2017-03-14 21:33 UTC, Fenkiou approved these changes
Tested and works as expected 👍

2018-10-07 05:22 UTC, ovnicraft commented
Hi ! possible merge this ?

2018-10-07 15:25 UTC, merged