[9.0][MIG][web_shortcut]
OCA/web pull request #564
Opened 2017-02-23 15:42 UTC by tarteo

Previously web_shortcuts

2017-02-24 08:16 UTC, astirpe requested changes
@tarteo Thank you!
See my comments on the code.

Could you also replace all the occurrences of `web_shortcuts` -> `web_shortcut` in every *.po file? This way the translation of all the already translated terms will be applied.
File `web_shortcuts.pot` can be removed (is not useful).

2017-02-24 08:16 UTC, astirpe commented on web_shortcut/README.rst
> +<https://github.com/OCA/162/issues>`_. In case of trouble, please
Must be `https://github.com/OCA/web/issues` here

2017-02-24 08:16 UTC, astirpe commented on web_shortcut/__openerp__.py
>      'website': 'http://openerp.com',
Please add `'license': 'AGPL-3',` in the manifest, otherwise it will take the LGPL licence which is the default for Odoo 9

2017-02-24 08:16 UTC, astirpe commented on web_shortcut/__openerp__.py
>      'author': "OpenERP SA,Odoo Community Association (OCA)",
Please replace the double quotes with single quotes, so this line will be consistent with the rest of the manifest

2017-02-24 08:50 UTC, tarteo commented
@astirpe Thanks for the review! I've made the changes you suggested.

2017-02-24 10:39 UTC, astirpe approved these changes

2017-02-24 14:28 UTC, simahawk requested changes

2017-02-24 14:28 UTC, simahawk commented on web_shortcut/models/ir_ui_menu.py
> +        for shortcut in shortcuts:
this could be just ``shortcuts.unlink()`` ;)

2017-02-24 14:28 UTC, simahawk commented on web_shortcut/static/src/js/web_shortcut.js
> +    var widget = require('web.Widget'),
you should keep classes' names CamelCase, ie:
```
var Widget = require('web.Widget'),
```

2017-02-24 14:58 UTC, tarteo commented
@simahawk I applied your suggestions. Thanks!

2017-02-24 15:05 UTC, simahawk approved these changes

2017-02-25 11:09 UTC, elicoidal requested changes
Short headers. Other than that LGTM

2017-02-25 11:09 UTC, elicoidal commented on web_shortcut/__init__.py
> +# -*- coding: utf-8 -*-
Please use short headers

2017-02-27 08:34 UTC, tarteo commented on web_shortcut/__init__.py
> +# -*- coding: utf-8 -*-
@elicoidal I've replaced the headers. Thanks!

2017-03-01 08:30 UTC, astirpe requested changes
@tarteo Please check also this new review.

2017-03-01 08:30 UTC, astirpe commented on web_shortcut/README.rst
> +To contribute to this module, please visit https://odoo-community.org.
You need to add this disclaimer: [https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#backporting-odoo-modules](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#backporting-odoo-modules)

2017-03-01 08:30 UTC, astirpe commented on web_shortcut/README.rst
> +* Dennis Sluijk <d.sluijk@onestein.nl>
You have to include Odoo S. A.

2017-03-01 09:32 UTC, tarteo commented on web_shortcut/README.rst
> +To contribute to this module, please visit https://odoo-community.org.
This is not a back port (8.0 -> 9.0). Do I still have to apply these conventions?

2017-03-01 09:52 UTC, astirpe commented on web_shortcut/README.rst
> +To contribute to this module, please visit https://odoo-community.org.
Yes please, just replace `backport` with `port`

2017-03-01 10:30 UTC, astirpe approved these changes

2017-03-01 10:31 UTC, astirpe commented
@elicoidal could you give a look to the headers?

2017-03-17 15:53 UTC, tarteo commented
Can we merge?

2017-07-28 09:14 UTC, astirpe commented
@elicoidal your approval is still pending, this PR is on hold since a long time

2017-07-28 09:32 UTC, elicoidal approved these changes

2017-07-28 09:32 UTC, merged