[ADD[ web_widget_date_interval
OCA/web pull request #575
Opened 2017-03-08 17:26 UTC by hbrunn

Date intervals
==============

This module was written to allow users to select some visual presentation of an interval instead of selecting a begin or end date.

Usage
=====

To use this module, use the widget ``date_interval`` on the field representing the begin of the interval. Make sure to also add the field representing the end of the interval, usually as hidden. Also add an ``options`` dictionary where you at least set the keys ``type`` and ``end_field``.

Depending on the type, you can add more configuration in the options dictionary, see below for a list.

weeknumber_iso
--------------

``hide_years``
    if this is set, don't show a year selection
``years_before``
    allow the user to move to N years before the current date (or the field's value)
``years_after``
    allow the user to move to N years after the current date (or the field's value)

Example::

    <field name="date_start" widget="date_interval" options="{'type': 'weeknumber_iso', 'end_field': 'date_end'}" />

Roadmap
=======

* add more interval types

2017-03-10 07:46 UTC, bealdav commented
Just tested

![capture du 2017-03-10 08-45-58](https://cloud.githubusercontent.com/assets/1853434/23786570/0e825bb2-056e-11e7-8502-ecaf5910a9d7.png)

2017-03-10 18:08 UTC, hbrunn commented
I'm discussing with the client to change the dropdown to a (configurable) list of buttons for the weeks that 'scroll' just like the years do. Any opinions about that in the community? And if we have that, do we want this as alternative for the dropdown or replace it entirely?

2018-05-03 07:41 UTC, simahawk requested changes
small things, other than that LGTM

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
png

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/README.rst
> +weeknumber_iso
"Widget options" sounds better

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/README.rst
> +* Odoo Community Association: `Icon <https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg>`_.
png

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/README.rst
> +Contributors
can you update this section according to https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst#credits ?

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/__init__.py
> +# © 2017 Therp BV <http://therp.nl>
Copyright

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/__openerp__.py
> +    "category": "Hidden/Dependency",
`'website': 'https://github.com/OCA/web',`

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/README.rst
> +
you might want to mention how to test that w/ the demo view

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                    throw 'Pass a type in the options dictionary!';
no translate?

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                'weeknumber_iso_onchange_year',
I'd indent the value lines

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/static/src/xml/web_widget_date_interval.xml
> +                >
you can shrink this in one line

2018-05-03 07:41 UTC, simahawk commented on web_widget_date_interval/static/src/xml/web_widget_date_interval.xml
> +                    >
same

2018-05-07 08:21 UTC, hbrunn commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                    throw 'Pass a type in the options dictionary!';
that's an error message for a developer

2018-05-07 08:21 UTC, hbrunn commented on web_widget_date_interval/static/src/xml/web_widget_date_interval.xml
> +                >
i prefer not, if we ever change something here this will be more more diff friendly than a big xml line

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +            events: {
Maybe it would be better to use https://backbonejs.org/#Model-extend here.

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                this.on('change:value', this, this.reinitialize);
Couldn't this be done on the `events`? Also, looking at `ReinitializeWidgetMixin` this seems to be better suited at the end of `Widget.start()`

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                var local = date.clone().clearTime().add(12).hours();
Why not `date.clone().clearTime().add({hours: 12})`?

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                for (
I have the feeling that all of this can be replaced with https://underscorejs.org/#range

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                    max_week = 52;
This can fail for years that do not have 52 weeks.

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                for (var week=min_week; week <= max_week; week++) {
Same here, can we use `_.range(min_week, max_week)`

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +            weeknumber_iso_get_weeks: function () {
As I understand, this function given a date it returns a range of weeks before and after that date while simultaneously tries to guard so as not to got to the next or to the previous year.

Why not use https://github.com/datejs/Datejs/blob/master/src/core.js#L352 and then get the range with a negative step and then with a positive up until you hit 1 or `last_day.december().moveToLastDayOfMonth().getISOWeek()`?

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +                        'Pass an end field in the options dictionary');
I modified the view from the front end and this was poping up all the time and I had to use postgres replace functions to fix the view. Maybe remove it and silently fail? The users should read `usage` on readme.

2019-05-16 15:29 UTC, daramousk commented on web_widget_date_interval/static/src/js/web_widget_date_interval.js
> +            weeknumber_iso_date_from_week: function (year, week) {
A little bit confused here with the ISO references. What are the advantages of using that ISO calendar system?

2022-03-27 12:31 UTC, closed without merging