[FIX][web_export_view] Remove monetary formatting
OCA/web pull request #594
Opened 2017-03-30 08:17 UTC by Yajo

Monetary fields were being exported empty because the parsing failed.

In the way of correctly exporting them as numbers, this chunk of code's performance has been improved.

This is a forward-port of #592.

@Tecnativa

2017-03-30 08:55 UTC, rafaelbn commented
@Yajo I cannot test it, runbot see:

![2017-03-30_10-54-51](https://cloud.githubusercontent.com/assets/8736623/24496004/5a882234-1537-11e7-9861-96da542ed806.png)

2017-03-30 09:36 UTC, chienandalu requested changes

2017-03-30 09:36 UTC, chienandalu commented on web_export_view/static/src/js/web_export_view.js
> +                                    .replace(/[^\d\.-]/g, "");
There is semicolon here that avoids proper enclosure

2017-03-31 11:50 UTC, chienandalu approved these changes
tested on runbot

2017-03-31 11:55 UTC, pedrobaeza approved these changes
Working as expected on runbot

2017-03-31 11:55 UTC, merged