migrate web_advanced_search_x2x to Odoo10
OCA/web pull request #600
Opened 2017-04-18 12:49 UTC by rami-wafaie

2017-04-18 12:52 UTC, hbrunn commented
you should follow the (guide)[https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0] to move commits from one version to the other, don't do this in one big commit

2017-04-18 13:00 UTC, rami-wafaie commented
@hbrunn Thanks for the feedback, This guidlines is very helpfull (This is my first odoo 10 Migration contribution) should I close this MR and open a new one with the new guidlines?
The code changes for odoo 10 are not that big just some small adjustments to the js file and in the qweb template

2017-04-18 13:08 UTC, hbrunn commented
just force push your new branch over this one, no need for a new PR

2017-04-19 09:07 UTC, rami-wafaie commented
Done

2017-04-19 09:35 UTC, hbrunn requested changes

2017-04-19 09:35 UTC, hbrunn commented on web_advanced_search_x2x/static/src/js/web_advanced_search_x2x.js
> + * Copyright 2017 Rami Alwafaie <rami.alwafaie@initos.com>
I don't believe changing two lines merits a copyright claim

2017-04-19 09:35 UTC, hbrunn commented on web_advanced_search_x2x/__manifest__.py
> +              "initOS GmbH, "
you're a contributor, not an author

2017-04-19 10:21 UTC, hbrunn approved these changes

2017-05-29 10:06 UTC, felixvillafranca approved these changes
Funtional review Ok.

2017-05-29 10:09 UTC, yajo approved these changes
Code OK

2017-05-29 10:09 UTC, merged