[10.0][ADD] Group "Edit Favicon" in web_favicon
OCA/web pull request #607
Opened 2017-04-24 14:09 UTC by tarteo

This addition adds a group "Edit Favicon" which allows a user (if member of) to edit the favicon of companies.

I can also use base.group_system, but I thought creating a new group would be nicer.

2017-04-26 09:35 UTC, dreispt commented
Why a new group just for this?
I would rather (re)use the Configuration grosup `base.group_system`.

2017-04-26 09:45 UTC, tarteo commented
@dreispt To make it more flexible.

2017-04-26 09:50 UTC, tarteo commented
@dreispt But I've no problem with changing it to base.group_system as I mentioned in the description of this PR. What do you think?

2017-04-26 09:51 UTC, dreispt commented
IMO it's not worth a new group, but let's see what others think.
BTW, +1 for the feature 😄

2017-05-31 08:38 UTC, felixvillafranca requested changes
The idea is good, but adding a grup just for this makes no sense.

2017-05-31 08:38 UTC, felixvillafranca commented on web_favicon/security/web_favicon_security.xml
> +    <record id="group_edit_favicon" model="res.groups">
I agree with @dreispt, remove the group please and use the one provided by Odoo.

2017-05-31 08:48 UTC, yajo requested changes

2017-05-31 08:48 UTC, Yajo commented on web_favicon/views/res_company.xml
> +                <page string="Web Favicon" name="favicon" groups="web_favicon.group_edit_favicon">
If you do what have been asked, this PR would amount to this single line (although fixed), so please squash and leave just 1 commit too.

Thanks!

2017-05-31 09:26 UTC, yajo requested changes

2017-05-31 09:26 UTC, Yajo commented on web_favicon/__manifest__.py
> +        'views/res_company.xml',
why?

2017-05-31 09:49 UTC, yajo approved these changes

2017-05-31 09:52 UTC, felixvillafranca approved these changes
Great ¡¡¡

2017-05-31 09:59 UTC, tarteo commented
Moved it to https://github.com/OCA/web/pull/645 I was unable to squash @felixvillafranca @Yajo @dreispt

2017-05-31 10:01 UTC, Yajo commented
Don't worry, I will squash at merge.

2017-05-31 10:01 UTC, tarteo commented
@Yajo Thanks!

2017-05-31 18:05 UTC, astirpe approved these changes

2017-06-01 09:28 UTC, dreispt commented
Build is failing because of the `help_online` module...

2017-06-01 10:33 UTC, astirpe commented
The travis issue seems something related with PR #584 on module `help_online`. I think the fixing must be tracked on a different issue, other than this PR.

Can we safely merge this PR then? It only contains a simple change in the view...

2017-06-01 11:13 UTC, dreispt commented
If there is no hurry, I would rather wait for the build to be fixed and then rebase this to get a green build.

2017-06-01 11:33 UTC, astirpe commented
No hurry, of course. It was just for the sake of satisfaction towards all the contributors of this PR. Lets make the build green first!

2017-06-01 11:36 UTC, lmignon commented
@dreispt @dreispt I propose a revert of the merged PR introducing the bug https://github.com/OCA/web/pull/647
For the record I'm not the author of the line introducing the bug.... this line has been added at merge time and squashed into mine commits....

2017-06-01 12:15 UTC, dreispt commented
@lmignon Stay cool! 🕶 
Code sprints can be fast moving and sometimes people can make wrong calls.
I'm sure it will get fixed soon.

2017-06-01 15:01 UTC, Yajo commented
https://github.com/OCA/web/pull/647 merged, please rebase

2017-06-02 08:06 UTC, tarteo commented
@Yajo Rebase done.

2017-06-02 08:44 UTC, astirpe commented
All green! :tada:

2017-06-02 09:48 UTC, merged