[MIG] Migration from 9.0 to 10.0 web_access_rule_buttons
OCA/web pull request #628
Opened 2017-05-17 18:52 UTC by daramousk

2017-05-17 18:57 UTC, pedrobaeza commented
It would be interesting to rename to singular as stated in the OCA guidelines.

2017-05-18 13:10 UTC, StefanRijnhart commented
@pedrobaeza Not sure in this case, as it does not refer to a data model but to the standard edit/create/delete __buttons__ in the interface.

2017-05-18 13:11 UTC, StefanRijnhart approved these changes

2017-05-30 14:53 UTC, felixvillafranca requested changes
It's Ok; but there is a variable unused.

2017-05-30 14:53 UTC, felixvillafranca commented on web_access_rule_buttons/static/src/js/web_access_rule_buttons.js
> +    var ListView = require("web.ListView");
This line could be removed

2017-05-30 15:36 UTC, yajo requested changes

2017-05-30 15:36 UTC, Yajo commented on web_access_rule_buttons/static/src/js/web_access_rule_buttons.js
> +	load_record() {
Sorry friend, we can't allow this syntax until it is supported by PhantomJS, or all JS tests would potentially break. You have to use the old, ugly and safe `load_record: function () {...` syntax.

2017-05-30 15:36 UTC, Yajo commented on web_access_rule_buttons/static/src/js/web_access_rule_buttons.js
> +		self.show_hide_buttons()
Feels better IMHO to proxy the function like `this._super.apply(this, arguments).then($.proxy(this.show_hide_buttons, this))`

2017-05-30 15:36 UTC, Yajo commented on web_access_rule_buttons/static/src/js/web_access_rule_buttons.js
> +		console.log(accesses)
IMHO this deserves a `console.debug` instead. Please add semicolon.

2017-05-30 15:36 UTC, Yajo commented on web_access_rule_buttons/static/src/js/web_access_rule_buttons.js
> +		    button.prop("disabled", !access);
4 spaces, no tabs.

2017-06-03 11:25 UTC, daramousk commented
@Yajo Changes implemented

2017-06-03 16:42 UTC, felixvillafranca approved these changes
Change Ok.
Funtional Ok.

2017-06-05 10:14 UTC, yajo approved these changes

2017-06-05 10:15 UTC, merged

2017-06-05 10:18 UTC, pedrobaeza commented
I would like to have this renamed to singular, but too late... Maybe on v10?

2017-06-05 10:18 UTC, pedrobaeza commented
Ouch, I see that this is v10. Uf, too bad. Can you maybe make a PR renaming it?