Fix [8.0] Perf issue with web_m2x_options #615
OCA/web pull request #641
Opened 2017-05-29 15:27 UTC by hparfr

Before : 
if no options specified after each keystroke, a call to check_access_rights is made

After:
a call is done once per field

Each request saved improves perf for user and load on the server.

+ some fixes on `parseInt` : always specify a radix
+ refactor  `is_option_set`

2017-05-29 20:47 UTC, pedrobaeza commented
@Yajo please check

2017-05-30 08:01 UTC, yajo requested changes
The idea is good, but you still need to change some things.

2017-05-30 08:01 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                true: true,
This is not doing what you expect. Object keys are never bools, just a `"true"` string.
What you want to do is `return $.inArray(option, [true, "true", "True"])`.

2017-05-30 08:01 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                this.limit = parseInt(this.view.ir_options['web_m2x_options.limit'],10);
According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Parameters), please revert this change.

2017-05-30 08:01 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                this.limit = parseInt(this.view.ir_options['web_m2x_options.limit'], 10);
As said above, revert this.

2017-05-30 08:01 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                        var id = parseInt(jQuery(this).attr('data-id'), 10);
Revert this.

2017-05-30 08:03 UTC, hparfr commented on web_m2x_options/static/src/js/form.js
> +                this.limit = parseInt(this.view.ir_options['web_m2x_options.limit'],10);
According to MDN: 
>Always specify this parameter to eliminate reader confusion and to guarantee predictable behavior.

2017-05-30 08:04 UTC, Yajo commented on web_m2x_options/static/src/js/form.js
> +                this.limit = parseInt(this.view.ir_options['web_m2x_options.limit'],10);
Oops sorry, I mistaked the diff, somehow it was in my mind that you were *removing* it, while you were adding it. Then for get my comments about this 😅

2017-05-30 08:06 UTC, hparfr commented on web_m2x_options/static/src/js/form.js
> +                true: true,
True, I will revert it.

2017-05-30 08:35 UTC, yajo approved these changes
Will squash at merge.

2017-05-30 10:24 UTC, jesusVMayor approved these changes

2017-05-30 10:31 UTC, merged

2017-05-30 10:31 UTC, pedrobaeza commented
Does it happen also in 9.0/10.0?

2017-05-30 10:35 UTC, hparfr commented
Thanks guys :)