[10.0][MIG]migrate web_widget_timepicker
OCA/web pull request #656
Opened 2017-06-26 18:30 UTC by smurf-U

2017-07-20 20:44 UTC, Jerther commented
I'm writing a new 10.0 module and I would gladly use this. I'm willing to contribute too if this PR merge can be sped up.

2017-07-20 20:46 UTC, pedrobaeza commented
Please review if the migration is correct and put it here.

2017-07-21 13:01 UTC, Jerther requested changes
README.rst needs to be replaced with new template. See  https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/js/web_widget_timepicker.js
> +        is_syntax_valid: function () {
Remove space between function and () (preserve coding style accross file)

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/js/web_widget_timepicker.js
> +                } catch (e) {
Remove space between catch and (e) (preserve coding style accross file)

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/js/web_widget_timepicker.js
> +        is_false: function () {
Remove space between function and () (preserve coding style accross file)

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/js/web_widget_timepicker.js
> +        focus: function () {
Remove space between function and () (preserve coding style accross file)

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/js/web_widget_timepicker.js
> +        parse_value: function (val, def) {
Remove space between function and (val, def) (preserve coding style accross file)

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/js/web_widget_timepicker.js
> +        format_value: function (val, def) {
Remove space between function and (val, def) (preserve coding style accross file)

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/js/web_widget_timepicker.js
> +        render_value: function () {
Remove space between function and () (preserve coding style accross file)

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/js/web_widget_timepicker.js
> +            if (!this.get("effective_readonly")) {
Remove space between if and () (preserve coding style accross file)

2017-07-21 13:01 UTC, Jerther commented on web_widget_timepicker/static/src/xml/web_widget_timepicker.xml
>                  <span class="fa fa-clock-o o_timepicker_button"/>
Clock icon appears under dropdown box
![image](https://user-images.githubusercontent.com/5856745/28464274-6e20d8e0-6df2-11e7-9498-c958e888f91f.png)

2017-07-21 13:10 UTC, Jerther requested changes
It would also be a good opportunity to upgrade the jquery plugin which is v1.10.1 to v1.11.11

2017-07-21 17:02 UTC, smurf-U commented
@Jerther jquery plugin v1.10.1 upgrade in last commit to v1.11.11 and done with all changs..

2017-07-21 17:48 UTC, Jerther approved these changes
That was quick! :)
Looks good to me!

2017-07-21 18:52 UTC, moylop260 commented
Could you follow the script:
 - https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

2017-07-21 19:15 UTC, moylop260 commented
I'm using the runbot instance and I just change the Stock's view for the fields.Datetime `min_date` to add this widget.
 - ![screen shot 2017-07-21 at 14 27 40](https://user-images.githubusercontent.com/6644187/28478624-d882add6-6e1e-11e7-8c1a-a6f1fd61190d.png)
   - http://3298939-656-b97d2f.runbot2.odoo-community.org/web?debug=1#id=698&view_type=form&model=ir.ui.view&action=25

But is not displayed:
 - ![screen shot 2017-07-21 at 14 27 56](https://user-images.githubusercontent.com/6644187/28478623-d8811b24-6e1e-11e7-83c2-4920e96d7a4c.png)
   - http://3298939-656-b97d2f.runbot2.odoo-community.org/web?debug=1#id=7&view_type=form&model=stock.picking&action=301&active_id=1

What is wrong?

2017-07-21 19:27 UTC, smurf-U commented
@moylop260 why you use timepicker widget with field whose type datetime? odoo have default datetime widget.

2017-07-21 20:04 UTC, Jerther commented
@moylop260  The underlying field must be `fields.Float()`.

2017-07-21 20:13 UTC, moylop260 commented
Thank for clarify
 - ![screen shot 2017-07-21 at 15 26 53](https://user-images.githubusercontent.com/6644187/28480611-11c69e2e-6e27-11e7-8843-043fc0037650.png)

👍

2017-08-16 13:56 UTC, Jerther commented
Ping

2017-08-23 12:37 UTC, katyukha commented
Hope this PR will be merged soon!

Thanks for porting)

2017-08-23 17:10 UTC, merged

2017-08-23 17:50 UTC, katyukha commented
@moylop260 thanks)

2017-09-21 06:58 UTC, vcloud9ray commented
In the Enterprise Edition, it shows the times perfectly in the dropdown, but if you click 7.30 then the value in the field turns into 7.5.

Did the value after selection match the value in the dropdown when you tested?

2017-09-22 05:52 UTC, vcloud9ray commented
Had to change the python field to Char and also change the JavaScript internal_format: 'char' for this to work properly (show 8:30 in the field instead of 8.5 when 8:30 was selected).  Then, behind the scenes I needed to create a float version of the field and deduce the float_time value.

2017-09-27 22:42 UTC, vcloud9ray commented
Had to comment out the <span class="fa fa-clock-o o_timepicker_button"/> because in Enterprise is doesn't sit beside the field, but rather shows up in the middle of other fields in the list and looks very ugly.