[10.0] [FIX] [web_timeline] Correct write when grouped by
OCA/web pull request #678
Opened 2017-07-20 07:43 UTC by JBF91

When you are working with the timeline view and you have grouped your items, you can extend or reduce the time duration of each item, but also change the group they belong, by dragging up or down the record.

I think that changing the group does not work as it should, since is writing the record but having as reference the "default_group_by" defined in the view attrs, instead of the current "group_by" condition defined in the search view box.

I've made a fix and tested myself but just for a while. Hope is useful

2017-07-20 07:45 UTC, pedrobaeza commented
Thanks for the patch. Please don't add extra blank lines. They don't add anything and make less clear the code read.

2017-07-20 07:45 UTC, pedrobaeza commented
And please sign the CLA.

2017-07-20 08:28 UTC, pedrobaeza requested changes

2017-07-20 08:28 UTC, pedrobaeza commented on web_timeline/static/src/js/web_timeline.js
> +            this.grouped_by = group_bys
`;` at the end

2017-07-20 08:28 UTC, pedrobaeza commented on web_timeline/static/src/js/web_timeline.js
> +            if(self.grouped_by){
space between `if` and the expression

2017-07-20 08:28 UTC, pedrobaeza commented on web_timeline/static/src/js/web_timeline.js
> +                data[self.grouped_by[0]] = group
`;` at the end.

2017-07-20 08:34 UTC, pedrobaeza approved these changes

2017-08-17 11:35 UTC, hbrunn approved these changes

2017-08-17 11:35 UTC, merged