[MIG] web_switch_company_warning to 10.0 Migration
OCA/web pull request #722
Opened 2017-09-08 15:18 UTC by hparfr

2017-09-11 14:51 UTC, bealdav approved these changes

2017-10-11 21:15 UTC, legalsylvain commented
is it this PR "need fixing" ? @Yajo

2017-10-17 07:53 UTC, yajo requested changes

2017-10-17 07:53 UTC, Yajo commented on web_switch_company_warning/static/src/xml/switch_company_warning.xml
> +    <t t-name="WarningWidget">
Keep old namespaced name please.

2017-10-17 08:56 UTC, hparfr commented on web_switch_company_warning/static/src/xml/switch_company_warning.xml
> +    <t t-name="WarningWidget">
done

2017-10-17 09:19 UTC, yajo approved these changes

2017-11-21 09:44 UTC, merged