[10.0][MIG] web_widget_text_markdown : Migration to 10.0
OCA/web pull request #738
Opened 2017-10-03 10:03 UTC by phucngta

2017-10-03 10:24 UTC, yajo requested changes
I'd love to see demo data here, with any view implementing a markdown widget to be able to quickly test it.

2017-10-03 10:24 UTC, Yajo commented on web_widget_text_markdown/README.rst
> +It was tested on openerp trunk, 10.0 branch.
Remove this section, it makes not much sense, the addon is set to instalable, so it's implicitly expected to work

2017-10-03 10:24 UTC, Yajo commented on web_widget_text_markdown/__init__.py
> +# © 2017 Phuc.nt - <phuc.nt@komit-consulting.com>
I'd prefer to keep empty files empty

2017-10-03 10:24 UTC, Yajo commented on web_widget_text_markdown/__manifest__.py
> +# © 2017 Phuc.nt - <phuc.nt@komit-consulting.com>
Use "Copyright" word instead of symbol.

2017-10-22 15:15 UTC, njeudy commented
@Yajo I wil test this (it is a migration from my V9 module) and add some test / exemple I think

2017-10-22 15:22 UTC, njeudy reviewed
- Keep all contributors when migrating modules
- we should considere this one: https://github.com/OCA/web/pull/281
- As explain in pull 281, we should use  ace from odoo I think

2017-10-22 15:22 UTC, njeudy commented on web_widget_text_markdown/__manifest__.py
> -    'category': '',
Do not remove other contributor (sudokeys is one of them)

2017-10-22 15:22 UTC, njeudy commented on web_widget_text_markdown/__manifest__.py
> -    'website': 'http://www.sudokey.com',
Think website should now be OCA ?

2017-10-22 15:25 UTC, njeudy commented
@yajo @phucngta : I worked on V11 to and completly remove ace (I use ace from odoo) and new js way.

See this too: https://github.com/njeudy/web_widget_text_markdown

2017-10-24 08:31 UTC, yajo requested changes
I took a look at the demo and saw this:

![captura de pantalla de 2017-10-24 10-30-36](https://user-images.githubusercontent.com/973709/31932356-675db52e-b8a6-11e7-93ab-74d4095ca55f.png)


I have to admit the widget is pretty amazing, but please add this Less:

```less
.oe_form_field_markdown {
  width: 100%;
}
```

2017-12-08 20:33 UTC, njeudy approved these changes
Awesome, better than use ace editor like un V9.
Will port it to V11 very sooon.

2017-12-08 20:46 UTC, njeudy requested changes

2017-12-08 20:46 UTC, njeudy commented on web_widget_text_markdown/__manifest__.py
> +    'website': 'http://www.komit-consulting.com',
Should be https://github.com/OCA/web

2017-12-08 20:47 UTC, njeudy commented
@phucngta @jcdrubay can you sign oca CLA for your devs github account, will review this quick :)

2017-12-09 07:54 UTC, jcdrubay commented
@njeudy @OCA/core-maintainers  I think both CLA should be signed already. Is there a way to check? thanks, JC

2017-12-12 08:23 UTC, yajo approved these changes
The previous problem I reported is now fixed

2017-12-12 11:07 UTC, tafaRU approved these changes
Just tested on runbot.

2017-12-12 12:35 UTC, Yajo commented
@njeudy is your ❌ still valid?

2017-12-12 16:32 UTC, moylop260 requested changes

2017-12-12 16:32 UTC, moylop260 commented on web_widget_text_markdown/__manifest__.py
> +# Copyright 2017 phucngta - <phuc.nt@komit-consulting.com>
Don't remove the original Copyright, please

2017-12-12 16:32 UTC, moylop260 commented on web_widget_text_markdown/static/src/js/web_widget_text_markdown.js
> +/* Copyright 2017 phucngta - <phuc.nt@komit-consulting.com>
Adds other authors, please

2017-12-12 22:14 UTC, njeudy commented
@Yajo it is ok for me

2017-12-12 22:17 UTC, njeudy approved these changes
Ok for me code review and tests

2018-01-23 21:33 UTC, njeudy commented
@moylop260 can you check if always red for you ?

2018-01-24 17:45 UTC, moylop260 commented
Could you use the git script from wiki: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0?

2018-01-24 20:25 UTC, njeudy commented
@moylop260 don't understand your comment .. what is wrong in this migration ?

2018-01-24 23:51 UTC, moylop260 commented
A module migrated requires all history of commits from git.
The wiki have documented how to do it

This PR have a commit so dont have a old history commits

2018-02-07 08:13 UTC, phucngta commented
@moylop260 I tried to get old commits but it seems that does not have any commits in history. Plus, this module was already existed in branch 10.0 of OCA so i think my commit represents what i've changed in this module.

2018-02-09 05:21 UTC, phucngta commented
When i cloned oca-web branch 10.0 to migrate module web_widget_text_markdown, there already have this module was get from 9.0 on this branch so i can't get old history commit again?
(I have updated description to FIX)
@moylop260

2018-02-21 16:14 UTC, njeudy commented
@moylop260 @Yajo think we can merge this one as V9 was not ported so I think history is not a requierment (I was the original author of this module, and won't be hurted not to have history on this.)

I will migrate this one (with some new feature on V11) and want to keep history from now.

What do you think ?

2018-02-22 07:31 UTC, simahawk requested changes
ok this is not a `FIX` but a `MIG`... please, pay attention to PR titles ;)

Bare code review: LGTM.

About commit history: I don't see much important stuff to keep from the past, other contributors just add cosmetic things (like oca icons and so on).

Nevertheless I'm not sure is a good thing to break the rules for something that is really cheap to do.

2018-02-22 07:36 UTC, jcdrubay commented
We can resubmit next week taking into account all comments. Thanks @njeudy for your flexibility, yet we need to do the right thing ;)

2018-02-22 09:06 UTC, Yajo commented
If you wish, you can squash it by author and logical changeset, but keep history please; we're not Flectra :laughing:

2018-02-22 09:46 UTC, njeudy commented
@jcdrubay Ok ping me when you will resubmit and if you need assitance.

@Yajo : you're right .. I will wait for resubmit :) thanks all for your time.

2018-02-26 12:08 UTC, njeudy commented
@phucngta I think you improted history in a wrong Way, I see your commit to V10.0 MIG before history .. you have to:

- Import history
- Add your MIG commit

2018-02-27 03:18 UTC, phucngta commented
I have re-improted history @njeudy .

2018-02-27 09:04 UTC, njeudy commented
There is a bug on runbot, I can click on group menu to test / check .. think this is not related to this migration, will investigate .

2018-02-27 09:23 UTC, njeudy requested changes
Some details :)

2018-02-27 09:23 UTC, njeudy commented on web_widget_text_markdown/static/src/js/web_widget_text_markdown.js
> +                oe.web.format_value(
oe is not define

2018-02-27 09:23 UTC, njeudy commented on web_widget_text_markdown/static/src/xml/bootstrap_markdown.xml
> + * License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).-->
use https://www.gnu.org/licenses/agpl (https)

2018-02-27 09:23 UTC, njeudy commented on web_widget_text_markdown/views/main.xml
> + * License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).-->
http -> https

2018-02-27 11:17 UTC, njeudy approved these changes
Test on runbot and code review

2018-02-27 11:18 UTC, njeudy commented
@simahawk @moylop260 changes where done for me can you finalise your review and eventually merge ?

2018-02-27 11:57 UTC, simahawk approved these changes
I'd squash `[FIX] remove en.po that was erroneously created by transbot` into translation commit but LGTM

2018-03-01 13:56 UTC, njeudy commented
@moylop260 @Yajo Is it ok for you to merge ?

2018-03-03 09:30 UTC, njeudy commented
@Yajo can you remove availting-cla tag ? I think it's ok now
@moylop260 have you some time to finish review and merge :) thanks !

2018-03-07 15:00 UTC, njeudy commented
@moylop260 any blocking point ?

2018-03-14 23:51 UTC, merged

2018-03-15 11:00 UTC, njeudy commented
thanks @moylop260