Fix Chrome slow scroll
OCA/web pull request #742
Opened 2017-10-07 15:22 UTC by lasley

Test fix

#741

https://github.com/cubiq/iscroll/issues/1100

2017-10-07 17:20 UTC, mgielissen commented
Scrolling works now with Android/Chrome

2017-10-07 19:32 UTC, lasley commented
Alright I've applied the same fix without editing the iScroll library, and added a note to the readme to remove the patch once iScroll is updated (this is fixed upstream, but there isn't a new release yet)

2017-10-08 05:25 UTC, MosabWadea commented
So I tried this fix but I faced this error:
`Uncaught TypeError: Cannot read property 'options' of undefined
`
```
https://portal.hobbydistrict.com/web/content/3480-c08c6da/web.assets_backend.js:3427
Traceback:
TypeError: Cannot read property 'options' of undefined
    at HTMLBodyElement.setIScrollProbes (https://portal.hobbydistrict.com/web/content/3480-c08c6da/web.assets_backend.js:3427:2011)
    at HTMLBodyElement.dispatch (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:637:451)
    at HTMLBodyElement.elemData.handle (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:610:173)
    at Object.trigger (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:631:211)
    at HTMLBodyElement.<anonymous> (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:682:147)
    at Function.each (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:370:767)
    at jQuery.fn.init.each (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:358:643)
    at jQuery.fn.init.trigger (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:682:118)
    at HTMLBodyElement.triggerOpenedListeners (https://portal.hobbydistrict.com/web/content/3480-c08c6da/web.assets_backend.js:3424:162)
    at HTMLBodyElement.invokeCallbackOnAnimationEnd (https://portal.hobbydistrict.com/web/content/3480-c08c6da/web.assets_backend.js:3424:889)
```

I don't think it is from this fix but maybe I did something wrong or inundated library?

2017-10-10 11:57 UTC, pedrobaeza commented
I receive this error when clicking on the icon for showing the drawer, and the clicking outside the drawer (on Firefox on my PC):
```
TypeError: this.iscroll is undefined

http://3306323-742-52282f.runbot3.odoo-community.org/web/content/440-5cf7aed/web.assets_backend.js:3479
Traceback:
setIScrollProbes@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/440-5cf7aed/web.assets_backend.js:3479:1998
dispatch@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:637:378
add/elemData.handle@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:610:151
trigger@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:631:204
trigger/<@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:682:134
each@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:370:758
each@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:358:636
trigger@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:682:113
triggerOpenedListeners@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/440-5cf7aed/web.assets_backend.js:3476:156
invokeCallbackOnAnimationEnd@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/440-5cf7aed/web.assets_backend.js:3476:880
dispatch@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:637:378
add/elemData.handle@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:610:151
```

2017-10-12 16:49 UTC, lasley commented
a8f19a8 should fix the issue - my bad I forgot casing

2017-10-13 04:01 UTC, pedrobaeza commented
I have tested and now there's no error and scroll in PCs works correctly, but trying on my Android mobile with Chrome, I still need to make funny moves for scrolling: there's no possibility to tap and hold the finger for scrolling. Can you please check it?

2017-10-13 14:49 UTC, lasley commented
I stole my girlfriend's Android for the day - should be able to fix this now

2017-10-14 19:59 UTC, lasley commented
Alright this last change was working pretty solid for me yesterday and looks good on Runbot now. Someone want to confirm?

Fix was to upgrade iScroll to the bleeding edge revision, which contains the proper change. It was created 10 months ago and there have been no changes, so I figure it's got to be stable enough.

2017-10-14 20:17 UTC, pedrobaeza requested changes
Tried and working. There's still a strange effect on the header bar with the logo and the "< Apps" link, but I think it's not related with this issue.

2017-10-14 20:17 UTC, pedrobaeza approved these changes

2017-10-14 20:38 UTC, lasley commented
>  There's still a strange effect on the header bar with the logo and the "< Apps" link, but I think it's not related with this issue.

Is it this?

![image](https://user-images.githubusercontent.com/7397578/31579163-009b290c-b0e5-11e7-8f9a-da583c3a0420.png)

2017-10-14 22:05 UTC, pedrobaeza commented
Yeah, definitively

2017-10-14 22:18 UTC, rafaelbn approved these changes

2017-10-14 22:20 UTC, lasley commented
I can't replicate the header issue with the last commit

2017-10-14 22:25 UTC, lasley commented on web_responsive/static/src/js/web_responsive.js
> +                this.iScroll.options.probeType = 1;
This was actually the fix to the header issue - the transform thing I realized marginTop was more clear & basically the same.

2017-10-14 22:30 UTC, lasley commented on web_responsive/static/src/js/web_responsive.js
> +                this.iScroll.options.probeType = 1;
Hmmm maybe the marginTop isn't the same, I'm reverting that.

2017-10-15 00:00 UTC, pedrobaeza commented
Now it's working worst IMO

2017-10-16 14:38 UTC, lasley commented
Damn ok I removed the commits from after you mentioned the other header issue & created #756

2017-10-16 14:57 UTC, pedrobaeza commented
OK, merging this then. @angelmoya please take this for v11

2017-10-16 14:58 UTC, pedrobaeza commented
Should I squash?

2017-10-16 15:09 UTC, lasley commented
> Should I squash?

I went ahead and did it so my GPG is preserved. I'd say we're good for a merge on CI 🍏

2017-10-16 15:51 UTC, merged