[11.0][MIG] web_no_bubble: Migration to 11.0
OCA/web pull request #765
Opened 2017-10-19 13:01 UTC by oihane

2017-10-19 13:21 UTC, pedrobaeza commented
```
web_no_bubble/__manifest__.py:5: [C8101(manifest-required-author), ] Missing author required "Odoo Community Association (OCA)" in manifest file
```

2017-10-19 13:52 UTC, pedrobaeza approved these changes

2017-10-20 00:31 UTC, elicoidal approved these changes
no runbot to test but LGTM

2017-10-20 12:48 UTC, yajo requested changes

2017-10-20 12:48 UTC, Yajo commented on web_no_bubble/__manifest__.py
> +    ),
I think this is not used

2017-10-20 12:48 UTC, Yajo commented on web_no_bubble/__manifest__.py
> +    'website': 'https://www.savoirfairelinux.com',
Put repo or addon url

2017-10-20 12:48 UTC, Yajo commented on web_no_bubble/views/web_no_bubble.xml
> +    <data>
`<odoo>`

2017-10-23 15:22 UTC, oihane commented
@Yajo changes done
@elicoidal runbot is now working if you want to check again

2017-10-23 15:25 UTC, anajuaristi commented
WE STRONGLY NEED this module. Those bullets are really annoying.

Sorry for screaming. ;P

2017-10-24 03:53 UTC, elicoidal commented
@oihane sorry I cant get the runbot running...

2017-10-24 08:23 UTC, yajo approved these changes

2017-10-24 08:24 UTC, merged