[11.0][MIG] web_searchbar_full_width
OCA/web pull request #799
Opened 2017-11-14 11:44 UTC by carlosDomatix

2017-11-14 15:39 UTC, yajo approved these changes
Migration looks quite good, just some little suggestions to upgrade code to new standards.

2017-11-14 15:39 UTC, Yajo commented on web_searchbar_full_width/__init__.py
> +##############################################################################
Remove all of this.

2017-11-14 15:39 UTC, Yajo commented on web_searchbar_full_width/README.rst
> +`here <https://github.com/OCA/web/issues/new?body=module:%20web_searchbar_full_width%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior*
Update template

2017-11-14 15:39 UTC, Yajo commented on web_searchbar_full_width/__manifest__.py
> +##############################################################################
Use new, shorter, headers please.

2017-11-16 08:20 UTC, yajo requested changes

2017-11-16 08:20 UTC, Yajo commented on web_searchbar_full_width/__init__.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
I think you can completely drop this file. It's copyrighting 0 LOC.

In any case, it's AGPL

2017-11-16 08:20 UTC, Yajo commented on web_searchbar_full_width/__manifest__.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
AGPL

2017-11-20 08:58 UTC, simahawk requested changes
LGTM. Same remarks as Jairo

2017-11-20 08:59 UTC, simahawk requested changes
wrong button :)

2018-03-19 10:07 UTC, lfreeke commented
:+1: (test on runbot)

2018-03-25 17:59 UTC, pedrobaeza commented
As @Yajo's comments have been honoured, I merge.

2018-03-25 17:59 UTC, merged