[11.0] [MIG] web_favicon
OCA/web pull request #800
Opened 2017-11-14 15:54 UTC by misern2

Standard Migration

2017-11-14 16:03 UTC, pedrobaeza commented
Please squash together "OCA Transbot..." commits.

2017-11-14 16:08 UTC, misern2 commented
@pedrobaeza  done!

2017-11-16 08:16 UTC, yajo requested changes
Travis is failing: https://travis-ci.org/OCA/web/jobs/302012013#L901

2017-11-16 08:18 UTC, Yajo commented
Can't we just apply website's favicon into backend? Odoo 10+ already has this setting built in:

![captura de pantalla de 2017-11-16 09-17-37](https://user-images.githubusercontent.com/973709/32880771-1ebb1954-caaf-11e7-90f9-652b9769adee.png)

BTW you have failures, check travis.

2017-11-16 08:21 UTC, pedrobaeza commented
I prefer to have a separate one.

2017-11-17 11:48 UTC, misern2 commented
@pedrobaeza @Yajo Travis fixed.

2017-11-17 12:46 UTC, yajo approved these changes

2017-11-20 08:52 UTC, simahawk approved these changes

2017-11-20 08:52 UTC, simahawk commented on web_favicon/controllers/web_favicon.py
> +        if 'uid' in request.env.context:
wouldn't be better to check the sessio? 
```python
if request.session.uid:
    company = request.env.user.company_id
```

2018-01-05 04:33 UTC, phatnguyenuit requested changes

2018-01-05 04:33 UTC, phatnguyenuit commented on web_favicon/__init__.py
> +# -*- coding: utf-8 -*-
In python3 `# -*- coding: utf-8 -*-` it should be removed.

Same for the others python file in this pull request.

2018-03-25 17:44 UTC, pedrobaeza commented
As there are no blocking comments, I merge.

2018-03-25 17:44 UTC, merged