[ADD][10.0] web_kanban_sortable
OCA/web pull request #810
Opened 2017-11-23 15:20 UTC by fuentes010

In Odoo v8.0 it was possible to sort any kanban view if the model has a field named sequence.
This module enable again this functionality in v10.

It just enable drag&drop sorting if the model has a field named sequence.

2017-11-30 13:31 UTC, Yajo commented
It's not that odoo 10 doesn't support this, it's that it only supports it when rendering a grouped view. To add this to ungrouped views, I think the proper place would be a fix in odoo core, if you really need this.

2017-11-30 14:24 UTC, fuentes010 commented
Well... that's true I should have explain it better. I need it at v10 and I'm pretty sure that this change won't be accepted at a stable branch, don't you?

2017-12-01 08:30 UTC, Yajo commented
There are a couple of workarounds you can use:

a. Set a default filter for the user that needs this that includes a group by clause. This way he'll have grouping enabled by default.
b. Configure list view as the default one, where you can do ungrouped sorting.

Both are officially supported and just some clicks away, and you save to maintain one extra addon with 119 LOC. Then you could close this. Just trying to KISS. What do you think?

2019-04-27 15:04 UTC, rousseldenis commented
@fuentes010

2019-04-29 04:31 UTC, nikul-serpentcs requested changes
Minor Change

2019-04-29 04:31 UTC, nikul-serpentcs commented on web_kanban_sortable/__manifest__.py
> +    'website': "https://www.studio73.es",
URL should be `https://github.com/OCA/web`

2019-04-29 13:29 UTC, closed without merging

2019-04-29 13:30 UTC, fuentes010 commented
We're don't need this anymore. If someone needs it feel free to contact.