[NEW][11] Tree view color row
OCA/web pull request #839
Opened 2018-01-13 11:43 UTC by fmdl

Dear

In V11, the attribute `colors` in tree view is no more supported by Odoo (deprecated from V9). It replace by the decoration system. But if you would like to hard a new color, it is very hard (you need to modifiy python code, rng, javascript and css).

This module re-add the old fonctionality exemple : `colors="blue:tetris == 'blue';red:tetris == 'red'"`.

Questions:
- for compatibility would like keep this coding (with `:` and `;`) ?
- or change the system to allow to use CSS, exemple colors="{css_blue: python_code;...}"

@pedrobaeza what do you think ?

2018-01-13 11:55 UTC, elicoidal requested changes
Thanks for the contribution

2018-01-13 11:55 UTC, elicoidal commented on web_tree_color/README.md
> +Web Tree Color
You need to add a README.rst following https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-01-13 11:55 UTC, elicoidal commented on web_tree_color/__init__.py
> +# -*- coding: utf-8 -*-
no coding line in v11

2018-01-13 11:55 UTC, elicoidal commented on web_tree_color/__manifest__.py
> +# -*- coding: utf-8 -*-
please add short headers

2018-01-13 11:55 UTC, elicoidal commented on web_tree_color/__manifest__.py
> +    'version': '1.0',
11.0.1.0.0

2018-01-13 11:55 UTC, elicoidal commented on web_tree_color/__manifest__.py
> +    'website': 'https://github.com/fmdl',
This repo

2018-01-13 11:55 UTC, elicoidal commented on web_tree_color/static/src/js/list_view.js
> +
add copyright

2018-01-13 11:55 UTC, elicoidal commented on web_tree_color/__manifest__.py
> +    'demo': [],
please remove empty or default keys

2018-01-13 12:01 UTC, fmdl commented
Dear @elicoidal , thank for you comment.
My PR is not finish, I would like the approbation before finish a clean module.

2018-01-14 03:45 UTC, elicoidal commented
no problem: ping me when necessary

2018-01-27 21:46 UTC, fmdl commented on web_tree_color/static/src/js/list_view.js
> +
Do

2018-01-31 10:38 UTC, fmdl commented
@elicoidal can you merge ?

2018-01-31 10:42 UTC, pedrobaeza commented
There must be at least 2 reviewers. You can review other PRs and ask in exchange that they review yours.

2018-04-30 20:13 UTC, fmdl commented
@alnslang can you review ?

2018-04-30 20:30 UTC, fmdl commented on web_tree_color/static/src/js/list_view.js
> +
@elicoidal ping
Thanks

2018-05-01 00:51 UTC, elicoidal requested changes
small details. 
demo data are nice to have
LGTM (no test: but can I without demo data nor UT)

2018-05-01 00:51 UTC, elicoidal commented on web_tree_color/README.rst
> +* css standard name : red
remove space before ':'

2018-05-01 00:51 UTC, elicoidal commented on web_tree_color/README.rst
> +Known issues / Roadmap
remove if empty

2018-05-01 00:51 UTC, elicoidal commented on web_tree_color/README.rst
> +Bugs are tracked on `GitHub Issues
please correct the URL

2018-05-01 00:51 UTC, elicoidal commented on web_tree_color/README.rst
> +* Florent de Labarre
can you add a mail?

2018-05-01 00:51 UTC, elicoidal commented on web_tree_color/__manifest__.py
> +    'summary': "Web Tree Color",
a short description is appreciated

2018-05-01 00:51 UTC, elicoidal commented on web_tree_color/__manifest__.py
> +    'auto_install': False,
are the following 2 really needed?

2018-05-01 00:51 UTC, elicoidal commented on web_tree_color/__manifest__.py
> +    'data': ['views/web_tree_color.xml'],
do you have a way to add a simple demo data?
(nice to have)

2018-05-01 09:16 UTC, fmdl commented
@elicoidal runbot seems doesn't work, can you check ?

2018-05-01 10:20 UTC, elicoidal commented
I can access runbot but it is far too slow from my location (everypage needs 1 minute to load)

2018-05-01 10:58 UTC, elicoidal reviewed
I do not know how to test the feature: a real example with screenshot in the README would be nice to have.

2018-05-01 11:01 UTC, fmdl commented on web_tree_dynamic_colored_line/demo/res_partner.xml
> +    <record id="view_partner_tree" model="ir.ui.view">
@elicoidal I have add an demo file.

2018-05-02 02:23 UTC, elicoidal commented on web_tree_dynamic_colored_line/demo/res_partner.xml
> +    <record id="view_partner_tree" model="ir.ui.view">
Awesome!
I tried Runbot but it is empty (no menu at all)

2022-08-21 12:36 UTC, closed without merging