add load argument to ensure correct context split
OCA/web pull request #844
Opened 2018-01-22 17:38 UTC by tschanzt

Fixes the display of the inactive languages in the translation overlay. Although the field is already translated correctly it is not reflected in the dialog since the default value is loaded for languages other than the one currently selected by the user.

Before:
![screenshot from 2018-01-22 17-57-51](https://user-images.githubusercontent.com/358342/35233832-8b983f28-ff9f-11e7-80ec-b0dc079b8951.png)
Here we can see that the correct string for German is displayed but French and English are the same, since the non translated value is loaded. 

After:
![screenshot from 2018-01-22 17-46-01](https://user-images.githubusercontent.com/358342/35233902-bf855942-ff9f-11e7-9298-a51fc73fcdf2.png)
Here we now can see, that the French string is now translated and no longer uses the untranslated value.

The problem was, that in [split_context](https://github.com/odoo/odoo/blob/10.0/odoo/api.py#L290) it is checked if we provide more arguments than the method actually needs. If this is the case the last element of the argument list is treated as the context. Since [read](https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L2975) takes the load argument we need to provide it, so that the context is split correctly.

it would also be possible to use self.view.dataset._model.call which takes where we could specify the context as a kwarg.

2018-01-22 17:43 UTC, simahawk requested changes
LGTM. Just one nitpicking thing that makes reading logs easier: would you mind changing the commit message with something like:
```
[fix] web_translate_dialog: correct context split

Long description here (what you put in the PR description basically)```

2018-01-22 21:53 UTC, pedrobaeza commented
Please change module version number according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

2018-01-23 09:11 UTC, tschanzt commented
@simahawk @pedrobaeza I increased the version number and reworded my commit message.

2018-01-23 09:49 UTC, simahawk approved these changes

2018-01-23 09:55 UTC, pedrobaeza approved these changes

2018-01-23 13:05 UTC, grindtildeath approved these changes

2018-01-23 13:07 UTC, merged

2018-01-23 13:08 UTC, hbrunn commented
any reason not to just pass the context by [name](https://github.com/OCA/OCB/blob/10.0/addons/web/static/src/js/framework/model.js#L41) as it should be anyways?

2018-01-23 13:11 UTC, pedrobaeza commented
Agh, too late, I have merged. Do you see this a problem?

2018-01-23 13:26 UTC, hbrunn commented
not really, people usually (hopefully!) are careful with changing the signature of the read function.

You'd then also have to call the function on the model, not the dataset, because as written above, the dataset version only allows positional arguments.

2018-01-23 13:41 UTC, tschanzt commented
@hbrunn I wasn't sure which one would be better. So I did the one which looked like the smaller change to me.

2018-01-23 13:44 UTC, hbrunn commented
next time, better go for the bigger diff but safer call. But that's fine as it is I think.