[10.0][ADD] web_tab_focus
OCA/web pull request #852
Opened 2018-01-31 11:10 UTC by andreparames

This is a proposal for a module that allows a page/tab of a notebook to be automatically focused depending on the value of a given field of the record. I suggest reading the [README](https://github.com/acsone/web/blob/85e08a7e431544ace5551eb2e80ac2123ea8e2f7/web_tab_focus/README.rst). Suggestions regarding the syntax are welcome!

2018-03-23 11:58 UTC, tarteo approved these changes
Tested it on Runbot. 
It works great and is great to improve user experience. Thanks!

2018-03-23 11:58 UTC, tarteo commented on web_tab_focus/__manifest__.py
> +    ],
Can you remove the demo key? it's empty

2018-03-23 12:02 UTC, simahawk requested changes

2018-03-23 12:02 UTC, simahawk commented on web_tab_focus/__manifest__.py
> +    'website': "https://odoo-community.org",
https://github.com/OCA/web

2018-03-23 12:02 UTC, simahawk commented on web_tab_focus/__manifest__.py
> +    'application': False,
this too

2018-03-23 22:33 UTC, andreparames commented
Thanks for the suggestions @tarteo and @simahawk. I've pushed an update.

2018-03-27 15:32 UTC, simahawk approved these changes
LGTM. Travis is red because of bokeh broken dependency.
@lreficent have you find a solution? Seems the same bug you have here https://github.com/OCA/web/pull/889

2018-03-28 09:15 UTC, andreparames commented
@simahawk @lreficent I got Travis to use Python 2.7.13 by using https://github.com/praekeltfoundation/travis-pyenv.

I'm not sure if this should be merged to the main repo, though.

2018-03-29 11:14 UTC, lreficent commented
I actually opened a issue some time ago: https://github.com/OCA/web/issues/893

Please report your opinion there, and see if we get some expert feedback.

2018-04-28 13:41 UTC, simahawk commented
@andreparames can you rebase? the issue should be fixed now

2018-04-28 15:02 UTC, andreparames commented
@simahawk thanks for the heads-up, I've rebased.

2018-06-22 21:26 UTC, MeetKD approved these changes
LGTM

2021-12-04 15:14 UTC, dreispt commented
/ocabot merge nobump

2022-08-02 19:49 UTC, dreispt commented
/ocabot merge nobump

2023-01-15 12:31 UTC, closed without merging