Contribution: Adding module web_diagram_position
OCA/web pull request #879
Opened 2018-02-23 17:54 UTC by pnajman-modoolar

Hello,

Module ``web_diagram_position``  enables saving coordinates of the diagram view elements.

Kind Regards,
Petar

2018-02-25 06:33 UTC, elicoidal commented on web_diagram_position/README.rst
> +``xpos`` and ``ypos`` like in the example below.
adding a screenshot of the result would be a good nice-to-have

2018-02-25 06:33 UTC, elicoidal commented on web_diagram_position/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
see https://github.com/OCA/web/pull/881#pullrequestreview-99094143

2018-06-06 06:21 UTC, pnajman-modoolar commented
My apologies for such a long idle time. 
I've pushed fixes and if time allows me I'll push those images as well.

2018-06-06 18:22 UTC, MeetKD requested changes

2018-06-06 18:22 UTC, MeetKD commented on web_diagram_position/__manifest__.py
> +    "author": "Odoo Community Association (OCA), Modoolar",
OCA as author should be at last.

2018-06-06 18:22 UTC, MeetKD commented on web_diagram_position/__manifest__.py
> +    "website": "https://www.modoolar.com/",
add `"website": "https://github.com/OCA/web/"`

2018-06-07 05:28 UTC, pnajman-modoolar commented on web_diagram_position/__manifest__.py
> +    "author": "Odoo Community Association (OCA), Modoolar",
fxed

2018-06-07 05:29 UTC, pnajman-modoolar commented on web_diagram_position/__manifest__.py
> +    "website": "https://www.modoolar.com/",
Fixed

2018-06-07 06:14 UTC, pnajman-modoolar commented on web_diagram_position/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
Fixed

2018-06-07 15:14 UTC, pnajman-modoolar commented
Can we merge this with 11.0?

2018-06-07 16:25 UTC, pedrobaeza commented
Travis is still red

2018-06-07 17:15 UTC, pnajman-modoolar commented
I've looked at the travis log and I don't see anything directly related to the module.
I can see that following test failed: test_ui_web (odoo.addons.web_responsive.tests.test_ui.TestUi)

But, unfortunately I don't know what to do with that.
Any help, pointer in the right direction would be appreciated ...

2018-06-07 23:53 UTC, pedrobaeza commented
It seems that your module breaks something on `web_responsive` module, but JS part is unknown for me.

2018-06-15 10:43 UTC, pnajman-modoolar commented
We've run tests locally but we couldn't reproduce this error.
Anyways, our next step it to setup environment by using OCA maintainers tools + travis and see if we'd have luck with that ....

2018-06-21 12:04 UTC, pnajman-modoolar commented
Hi @pedrobaeza, travis and runbot are now green. What are the next steps?

2018-06-21 17:42 UTC, pedrobaeza commented
You have to find reviewers for your PR. Sometimes they appear spontaneously if the PR is of their interest. If not, you can review other PRs of the same repository or similar ones, and ask in exchange that they review yours.

@MeetKD has expressed a bit of interest, so maybe he can finish a review, but as you know, nothing guaranteed as this is a voluntary effort.

2018-06-22 13:55 UTC, MeetKD requested changes

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_controller.js
> +    },
You can remove this dictionary.

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_controller.js
> +        return context ? context.edit != undefined && !context.edit : false;
I think you can handle this with better way. You can use underscore js function to check if its undefined or not **_.isundefined()**

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_controller.js
> +            return this._super();
I am not sure but may b you can remove this lines. Can you please elaborate this changes, According to above lines your changes will only affect for project.workflow. Correct me if i am wrong here.

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_controller.js
> +            let renderer = pop.form_view.renderer;
This is non blocking but either use let or var. I would suggest dont mix it up.

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_controller.js
> +    },
I don't see any change in this method compared with original implementation. You can remove this method.

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_controller.js
> +    },
I don't see any change in this method compared with original implementation. You can remove this method.

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_renderer.js
> +        return model.nodes.attrs.xpos != undefined && model.nodes.attrs.ypos != undefined;
please improve with isundefined function.

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_renderer.js
> +        this.id_to_edge = {};
remove this line.

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/diagram_renderer.js
> +    },
Can we use the super method here, instead of overriding the whole method ?

2018-06-22 13:55 UTC, MeetKD commented on web_diagram_position/static/src/js/graph.js
> +})(window);
Cant you make changes by overriding this js ? I think there has to be a good way to handle this.

2018-10-31 13:56 UTC, closed without merging