Parse JSON only if not already object
OCA/web pull request #886
Opened 2018-03-06 20:39 UTC by guewen

I had a parse error because the options was already an object (an empty
{}).

2018-03-07 08:59 UTC, simahawk requested changes
small glitch + update version

2018-03-07 08:59 UTC, simahawk commented on web_tree_dynamic_colored_field/README.rst
> +            <field name="name" 'options="{fg_color": "white:customer == True"}'/>
mis-placed quotes
```xml
<field name="name" options='{fg_color": "white:customer == True"}'/>
```

2018-03-07 09:12 UTC, guewen commented on web_tree_dynamic_colored_field/README.rst
> +            <field name="name" 'options="{fg_color": "white:customer == True"}'/>
Fixed

2018-03-07 09:12 UTC, guewen commented
I corrected the misplaced quote + changed module version

2018-03-08 07:43 UTC, max3903 approved these changes
LGTM

2018-03-09 06:41 UTC, feketemihai approved these changes

2018-03-09 06:57 UTC, simahawk approved these changes

2018-03-09 08:36 UTC, pedrobaeza commented
One question: are you changing the syntax from previous versions of this module?

2018-03-16 09:22 UTC, LoisRForgeFlow approved these changes
Tested locally, thanks for this migration! :+1:

2018-03-16 16:49 UTC, merged