11.0 mig web_listview_range_select
OCA/web pull request #910
Opened 2018-04-11 19:56 UTC by aldo774

Migration of the web_listview_range_select module to v11

2018-04-13 12:07 UTC, mstuttgart approved these changes
It's working! Thanks :+1:

2018-04-13 13:20 UTC, tarteo requested changes
Thanks for migrating. I tested it on Runbot and it works perfectly.

2018-04-13 13:20 UTC, tarteo commented on web_listview_range_select/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/162/10.0
Please change this to 11.0

2018-04-13 13:20 UTC, tarteo commented on web_listview_range_select/__manifest__.py
> +    'website': 'http://www.onestein.eu',
Can you change the website to https://github.com/oca/web, please.

2018-04-13 13:20 UTC, tarteo commented on web_listview_range_select/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Please, update the README to comply the new template.

2018-04-13 19:27 UTC, aldo774 commented on web_listview_range_select/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Changes made :+1:

2018-04-13 19:38 UTC, aldo774 commented
Changes maded :+1:

2018-04-13 19:40 UTC, rodrigets approved these changes
LGTM :+1:

2018-04-13 21:21 UTC, rafaelbn approved these changes
Tested in runbot :+1: 

Please @tarteo review you review :smile: Thanks!

2018-04-14 19:42 UTC, tarteo approved these changes

2018-04-16 08:49 UTC, merged