11.0 migrate web_widget_datepicker_options
OCA/web pull request #924
Opened 2018-05-14 17:41 UTC by yaniaular

2018-05-14 20:22 UTC, yaniaular commented
@veloutin @yvaucher @sbidoul @pedrobaeza I have migrated this module and I need your approval to merge it, thanks.

2018-05-14 20:33 UTC, pedrobaeza commented
Hi @yaniaular, thanks for the migration, but I'm afraid this is not how it works. Reviewers can come to this PR because they are interested in the module itself, or you can review other PRs in the same repository or other similar ones and ask in exchange that they review yours. Current commit authors that you see can be general OCA maintainers like me and @sbidoul that don't know about the module itself, or even non active Odoo developers.

2018-05-14 20:55 UTC, yaniaular commented
@pedrobaeza I think you get me wrong. I didn't mean I was going to merge this. I just wanted to tell you that I've migrated the module and that you may review it. I do not have permission to merge it anyway.

2018-05-15 06:17 UTC, simahawk requested changes

2018-05-15 06:17 UTC, simahawk commented on web_widget_datepicker_options/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
png

2018-05-15 06:17 UTC, simahawk commented on web_widget_datepicker_options/README.rst
> +Bug Tracker
bug tracker and credits need update from template https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-05-15 06:17 UTC, simahawk commented on web_widget_datepicker_options/__init__.py
> +# -*- encoding: utf-8 -*-
remove encoding and use short license headers in all py files

2018-05-15 06:17 UTC, simahawk commented on web_widget_datepicker_options/__manifest__.py
> +    "license": "AGPL-3",
`'website': 'https://github.com/OCA/web',`

2018-05-15 06:17 UTC, simahawk commented on web_widget_datepicker_options/__manifest__.py
> +    "name": 'web_widget_datepicker_options',
```
'name': 'Web widget datepicker options',
'summary': 'Enhance customization for datepicker widgets',
```

2018-05-15 06:17 UTC, simahawk commented on web_widget_datepicker_options/static/src/js/datepicker.js
> +            if(typeof this.__parentedParent !== 'undefined' && this.__parentedParent.field.type === 'date' && this.__parentedParent.nodeOptions){
define `var parent = this.getParent();` and replace all `this.__parentedParent`

2018-05-15 06:17 UTC, simahawk commented on web_widget_datepicker_options/view/qweb.xml
> +<openerp>
s/openerp/odoo
remove `<data />`

2018-05-15 06:17 UTC, simahawk commented on web_widget_datepicker_options/README.rst
> +    <field name="date" options="{'datepicker':{'yearRange': 'c-100:c+0'}}"/>
Am I wrong or you should use JSON notation?
```xml
<field name="date" options='{"datepicker":{"yearRange": "c-100:c+0"}}'/>
```

2018-05-27 09:29 UTC, MeetKD commented on web_widget_datepicker_options/__manifest__.py
> +    ],
Add only web module dependency.

2018-05-28 01:32 UTC, luisg123v commented on web_widget_datepicker_options/README.rst
> +    <field name="date" options="{'datepicker':{'yearRange': 'c-100:c+0'}}"/>
@simahawk 
Both single and double quotes are possible, it keeps the same behavior as Odoo's native options.

2018-05-28 02:06 UTC, luisg123v commented
@simahawk & @MeetKD 
We applied all your requested changes. Also we edited the PR's description, to make clearer what this is all about.

If it's not too much, could you review again, please?

2018-05-28 10:51 UTC, simahawk approved these changes
LGTM. You could squash last 2 commits before merge.

2018-05-28 16:04 UTC, luisg123v commented
@simahawk 
Are you sure squashing is the way to go? Take into account the author differs for those commits.

2018-05-28 17:45 UTC, luisg123v commented
@moylop260 
Could you approve this PR, please?

2018-05-28 23:33 UTC, moylop260 commented
Could you squash the Yanina commits in one commit, please?

2018-05-29 00:38 UTC, luisg123v commented
@moylop260 
Done, commits were squashed as you requested

2018-05-29 08:08 UTC, yajo reviewed
I might be saying some stupidity, but [isn't this already what the v11 core widget does](https://github.com/odoo/odoo/blob/1039abfbdb1dcfd51e753874795721fc0d617485/addons/web/static/src/js/widgets/date_picker.js#L22-L57)?

2018-05-29 14:43 UTC, luisg123v commented
@Yajo 
AFAIK, it's not the same. That method merge a parameter named `options`, with some computed values. However, that parameter is not the options passed to the field in a view, but some common values that Odoo passes to all widgets

If you wan to, e.g. limit a field, the following won't work:
```
<field name="post_date" options="{'daysOfWeekDisabled': [0, 6]}"/>
```
But, with this module, you could do:
```
<field name="post_date" options="{'datepicker': {'daysOfWeekDisabled': [0, 6]}}"/>
```

2018-05-30 18:55 UTC, MeetKD approved these changes

2018-05-30 18:57 UTC, pedrobaeza commented
I think first 8 commits from same author can be squashed, as that commit history doesn't add anything useful. When done, I'll merge.

2018-05-30 19:09 UTC, yaniaular commented
@pedrobaeza Do you mean the veloutin's commits?

2018-05-30 19:14 UTC, pedrobaeza commented
Yeah, that's it

2018-05-30 19:50 UTC, luisg123v commented
@pedrobaeza 
Done, all commits from the same author were squashed.

2018-05-31 07:14 UTC, merged

2018-06-04 10:43 UTC, Yajo commented
Fixing this upstream is 1 LOC, I did it here: https://github.com/odoo/odoo/pull/25044

Let's hope they merge it and we need no more this addon :blush: