[IMP]Improved group by functionality.
OCA/web pull request #941
Opened 2018-05-31 21:49 UTC by MeetKD

1. Fixed the issue of expand shrink buttons showing on discuss menu.
2. Added debounce event when buttons are clicked.
3. Fixed the issue of buttons are added in FavoriteMenu.
4. Restructured the code to fix other various issue like only display group by expand buttons if group by button is visible. 
(NOTE: Earlier code was not honoring **disable_groupby** by flag in searchview)

2018-06-04 17:26 UTC, MeetKD commented
@simahawk can you please review this?

2018-06-06 07:18 UTC, simahawk requested changes

2018-06-06 07:18 UTC, simahawk commented on web_group_expand/static/src/js/web_group_expand.js
> +odoo.define('web.GroupByExpandMenu', function (require) {
module name should stay as namespace and I'd slit them into 2 files

2018-06-06 18:28 UTC, MeetKD commented on web_group_expand/static/src/js/web_group_expand.js
> +odoo.define('web.GroupByExpandMenu', function (require) {
@simahawk Can you please re-review ?? :smiley:

2018-06-07 14:11 UTC, aldo774 approved these changes
You did exactly what I wanted to do when I migrated this module, I couldn't for lack of experience, I learned by seeing your code, thanks.

2018-06-07 17:13 UTC, MeetKD commented
@aldo774 i am glad  and thank you for your kind words. :green_heart:

2018-06-07 18:56 UTC, pedrobaeza approved these changes

2018-06-07 18:57 UTC, merged