11.0 mig web widget slick
OCA/web pull request #958
Opened 2018-06-15 16:00 UTC by MeetKD

2018-06-15 17:46 UTC, MeetKD commented
I dont know why but build has been terminated. Can you please help ?

2018-06-26 07:22 UTC, simahawk approved these changes
overall LG. Build restarted

2018-06-26 07:22 UTC, simahawk commented on web_widget_slick/__manifest__.py
> +    "author": "LasLabs, Meet Dholakia, Odoo Community Association (OCA)",
if this is just a bare migration listing yourself in CONTRIBUTORS is enough :wink:

2018-06-26 07:22 UTC, simahawk commented on web_widget_slick/static/src/js/web_widget_slick.js
> +        this.$el.append(this.$slick);
instead of flushing and then appending later (flickering might happen) can't you do `this.$el.html(this.$slick)`?

2018-07-04 06:25 UTC, simahawk requested changes
some comments not addressed

2018-07-04 06:27 UTC, simahawk commented
also, this is failing like https://github.com/OCA/web/pull/971#issuecomment-402033806
https://travis-ci.org/OCA/web/jobs/392778083#L1409

2022-11-13 12:39 UTC, closed without merging