[IMP][11.0][web_responsive] Suggested changes
OCA/web pull request #978
Opened 2018-07-03 19:10 UTC by Tardo

Suggested changes in #540 (FieldStatus + Header Buttons)

2018-07-04 07:31 UTC, yajo requested changes
Thanks for the contribution and cleanup!

I'm seeing some weirdities:

![captura de pantalla de 2018-07-04 07-57-07](https://user-images.githubusercontent.com/973709/42261536-75162fda-7f60-11e8-9385-fec441c42c38.png)

TBH that was there before this PR, but now seems a good moment to fix it.

![captura de pantalla de 2018-07-04 07-57-46](https://user-images.githubusercontent.com/973709/42261755-17cdcd8c-7f61-11e8-9957-85a492159fa8.png)

Maybe to reduce the duplication, you can imagine a different word for it, or you can use a proper icon.

![captura de pantalla de 2018-07-04 07-57-57](https://user-images.githubusercontent.com/973709/42261757-1936f4e6-7f61-11e8-8a2d-1287dfd6b6c5.png)

I think that some of these problems come from the fact that [Bottstrap 3 expects a specific `.dropdown-menu>li>a` structure](https://getbootstrap.com/docs/3.3/components/#btn-dropdowns) to properly render a dropdown, and you're using buttons here.

So I would suggest trying this:

1. Action buttons

   - Render the structure Bootstrap expects separately from current one
   - Put all of that into a `<div class="hidden-lg hidden-md">`
   - Put upstream odoo buttons into a  `<div class="hidden-xs hidden-sm">`

2. State widget

   - This widget already supports folding. All you have to do is [override this method and set `fold: true` where needed](https://github.com/odoo/odoo/blob/daedcd92e36abdca43dd5580288311a05d87da24/addons/web/static/src/js/fields/relational_fields.js#L1996).

2018-07-04 07:31 UTC, yajo commented on web_responsive/static/src/js/web_responsive.js
> +            if (config.device.size_class <= config.device.SIZES.XS) {
Doing this through JS means that, if I resize the browser, I have to refresh to see the effects.

2018-07-05 11:32 UTC, Yajo commented on web_responsive/static/src/js/web_responsive.js
> +            // Break inheritance!
Is there a chance to break it in the qweb template instead, by replacing elements?

2018-08-01 12:09 UTC, pedrobaeza commented
@Yajo can you update your review here? I have launched a rebuild on runbot.

2018-08-01 12:12 UTC, yajo approved these changes
Code OK

2018-08-02 06:06 UTC, pedrobaeza approved these changes
Thanks for the improvements!

2018-08-02 06:07 UTC, merged