[11.0][MIG] web_advanced_search_wildcard
OCA/web pull request #985
Opened 2018-07-08 21:05 UTC by JBF91

Migration of web_advanced_search_wildcard.

No problems found, and no errors when using it, I thinks it's done.

2018-07-10 14:44 UTC, lfreeke commented
:+1: (functional test)

2018-07-11 00:43 UTC, elicoidal approved these changes
LGTM

2018-07-11 00:43 UTC, elicoidal commented on web_advanced_search_wildcard/static/src/js/search.js
> +odoo.define('web_advanced_search_wildcard', function (require) {
You could update copyright here

2018-07-11 00:43 UTC, elicoidal commented on web_advanced_search_wildcard/views/template.xml
> +<odoo>
and here

2018-07-11 08:52 UTC, Tardo requested changes

2018-07-11 08:52 UTC, Tardo commented on web_advanced_search_wildcard/README.rst
> +Contributors
Change this to the new structure for readme's

2018-07-11 08:58 UTC, Tardo commented
Despite the necessary changes, it seems to work correctly.

2018-07-12 06:15 UTC, simahawk approved these changes
only small changes needed

2018-07-12 06:15 UTC, simahawk commented on web_advanced_search_wildcard/__manifest__.py
> +    "application": False,
drop this flags, as they are defaults. 
Add `'website': 'https://github.com/OCA/web',`

2018-07-18 09:03 UTC, tarteo requested changes

2018-07-18 09:03 UTC, tarteo commented on web_advanced_search_wildcard/static/src/js/search.js
> +    Field.prototype.operators.push(
Can you use the class system here, something like:

```
Char.include({
      init: function() {
            this._super.apply(this, arguments);
            this.operators.push({value: '=ilike', text: _lt("matches")});
      }
})

```

2018-08-27 10:48 UTC, pedrobaeza commented
@JBF91 can you make the requested comments?

2018-09-03 07:42 UTC, JBF91 commented
@pedrobaeza Yes, I'm going to do it these days

2018-12-25 23:43 UTC, alexis-via approved these changes
code review, no test

2018-12-25 23:44 UTC, alexis-via commented
If you like it, you can include the improvement is proposed on the v10 branch https://github.com/OCA/web/pull/1142/files (adds "starts with" and "ends with" advanced search filters).

2019-01-08 14:31 UTC, simahawk commented
@JBF91 any update?

2019-11-11 09:18 UTC, NachoSerra commented
Hi, there seems to be an incompatibility when the module web_advanced_search is installed and filtering a many2one field. For example, in journal items, searching accounts starting with '%6' it returns journal items where the account id is 6.

2022-11-27 12:34 UTC, closed without merging